### ISSUE TITLE
[Story] Room list empty state

### ISSUE THREAD

**Issue by stefanceriu** [vector-im/element-meta#1016]
As a user that isn't part of any rooms
I want to see an empty state in the room list (instead of the skeletons)
so that I can be informed as to what the current state is

## Scope
*These should be a list of technical tasks which take ½-1 day to complete*
```[tasklist]
### Tasklist
- [ ] Task 1
```

- [ ] QA signoff on completion
- [ ] Design signoff on completion
- [ ] Product signoff on completion

##  Stretch goals
None at this time

## Out of scope
-

**Comment by amshakal** [comment]
Empty state work has already been done. I believe @pixlwave worked on it? [Design](https://www.figma.com/file/0MMNu7cTOzLOlWb7ctTkv3/Element-X?type=design&node-id=10168%3A73230&mode=design&t=jNz1NK4eEvz4lxgR-1)

**Comment by stefanceriu** [comment]
> Empty state work has already been done

It has, yes, thank you!
