### ISSUE TITLE
Show the invites list (UI only)

### ISSUE THREAD

**Issue by alfogrillo** [vector-im/element-meta#1018]
As a user that has been invited to a new conversation I want to join a room to read messages & chat w. other users.
- Invites shows on the "all chats" list.

**Designs**
- [iOS](https://www.figma.com/file/0MMNu7cTOzLOlWb7ctTkv3/Element-X-(new)?node-id=683%3A74364&t=6k57zCRQMIGXEeYd-1)
- [Android](https://www.figma.com/file/0MMNu7cTOzLOlWb7ctTkv3/Element-X-(new)?node-id=1076%3A77893&t=6k57zCRQMIGXEeYd-1)

**Matrix APIs**
No new APIs are required for this task. There's an [is_invite](https://github.com/matrix-org/matrix-spec-proposals/blob/64a6f495e9c6964ac567bf7fdc323cc543e1301b/proposals/3575-sync.md?plain=1#L416) filter on **sliding sync**.

**ACs**
- A label (copy: "Invites") with a badge shows on top of rooms when a new invite arrives.
    - The label should show just when at least one invite is available
    - The badge is always shown if the label is onscreen. Showing/Hiding just the badge will be done as a part of this [issue](https://github.com/vector-im/element-meta/issues/1158).
- A tap on the "Invites" CTA pushes the list of the invites in the navigation stack
- Each item will show different info depending on the invitation type:
    - For DM chat shows:
        - Avatar of the inviter
        - Display name of the inviter
        - Matrix id of the inviter
    - For normal rooms:
        - Avatar of the room
        - The name of the room
        - The canonical alias of the room (if any, otherwise hide the line)
        - The avatar of the inviter
        - A copy including the inviter's display name "%@ invited you" (e.g. "John invited you")
- Each item have two CTA to decline/accept the invitation
- No other functionality is included as a part of this ticket (e.g. navigation to an invite detail, accept/decline invites)
- In case no invites are available show a label with copy "No invites" with a design similar to [this](https://www.figma.com/file/0MMNu7cTOzLOlWb7ctTkv3/Element-X-(new)?node-id=479-76114&t=rWjXmdaotl56MVlL-0).

```[tasklist]
### Tasks

- [ ] https://github.com/vector-im/element-x-android/issues/102
- [ ] https://github.com/vector-im/element-x-ios/issues/605
```

**Comment by amshakal** [comment]
Invites designs for 
iOS: https://www.figma.com/file/0MMNu7cTOzLOlWb7ctTkv3/Element-X-(new)?node-id=683%3A74364&t=6k57zCRQMIGXEeYd-1

Android: https://www.figma.com/file/0MMNu7cTOzLOlWb7ctTkv3/Element-X-(new)?node-id=1076%3A77893&t=6k57zCRQMIGXEeYd-1
