### ISSUE TITLE
Devtool to create a new room encrypted with MLS

### ISSUE THREAD

**Issue by BillCarsonFr** [vector-im/element-meta#1027]

**Comment by uhoreg** [comment]
https://github.com/uhoreg/matrix-js-sdk/tree/mls_poc and https://github.com/uhoreg/matrix-react-sdk/tree/mls_poc

Added a toggle switch to the create room dialog

![Image](https://user-images.githubusercontent.com/1012976/224458271-8f1dbfe4-7cea-4b99-86fb-4a6437baa33f.png)
