### ISSUE TITLE
Receving MLS encrypted Messages

### ISSUE THREAD

**Issue by BillCarsonFr** [vector-im/element-meta#1029]

**Comment by uhoreg** [comment]
MLS messages sent between two devices of the same user:

![Image](https://user-images.githubusercontent.com/1012976/228066543-5f3855ff-4a2f-4812-83a2-0d3c3d8a4679.png)

Will work on multiple users (DM) next

**Comment by uhoreg** [comment]
> Will work on multiple users (DM) next

I've updated the code to handle multiple initial users, but getting it working in a DM may require extra UI code, so not going to do it now.
