### ISSUE TITLE
[Story] Show the send status of a message

### ISSUE THREAD

**Issue by VolkerJunginger** [vector-im/element-meta#1042]
As a user that has send a message I want to to know the status of the message so I know that I succeeded in sending the message.

- Show an indicator that the message has not yet reached the server (message not send)
- Show an indicator that the message has been recieved by the server (message send)
- If the message could not reach be received by the server show an error

## Scope
*These should be a list of technical tasks which take ½-1 day to complete*

- [x] QA signoff on completion
- [x] Design signoff on completion
- [x] Product signoff on completion

```[tasklist]
### iOS Tasklist
- [ ] https://github.com/vector-im/element-x-ios/issues/921
```

- [x] QA signoff on completion
- [x] Design signoff on completion
- [x] Product signoff on completion

##  Stretch goals
None at this time

## Out of scope
-

**Comment by Velin92** [comment]
https://www.figma.com/file/0MMNu7cTOzLOlWb7ctTkv3/Element-X?type=design&node-id=3738-151900&t=iaB60KV4j1WK5M7y-0

Currently working on the redesign for this, since that view space will be also required for read receipts

**Comment by Velin92** [comment]
This is done and completed on iOS
