### ISSUE TITLE
[Story] Show if a room has unread messages & mark room as "read"

### ISSUE THREAD

**Issue by VolkerJunginger** [vector-im/element-meta#1043]
As a user that has unread messages I want to see which rooms have unread messages in the room list so I have fast access to read them.

- Show an indicator for room with unread message in the room-cell in the room list
- Mark the room as "read" when the user has oppened the room. 
- - This is independent from the read status of the messages in the room
- - If a room has unread messages in a Thread still mark the room as read.

Remark
The indicator is more a "hint" for the user that there is a "todo" in the room then a "unread messages" indicator or even a counter. This fits also better with the very common behaviour of user marking rooms as "unread" to remind them self to answer later or to revisit the room at a better point in time.

We need to meet the fine line of making users aware and annoying them so it should be fairly easy to "remove" the unread indicator for a room. Todays behaviour of keeping a room un-read just because there are messages unread in a Thread is a god example of annoying behaviour - and it is inconsistent. While a room is marked as read even though I may not have been reading through all messages (especially in very big room with a high frequency of messaging) I am forced to visit every single thread or mark the room as un-read manually.

## Scope
*These should be a list of technical tasks which take ½-1 day to complete*
```[tasklist]
### Tasklist
- [x] Implementation
- [x] QA signoff on completion
- [x] Design signoff on completion
- [x] Product signoff on completion
- [ ] https://github.com/vector-im/element-x-ios/issues/639
- [ ] https://github.com/vector-im/element-meta/issues/1977
```

##  Stretch goals
None at this time
<or add a tasklist>

## Out of scope
-

**Comment by callumu** [comment]
Bug from a room that has predominantly images


https://github.com/vector-im/element-meta/assets/110109933/8deef4c1-2315-465b-9459-6d1fc8b2e027
