### ISSUE TITLE
[Story] Search a user to start a chat

### ISSUE THREAD

**Issue by alfogrillo** [vector-im/element-meta#1055]
As a user I want to find other people to chat with even If I don't have their matrix id

## Scope

```[tasklist]
### Engineering
- [ ] https://github.com/vector-im/element-meta/issues/1013
- [ ] https://github.com/vector-im/element-meta/issues/1056
- [ ] https://github.com/vector-im/element-meta/issues/1172
```

## Out of scope

- Nothing at the moment

## Sign-off

```[tasklist]
### Android
- [x] Design sign-off on completion
- [x] QA sign-off on completion
- [x] Product sign-off on completion
```

```[tasklist]
### iOS
- [x] Design sign-off on completion
- [x] QA sign-off on completion
- [x] Product sign-off on completion
```

**Comment by kittykat** [comment]
Must be tested with test accounts for now

**Comment by ghost** [comment]
On iOS this seems mostly okay. I have filed one issue (#1712)  but I'm not sure it directly relates to this user story. I don't think that issue should block QA sign off for public testing on iOS.

However [Kat's comment ](https://github.com/vector-im/element-meta/issues/1055#issuecomment-1495724366) last month about only using test accounts should block. In my opinion a potential for data loss is not acceptable, even for public testers who accept a certain amount of risk.

I still need to test this on Android.

**Comment by Johennes** [comment]
> However https://github.com/vector-im/element-meta/issues/1055#issuecomment-1495724366last month about only using test accounts should block. In my opinion a potential for data loss is not acceptable, even for public testers who accept a certain amount of risk.

I believe this should be obsolete by now. It only affected Android.

**Comment by Johennes** [comment]
Closing this since we've reviewed it in the weekly on Tuesday and shipped it in the iOS TestFlight today. Any further issues can be tracked under the epic which I'm keeping open until QA has processed the whole scope.

**Comment by ghost** [comment]
Retested this on Element X iOS 1.1.8 (270) and Element X Android 0.1.0-nightly (July 1, 2023). It seems to be working in line with the acceptance criteria. Removing this from my backlog, but please tag me if you need something tested.
