### ISSUE TITLE
[Story] React on message

### ISSUE THREAD

**Issue by VolkerJunginger** [vector-im/element-meta#1067]
As a user that has received or send a message I want to react via emoji on that message so I can send a lightweight reaction.

- The user can ad multiple emoji to a message in the timeline
- The emoji are visible next to the message in a row
- If there are too many emoji introduce a 2nd (3rd...) row
- The emoji are shown to all room members
- The user can pick out of a standard set of emoji
- Show a set of six favourite emoji first

## Scope

```[tasklist]
### Engineering
- [ ] https://github.com/matrix-org/matrix-rust-sdk/issues/1792
- [ ] https://github.com/vector-im/element-x-android/issues/288
- [ ] https://github.com/vector-im/element-x-ios/issues/782
- [ ] https://github.com/vector-im/element-x-ios/issues/783
- [ ] https://github.com/vector-im/element-x-android/issues/342
```

## Out of scope

- Nothing at the moment

### Android
- [x] Design sign-off on completion
- [x] QA sign-off on completion
- [x] Product sign-off on completion

### iOS
- [x] Design sign-off on completion
- [x] QA sign-off on completion
- [x] Product sign-off on completion

**Comment by amshakal** [comment]
Figma links are there in the engineering tasks already
