### ISSUE TITLE
[Story] Show notification settings when joining a new room

### ISSUE THREAD

**Issue by VolkerJunginger** [vector-im/element-meta#1076]
As a user that is joining a new room I want to see options for the notification settings right away to configure the way I am notified about new messages.

- Show the notification settings for a room when joining.
- Show the current setting (default)
- Show it in way the user understands what she is getting: Instead of "Default notifications" say "You get notifications for each new message" or "You get a notification each time you're mentioned in this room"

## Scope
*These should be a list of technical tasks which take ½-1 day to complete*
```[tasklist]
### Tasklist
- [ ] Task 1
- [ ] QA signoff on completion
- [ ] Design signoff on completion
- [ ] Product signoff on completion
```

##  Stretch goals
None at this time
<or add a tasklist>

## Out of scope
-

**Comment by manuroe** [comment]
This did not happen.
