### ISSUE TITLE
[Story] Show avatars for DMs with only 2 members in the room

### ISSUE THREAD

**Issue by VolkerJunginger** [vector-im/element-meta#1079]
As a user that has a DM with another user I want to see their picture in the room list so that I can recognise our DM faster
- DMs with only (max) two users are our 1:1 chats. Here I want to see the other users picture in the room list as an avatar.
- DM´s with more than two users should be treated like any other room.

## Scope
*These should be a list of technical tasks which take ½-1 day to complete*
```[tasklist]
### Tasklist
- [ ] https://github.com/vector-im/element-x-android/issues/739
- [ ] https://github.com/vector-im/element-x-ios/issues/917
- [x] QA signoff on completion
- [x] Design signoff on completion
- [x] Product signoff on completion
```

##  Stretch goals
None at this time
<or add a tasklist>

## Out of scope
-

**Comment by t3chguy** [comment]
> Show avatars for DMs with ≥2 members in the roomlist

Which avatar should be picked in the case of >2 members?

**Comment by amshakal** [comment]
Volker, are we thinking of showing some other kind of avatar? I know that there are strong opinions within the company to not differentiate between room and dm avatars. @nadonomy

**Comment by VolkerJunginger** [comment]
For DMs with  ≥2 members I want to see the other users picture. For all other cases treat this like a generic room.

**Comment by amshakal** [comment]
Ah, okay. Will that be possible? Given that DMs with >2 people is a room without a name? Also, will check in with Nad to figure out the legacy thinking behind this and comment back here.

**Comment by t3chguy** [comment]
> For DMs with ≥2 members I want to see the other users picture. For all other cases treat this like a generic room.

Could you show an example of how you would like to see the pictures of e.g. 4 other users (in a 5>=2 user DM)? Would it be a circular avatar with a quarter of each user's picture spliced into it?

**Comment by VolkerJunginger** [comment]
Sorry all - I think I used the ≥ in the wrong way.

So to be clear.
- DMs with only (max) two users are our 1:1 chats. Here I want to see the other users picture in the roomlist as an avatar.
- DM´s with more than two users should be treated like any other room.

**Comment by manuroe** [comment]
@kegsay is it something we can implement in the SS proxy?

**Comment by t3chguy** [comment]
> DM´s with more than two users should be treated like any other room.

So a 1:1 with another person but which also contains a bot, and is listed in `m.direct` won't be a DM? I think the spec needs updating as `m.direct` doesn't discriminate based on how many members a room has. Canonical DMs also allows >2 user DMs

**Comment by pmaier1** [comment]
> @kegsay is it something we can implement in the SS proxy?

https://github.com/matrix-org/sliding-sync/issues/166

**Comment by manuroe** [comment]
The today nightly of EAX got the last version of the SDK. Avatars are now shown.
