### ISSUE TITLE
Ignoring a user

### ISSUE THREAD

**Issue by Velin92** [vector-im/element-meta#1083]
As a user that is annoyed be an other user I want to be able to stop receiving any sign of existence of this user to make messaging fun again.

- Blocking a user in the conntext of reporting a message
- Blocking from the user-profile
- Blocking from an invite

See designs in Figma
https://www.figma.com/file/0MMNu7cTOzLOlWb7ctTkv3/Element-X-(new)?node-id=546%3A75333&t=1rTgLu3kcD3xpYfO-4

**Comment by erkinalp** [comment]
The ignore UX should make it difficult to [ignore yourself](https://github.com/vector-im/element-meta/issues/410).

**Comment by kittykat** [comment]
This was fixed as part of the work on the relevant epic
