### ISSUE TITLE
[Story] Receive push notification for new message

### ISSUE THREAD

**Issue by kittykat** [vector-im/element-meta#1093]
As a user I that is a member in a room want to get a push notification for each new message in that room.
I want to know who send what kind of content in which room at what  time.
- Show room avatar
- Show room / user-name
- Show content

## Scope
*These should be a list of technical tasks which take ½-1 day to complete*

```[tasklist]
### Android
- [ ] https://github.com/vector-im/element-x-android/issues/186
- [x] Resolve user account
- [x] Manage notifications cache
- [x] Minimal notification actions to clean the cache (dismissRoom, dismissSummary)
```

```[tasklist]
### iOS
- [ ] https://github.com/vector-im/element-x-ios/issues/671
- [ ] https://github.com/vector-im/element-x-ios/issues/759
- [ ] https://github.com/vector-im/element-x-ios/issues/802
- [ ] https://github.com/vector-im/element-x-ios/issues/776
- [ ] https://github.com/vector-im/element-x-ios/issues/813
- [ ] https://github.com/vector-im/element-x-ios/issues/855
- [x] Resolve user account
```

```[tasklist]
### Rust
- [ ] https://github.com/matrix-org/matrix-rust-sdk/pull/1608
- [ ] https://github.com/matrix-org/matrix-rust-sdk/pull/1458
- [ ] https://github.com/matrix-org/matrix-rust-sdk/issues/1628
- [ ] https://github.com/matrix-org/matrix-rust-sdk/issues/1795
```

```[tasklist]
### Android after SDK
- [x] Display the notification: avatar image, room name, sender name, content
- [x] Open the timeline on the notified message
```

```[tasklist]
### iOS after SDK
- [x] Check no more RAM issue when running the SDK
- [x] Display room name, sender name, content
- [x] Display room avatar for non dm rooms
- [x] Open the timeline on the notified message
```

- [x] QA signoff
- [x] Producs signoff
- [x] Design signoff

##  Stretch goals
None at this time
<or add a tasklist>

## Out of scope
- UnifyPush
- FDroid
- Troubleshoot screen (like on current EA)
- Timeline around an event id (`/context` + backward and forward pagination)
- Full notification timeline cache: keep cache as long as the notification is not read

**Comment by kittykat** [comment]
@amshakal:
> Should we consider different notification rules for different types of rooms at this point, push and inside the app? 
> 
> Different types of notification settings per room:
> - All messages
> - Mentions and Keywords
> - Mute
> 
> Different types of rooms:
> - Audio rooms
> - Video rooms
> - Invites
> 
> Different types of messages:
> - Polls
> - Edited messages
> - Deleted messages
> - Reactions
> - Replies to your messages
> - Room activity/upgrades
> - Membership changes etc

**Comment by manuroe** [comment]
All done 🥳
