### ISSUE TITLE
[Story] Receive push notifications for room invites

### ISSUE THREAD

**Issue by kittykat** [vector-im/element-meta#1094]
As a user that has been invited to a room I want to get a push-notification for the room-invitation so I am aware that I join a room.
- I want to know who invited me to what room.
- When tapping on the push I want to open the "Join room" screen and decide to join or decline the room join.

### Dependencies
- https://github.com/matrix-org/matrix-rust-sdk/issues/1928

## Scope
```[tasklist]
### Android
- [x] Render the invite
- [x] Navigate to the "Invites" screen
```

- [x]  QA signoff on completion
- [x]  Design signoff on completion
- [x]  Product signoff on completion

```[tasklist]
### iOS
- [x] Render the invite
- [x] Navigate to the "Invites" screen
```

- [x]  QA signoff on completion
- [x]  Design signoff on completion
- [x]  Product signoff on completion

##  Stretch goals
None at this time
<or add a tasklist>

## Out of scope
- TBD
-

**Comment by manuroe** [comment]
@VolkerJunginger should we consider reject and accept buttons in the notification itself?

**Comment by VolkerJunginger** [comment]
No, we will open the room. This should also drive interaction as for DMs there will be a message waiting that the user might miss if she joins from the push.

**Comment by manuroe** [comment]
It makes sense. I like the reasoning behind 👍 .

**Comment by Velin92** [comment]
Do we have designs for how the content of these notifications should look like, or of their actions?

**Comment by Velin92** [comment]
Implemented invitation notifications, however they come as encrypted most of the times, so for them to work properly we need to have a fully working two sync loop implementation.

**Comment by jmartinesp** [comment]
I forgot to update this, but invite notifications also work fine now on Android.
