### ISSUE TITLE
Enhance user-informed-ness about data collection

### ISSUE THREAD

**Issue by ShadowJonathan** [vector-im/element-meta#110]
![image](https://user-images.githubusercontent.com/22740616/149570577-65d11b0f-a3f7-4e7e-8180-e82682424cbb.png)

Element Web recently revamped its "learn more" panel (under Security & Privacy -> Privacy -> Analytics) to the above, it's very good, however, compared to the old panel, it loses all of the "positive" acknowledgements of data collection ("We will connect X"), while introducing "negative" ones ("We will not collect Y")

<details>
<summary>Old Panel</summary>

![image](https://user-images.githubusercontent.com/22740616/149570904-d2634c11-3689-4a15-9bf5-f9f6f19c6091.png)

</details>

I think that this is not adequate enough, as only people who are familiar with data collection in general will be able to draw conclusions from these negative acknowlegements.

Thus, I'm asking for more detailed *positive* acknowledgements as to what data is collected in above panel. Suggestions for this include; 
1. grabbing those definitions from [matrix-analytics-events](https://github.com/matrix-org/matrix-analytics-events), and displaying these in this panel in a fashion (such as under a expansion dropdown)
2. prefixing "negative" acknowledgements with red/cross icons.
3. describing intentions, "We will use data about the number of rooms you've joined to prioritise room performance optimisation, and provide the best average experience".
4. providing a visual readout of the current live data, so that the user can double-check for themselves what data the local client is actually sending out.
5. in patch notes, include new types of data to be collected through analytics
6. provide toggles on a data-type basis for users to opt-in/out of specific analytics data.

Above is in decreasing order of suggested urgency, the main thing i want to get across is that the user is informed at any time as to what data is being collected from them, that they're able to keep up-to-date with this information, and that they have complete agency over this fact, plus their participation.

**Comment by novocaine** [comment]
Yep this is coming, but can you file this as a T-enhancement in Element Web please?

**Comment by ShadowJonathan** [comment]
@kittykat recommended me to file it here, but I'll do so
