### ISSUE TITLE
[Story] Show visual feedback if media is loading

### ISSUE THREAD

**Issue by VolkerJunginger** [vector-im/element-meta#1100]
As a receiver I want to get visual feedback when media is loading so I can wait patiently until I access that media.
- loading images
- loading video
- loading files

## Scope
*These should be a list of technical tasks which take ½-1 day to complete*
```[tasklist]
### Android
- [x] Implementation
- [x] QA signoff on completion
- [x] Design signoff on completion
- [x] Product signoff on completion
```

```[tasklist]
### iOS
- [x] Implementation
- [x] QA signoff on completion
- [x] Design signoff on completion
- [x] Product signoff on completion
```

##  Stretch goals
None at this time
<or add a tasklist>

## Out of scope
-

**Comment by amshakal** [comment]
Loading (iOS): [Photo](https://www.figma.com/file/0MMNu7cTOzLOlWb7ctTkv3/Element-X-(new)?node-id=2409%3A110802&t=9qgQvDswgzKRZpna-1), [Video](https://www.figma.com/file/0MMNu7cTOzLOlWb7ctTkv3/Element-X-(new)?node-id=2299%3A119533&t=9qgQvDswgzKRZpna-1), [File](https://www.figma.com/file/0MMNu7cTOzLOlWb7ctTkv3/Element-X-(new)?node-id=2299%3A120100&t=9qgQvDswgzKRZpna-1)

Loading (Android): [Photo](https://www.figma.com/file/0MMNu7cTOzLOlWb7ctTkv3/Element-X-(new)?node-id=2368%3A118873&t=9qgQvDswgzKRZpna-1), [Video](https://www.figma.com/file/0MMNu7cTOzLOlWb7ctTkv3/Element-X-(new)?node-id=2371%3A116611&t=9qgQvDswgzKRZpna-1), [File](https://www.figma.com/file/0MMNu7cTOzLOlWb7ctTkv3/Element-X-(new)?node-id=2371%3A117177&t=9qgQvDswgzKRZpna-1)
