### ISSUE TITLE
Show room previews on room search results

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-meta#1102]
Room previews are missing when you filter the room list, unless the room happens already to have been in the 'VisibleRooms' SS window. Instead, we should call /messages (or a new bulk /messages API) to grab the room preview and precache the room history for the rooms show in the roomlist search results.

**Comment by manuroe** [comment]
We want to manage it in the SDK: https://github.com/matrix-org/matrix-rust-sdk/issues/1659

**Comment by Hywan** [comment]
Closed by https://github.com/matrix-org/matrix-rust-sdk/issues/1911.
