### ISSUE TITLE
[Story] Room detail page

### ISSUE THREAD

**Issue by VolkerJunginger** [vector-im/element-meta#1103]
As a user I want to be able to access a room-detail-page from the room header so that I can get some info about the room.

Show the following details:

Feature | Room- Details
-- | --
Show Avatar | yes
Show Name | yes
Matrix-ID | yes
Room Description / Topic | yes
→ Encryption: Info + Verify user | Info only
→ Room-Members list | yes
Leave Room | yes

## Scope
*These should be a list of technical tasks which take ½-1 day to complete*

```[tasklist]
### Android
- [x] Implementation
- [ ] https://github.com/vector-im/element-x-android/issues/799
```

- [x] QA signoff on completion
- [x] Design signoff on completion
- [x] Product signoff on completion

```[tasklist]
### iOS
- [x] Implementation
```

- [x] QA signoff on completion
- [x] Design signoff on completion
- [x] Product signoff on completion

##  Stretch goals
None at this time
<or add a tasklist>

## Out of scope
-

**Comment by amshakal** [comment]
Design will first work on features being implemented right now and then focus on the rest of the features as additional info might be needed for each and every one of them. eg. scope of audio/video call has not been defined yet, we don't know what encryption and verify user flow will look like based on what crypto team plans on doing etc.

Additionally slightly worried to have search here. Timeline might be a better place to search for messages.

**Comment by amshakal** [comment]
Are we sure we can and want to do links as well?

**Comment by amshakal** [comment]
Link to figma: This is based on future requirements/features we want to build.

iOS: https://www.figma.com/file/0MMNu7cTOzLOlWb7ctTkv3/Element-X-(new)?node-id=1466%3A81929&t=ZXsZIHrbrFYWRErj-1
Android:https://www.figma.com/file/0MMNu7cTOzLOlWb7ctTkv3/Element-X-(new)?node-id=1649%3A85791&t=ZXsZIHrbrFYWRErj-1

**Comment by manuroe** [comment]
@kittykat: iOS is ready for QA

**Comment by jmartinesp** [comment]
@kittykat Android is ready for QA too. You can test this in the latest nightly.

**Comment by ghost** [comment]
Testing this on iOS 16.3.1 with an iPhone 12 mini on Element X 1.1.0 (218), this seems to be mostly okay.

I encountered an issue with very large rooms like Matrix HQ though so I filed it [here](https://github.com/vector-im/element-x-ios/issues/933).

**Comment by kittykat** [comment]
@jmartinesp is it correct that links in the topic are not clickable and cannot be copied? Apart from that, passed on Android

**Comment by jmartinesp** [comment]
> @jmartinesp is it correct that links in the topic are not clickable and cannot be copied? Apart from that, passed on Android

I didn't see it in the requirements, but it would definitely be helpful. Maybe we could create a new issue for that?

**Comment by kittykat** [comment]
Filed https://github.com/vector-im/element-x-android/issues/612 and https://github.com/vector-im/element-x-android/issues/613 for Android about room topics.

**Comment by ghost** [comment]
I think we can consider this _conditionally_ signed off by QA. Once the two issues reported by Kat are resolved I'd consider this good to go for public testing.

**Comment by kittykat** [comment]
We can fix links as follow on work
