### ISSUE TITLE
[Story] User profile

### ISSUE THREAD

**Issue by VolkerJunginger** [vector-im/element-meta#1105]
As a user I want to be able to access a user-detail-page when tapping on a user avatar so that I can get some info about the user.

Implement the following features:

Feature | User Profile
-- | -- 
Show Avatar | userpic
Show Name | username
Matrix-ID | yes
Block User | yes

## Scope
*These should be a list of technical tasks which take ½-1 day to complete*
```[tasklist]
### Android
- [x] Implementation
```
- [x] QA signoff on completion
- [x] Design signoff on completion
- [x] Product signoff on completion

```[tasklist]
### iOS
- [x] Implementation
```
- [x] QA signoff on completion
- [x] Design signoff on completion
- [x] Product signoff on completion

## Out of scope
- Final design implementation with Start a chat, etc.

**Comment by amshakal** [comment]
Design will first work on features being implemented right now and then focus on the rest of the features as additional info might be needed for each and every one of them. eg. scope of audio/video call has not been defined yet, we don't know what encryption and verify user flow will look like based on what crypto team plans on doing etc.

**Comment by amshakal** [comment]
Additionally should we show if the user has been favourited here?

**Comment by Velin92** [comment]
This view has been added, so far it just includes the ignore function, but can now include more functionalities.
@VolkerJunginger let me know if this should be part of the Plat or the Feat team, (currently I am working on https://github.com/vector-im/element-meta/issues/1167)

**Comment by amshakal** [comment]
Link to figma based on requirements and future features:

iOS: https://www.figma.com/file/0MMNu7cTOzLOlWb7ctTkv3/Element-X-(new)?node-id=1574%3A87427&t=ZXsZIHrbrFYWRErj-1
Android: https://www.figma.com/file/0MMNu7cTOzLOlWb7ctTkv3/Element-X-(new)?node-id=1777%3A94524&t=ZXsZIHrbrFYWRErj-1

**Comment by manuroe** [comment]
@kittykat: iOS is ready for QA

**Comment by jmartinesp** [comment]
@amshakal  @kittykat @VolkerJunginger this is ready to be tested on Android, it should be included in the latest nightly.

**Comment by ghost** [comment]
Testing this on iOS using an iPhone 12 mini running Element X 1.1.0 (200) I can't seem to tap on user avatars. Tapping them does nothing. Is this functionality implemented fully? Is there some other way to access the user details view?

**Comment by Velin92** [comment]
> Testing this on iOS using an iPhone 12 mini running Element X 1.1.0 (200) I can't seem to tap on user avatars. Tapping them does nothing. Is this functionality implemented fully? Is there some other way to access the user details view?

@ashughes1 

Hi! Does this behaviour not work for you in group rooms?

https://github.com/vector-im/element-meta/assets/34335419/2e1433c1-09f6-41fc-829a-70a8622eeac9

**Comment by ghost** [comment]
@Velin92 Sorry for the delay in replying. I do get the User Details screen after tapping People in Room Details and then tapping the user from there.  Although he encryption info seems to be missing (part of acceptance criteria in the initial comment above). The user details view is not accessible by tapping the avatar in a room timeline though, as it does on Element legacy.

**Comment by ghost** [comment]
After discussion with @callumu and @amshakal it was agreed to file an issue for the tapping on avatars/usernames in the timeline. See #1701.

**Comment by ghost** [comment]
Aside from #1701 this is working well enough on iOS for QA sign-off. I still need to test Android.

**Comment by kittykat** [comment]
@jmartinesp Where should the encryption info be shown and how? Is it correct that the "send message" button doesn't work?

**Comment by jmartinesp** [comment]
> @jmartinesp Where should the encryption info be shown and how? Is it correct that the "send message" button doesn't work?

The encryption info should only appear in the 'room details' screen, so the one that's brought up when you tap on a chat's title or when long pressing a room and selecting 'room settings' in the room list. If the room is encrypted there will be a section with some info, otherwise nothing will appear.

As for the send message button... we originally built this before we had the logic for creating new rooms, and it seems like we never got to actually handle that. We should probably create an issue for that.

**Comment by kittykat** [comment]
@jmartinesp given that this issue is about the user profile, could it mean whether the user has an unverified session or some other problem like that? we don't have plans to add that in the immediate future though

CC @VolkerJunginger in case you can help verify the ACs

**Comment by kittykat** [comment]
Blocking issue on Android: https://github.com/vector-im/element-x-android/issues/616

**Comment by manuroe** [comment]
As the https://github.com/vector-im/element-x-android/issues/616 is fixed and checked automatically by the tests. I am ticking the QA checkbox for android.

**Comment by ghost** [comment]
I retested this on Element X iOS 1.1.8 (271) and Element X Android 0.1.0-nightly (July 1, 2023). This is working in line with the acceptance criteria with _Send Message_ now removed. Marking this done for QA for now. Please tag us again if there's retesting to be done.

**Comment by kittykat** [comment]
All done and reviewed :+1:
