### ISSUE TITLE
[Task] Adapt new Android designs

### ISSUE THREAD

**Issue by VolkerJunginger** [vector-im/element-meta#1107]
## Scope
*These should be a list of technical tasks which take ½-1 day to complete*
```[tasklist]
### Tasklist
- [ ] https://github.com/vector-im/element-x-android/issues/354
- [x] QA signoff on completion
- [x] Design signoff on completion
- [x] Product signoff on completion
```

##  Stretch goals
None at this time
<or add a tasklist>

## Out of scope
-

**Comment by amshakal** [comment]
Link to figma:
https://www.figma.com/file/0MMNu7cTOzLOlWb7ctTkv3/Element-X-(new)?node-id=823%3A76439&t=cPNJwcNqVppMY9e6-1

**Comment by jmartinesp** [comment]
@amshakal , @kittykat and @VolkerJunginger could you test [this apk](https://github.com/vector-im/element-x-android/pull/356#issuecomment-1521545023)?

**Comment by ghost** [comment]
I apologize for taking so long to get to this issue and assume the QA request is still relevant. I've been testing various user stories on Element X Android 0.1.0-nightly (July 1, 2023) and touching the Search and menu UI throughout. I've not encountered any major issues related to the changes here. Considering this done from a QA perspective. Please tag me if you'd like something more tested.
