### ISSUE TITLE
[Story] Show most recent activity in room cell on room-list

### ISSUE THREAD

**Issue by VolkerJunginger** [vector-im/element-meta#1109]
As a user I want to see the most recent room activity in the room list so that I can see if a room has new interesting content to offer (and understand the sorting of the room-list better).

## Scope
*These should be a list of technical tasks which take ½-1 day to complete*
```[tasklist]
### Tasklist
- [x] Get latest events/messages for each room
- [x] Filter out events that aren't relevant (avatar or name changes, i.e.)
- [ ] https://github.com/vector-im/element-x-android/issues/217
```

- [x] QA signoff on completion
- [x] Design signoff on completion
- [x] Product signoff on completion

##  Stretch goals
None at this time
<or add a tasklist>

## Out of scope
-

**Comment by jmartinesp** [comment]
@kittykat , @amshakal & @VolkerJunginger can you review the apk at https://github.com/vector-im/element-x-android/pull/220#issuecomment-1471846108?

**Comment by ghost** [comment]
#### QA Sign-off Status:
:green_circle: Element X iOS 1.1.8 (271)
:green_circle: Element X Android 0.1.0-nightly (July 5, 2023)

#### Details
I have tested this and find it meets the acceptance criteria above without any major issues found. I think this is good enough to go to public testing.
