### ISSUE TITLE
[Story] Show rooms with unread messages in the app icon

### ISSUE THREAD

**Issue by VolkerJunginger** [vector-im/element-meta#1146]
As a user that has unread messages I want to have an indicator  on the app-icon so that I know there is some todos.

- Show that there are rooms w. unread messages in the app icon
- Reset the app icon when visiting the app.

## Scope
*These should be a list of technical tasks which take ½-1 day to complete*
```[tasklist]
### Tasklist
- [x] QA signoff on completion
- [x] Design signoff on completion
- [x] Product signoff on completion
```

##  Stretch goals
None at this time
<or add a tasklist>

## Out of scope
-

**Comment by manuroe** [comment]
The behavior will be different on iOS and Android.
On iOS, this is a count badge. So, we need to put a count (unread rooms).
On Android, it depends on the OS version. On the latest OSes, the behavior could match which what we want here. There is an app icon indicator when there is a notification pending for the app.
