### ISSUE TITLE
[Story] Remove reaction from a message

### ISSUE THREAD

**Issue by VolkerJunginger** [vector-im/element-meta#1163]
As a user that reacted on a message I wan to be able to remove the reaction to correct my decision.
- If a user has multiple reactions each reaction should be removed separately

Questions:
How do we handle the preview in the room-list?  If someone reacted on my message I should see this a s preview in the room list.

Suggestion: 
- Remove the preview
- Show previous preview

## Scope

```[tasklist]
### Engineering
- [ ] https://github.com/vector-im/element-x-android/pull/707
- [ ] https://github.com/vector-im/element-x-ios/pull/1166
```

```[tasklist]
### Issues
- [ ] https://github.com/vector-im/element-x-ios/issues/1372
```

## Out of scope

- Nothing at the moment

### Android
- [x] Design sign-off on completion
- [x] QA sign-off on completion
- [x] Product sign-off on completion

### iOS
- [x] Design sign-off on completion
- [x] QA sign-off on completion
- [x] Product sign-off on completion

**Comment by amshakal** [comment]
Callum and I agree with your suggestion. 

If a reaction has been removed, we should revert back to the previous item in message preview.
