### ISSUE TITLE
it could be nice to list the users who have read a given message

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-meta#1224]
as an option on the message, much as WA and FB Msgr do, by enumerating the RRs which have passed that point.  N.B. this is *not* actually tracking read status per-msg

**Comment by daniellekirkwood** [comment]
<img width="132" alt="Screenshot 2023-03-31 at 10 26 09" src="https://user-images.githubusercontent.com/89144281/229081807-068fc91c-9c39-4ac8-8bc2-0ca14ed08e8d.png">

<img width="248" alt="Screenshot 2023-03-31 at 10 26 22" src="https://user-images.githubusercontent.com/89144281/229081861-1919f3ba-4095-46b6-a979-b5150e5c3b76.png">


Here's what we have in product today and I believe it satisfies the request in this issue. (It is also available on mobile). 

I'll close this issue but if I've mis-read the request here please let me know

**Comment by t3chguy** [comment]
@daniellekirkwood the issue with that is that it doesn't include people who have read a later message

Imagine a room with these messages

A
B
C

If PersonX has read up to C, clicking on read receipts for B will not show them
