### ISSUE TITLE
Mobile FTUE: Choose a server (Meta)

### ISSUE THREAD

**Issue by daniellekirkwood** [vector-im/element-meta#126]
- [x] https://github.com/vector-im/element-android/issues/2396	
- [x] https://github.com/vector-im/element-ios/issues/5161

When the user has chosen to choose their server, we show this screen:

| Sign up | Sign in |
|----|----|
| <img width="214" alt="Screenshot 2022-02-16 at 15 05 06" src="https://user-images.githubusercontent.com/89144281/154293162-f70a3ec2-46a6-449c-9c6f-4ee7b87551db.png"> | <img width="212" alt="Screenshot 2022-02-16 at 15 05 14" src="https://user-images.githubusercontent.com/89144281/154293199-61f49e94-02c5-43ad-8a4a-5c0f66829042.png"> |

 In the future we may want to add other options (see comments). 
 We also may choose to replace the "Want to host you own server" screen depending on the context of the user...

**Comment by daniellekirkwood** [comment]
Things we may want in the future: 
- [ ] QR code
- [ ] Magic link
- [ ] NFC, location

**Comment by daniellekirkwood** [comment]
Can we pre-fill this list with other options?

**Comment by daniellekirkwood** [comment]
https://github.com/vector-im/element-android/issues/2396	
https://github.com/vector-im/element-ios/issues/5161

**Comment by HarHarLinks** [comment]
I would like if this would indicate that EMS isn't the only way to host your own. What I mean isn't a list of other hosting providers, but matrix.org docs about it or the list of servers (https://matrix.org/docs/projects/try-matrix-now filtered for servers).

**Comment by daniellekirkwood** [comment]
@ouchadam "When pressing EDIT within the sign up details page, should the server url contain the https:// prefix?"

<img width="671" alt="Screenshot 2022-04-28 at 11 30 38" src="https://user-images.githubusercontent.com/89144281/165822304-45c1e4fb-7310-49ba-b273-16fb3a6cf09c.png">

We decided that we would remove the https:// as it's industry standard and saves space. 

👀 @pixlwave
