### ISSUE TITLE
New mention UI eats the text of the link

### ISSUE THREAD

**Issue by MightyCreak** [vector-im/element-meta#1261]
### Description

Can't make a link to a room with a text.

### Steps to reproduce

If you write something like that:

```Meet me [here](https://riot.im/develop/#/room/#test:matrix.org)```

`here` isn't shown. Instead it's the room name that is.

Describe how what happens differs from what you expected.

<img width="270" alt="riot_issue_mention_link" src="https://user-images.githubusercontent.com/6382548/28873159-7d83c2c2-775a-11e7-85c2-6cc9c10d544c.png">

The best solution would be to show the room icon but keep the link text instead of the room name.

### Version information

Dev

- **Platform**: web

For the web app:

- **Browser**: Firefox 54
- **OS**: macOS
- **URL**: riot.im/develop

**Comment by daniellekirkwood** [comment]
We've taken a look at this feedback as we're again [working on Pills](https://github.com/vector-im/element-meta/issues/1030). The solution that we've landed at should now be live in all our public test environments (Nightly builds for example). 

I will close this issue as we've made and committed the product decisions on how to handle this use case. 

If there's more feedback once playing with the new implementation, please go ahead and open another issue. You're welcome to tag me in it also :)
