### ISSUE TITLE
Mobile FTUE: Celebration screens (meta)

### ISSUE THREAD

**Issue by daniellekirkwood** [vector-im/element-meta#131]
- [x] https://github.com/vector-im/element-android/issues/5280	
- [x] https://github.com/vector-im/element-ios/issues/5651

Our onboarding flow needs personality - we need to encourage the users to keep going and the simplest way to do that is to over consistent positive reinforcement and feedback when they complete a flow. 
We need to ensure we don't celebrate too often, and that we're not getting in the way of their task.

Identified areas of celebration are: 
- The account has been created
- The account has been personalised

| Account created | Account personalise | 
|---|---|
| <img width="180" alt="Screenshot 2022-02-16 at 15 35 06" src="https://user-images.githubusercontent.com/89144281/154299242-db74eecb-74bb-4598-b0ca-dab3b4d8d40f.png"> | <img width="170" alt="Screenshot 2022-02-16 at 15 35 14" src="https://user-images.githubusercontent.com/89144281/154299292-3664e5b4-c158-4660-a460-3b948bd6d05a.png"> |

In the case where the server does not offer any personalisation options then the confetti animation would show at the point of account creation

The confetti animation can use the same as is currently on the timeline for android

**Comment by daniellekirkwood** [comment]
<img width="416" alt="Screenshot 2022-02-16 at 16 08 35" src="https://user-images.githubusercontent.com/89144281/154306946-8bdeedd8-6afd-4701-9e5c-d30e4e7fbbf2.png">

**Comment by daniellekirkwood** [comment]
https://github.com/vector-im/element-android/issues/5280	
https://github.com/vector-im/element-ios/issues/5651

**Comment by matthijskooijman** [comment]
Apologies if this is not the right place to comment about this, but looking at the design presented here, I wonder if the "Take me home" button will be clear to users. I assume "home" refers to the home screen in the Element Mobile app, but I am afraid that new users (who have never seen the app UI) have no idea that the app has a home screen, so it will not be clear to them what this button will do. Maybe sometime more explicit like "Skip for now", or "Do this later", or "Remind me later" or so would be more helpful?

A related feature (as hinted by my proposed wordings) would be to, if the user skips personalisation, to remind them of this later (probably with "Personalize now / Remind me later / Skip personalization" buttons). This would make it easier for user to just start exploring the app, in the confidence that they can always complete the personalisation flow later (of course they can always just do this manually through the settings, but a new user probably does not know what they missed when they (accidentally?) skipped personalisation, so a reminder that allows them to go through this later (and foreshadowing that his can happen later through the button text) could be helpful. I quickly searched and could not find an existing issue for this (or maybe it is already implemented?), but maybe I did not look well enough.

A bit more off-topic, but I've been reading through the FTUE issues here, and think these are all great improvements that will be very helpful to (mostly non-technical) community I'm moderating for. So thanks for all this!

**Comment by daniellekirkwood** [comment]
> * Mobile FTUE: Celebration screens (Android) element-android#5280

Thanks for your feedback! It's a super relevant comment for the copy on this button. We'll discuss it as a team and get back to you. 

This issue particularly is the "MVP" of the FTUE flow so if you don't see your suggestions in product right away, it's likely because we've got them scheduled for the second iteration of this flow - especially the idea of allowing users to jump into personalisation later down the line (not right at the beginning if they don't want to).
