### ISSUE TITLE
Mobile FTUE: Popups and permissions (meta)

### ISSUE THREAD

**Issue by daniellekirkwood** [vector-im/element-meta#133]
- [x] https://github.com/vector-im/element-android/issues/5282	
- [x] https://github.com/vector-im/element-ios/issues/5653

There are several pop-ups that we need to present to the user during their first session in the app. 
We need to experiment with the best placement of these pop-ups to ensure minimal disruption to the flow. 

### Sign up
| Pop up | Placement (Round 1) | Learnings | 
|----|----|----|
| Notifications | Directly after the user has confirmed their email, and before they agree to the Ts&Cs. If the server does not have either of these steps the notification dialog shows before Account creation celebration screen. (This only applies on iOS) | We're a messaging app, requesting notifications access is expected and could be critical to a user's experience of Element over time. |
| PostHog analytics | Before the user hits the Home page for the first time. Ideally this is after personalisation is complete and the celebration has been shown but if personalisation is skipped then posthog would show after the account creation celebration screen. | The earlier we can ask for posthog permission the more we will learn about our flow and the impact of FTUE on D1 and R30. |
| Access to contacts | @amshakal what point do we ask for this? When sending a DM for the first time makes logical sense? | |

### Sign in
| Pop up | Placement (Round 1) | Learnings | 
|----|----|----|
| Notifications | @amshakal When the user is signing in on the device, when should we ask for notification permissions? (This only applies on iOS). Do we also want to show a screen behind the pop up to give context? | We're a messaging app, requesting notifications access is expected and could be critical to a user's experience of Element over time. |
| PostHog analytics | We'll ask this when the user has successfully signed in and while the app is loading the rooms in the background |  |
| Access to contacts | Might be the same as above @amshakal to let us know | |
| Cross-signing | When the user has completed the PostHog screen and when they land on the Home screen | |

**Comment by amshakal** [comment]
We could even add this when someone taps on the FAB, or as an empty state

**Comment by daniellekirkwood** [comment]
> We could even add this when someone taps on the FAB, or as an empty state

Sure, whatever you think is best

**Comment by amshakal** [comment]
Will explore a few options and get back!

**Comment by daniellekirkwood** [comment]
https://github.com/vector-im/element-android/issues/5282	
https://github.com/vector-im/element-ios/issues/5653

**Comment by daniellekirkwood** [comment]
@amshakal Assigning this to you as we have an open question around when we ask for access to contact info. We may choose to remove "contact" from the definition of done for this issue as the Delight and/or PS team may be handling it...

**Comment by pixlwave** [comment]
For the notifications prompt on iOS we are going to to let the prompt show itself naturally on the congratulations screen unless it doesn't work well in testing. This is due to the added complication that different homeservers can show the screens in different orders and might not even show an email screen to have the prompt follow either.
