### ISSUE TITLE
Mobile FTUE: Password recovery (meta)

### ISSUE THREAD

**Issue by daniellekirkwood** [vector-im/element-meta#135]
- \[x\] https://github.com/vector-im/element-android/issues/5284
- \[x\] https://github.com/vector-im/element-ios/issues/5655

When the user has forgotten their password, we need to ensure we can get them back on track

Figma: https://www.figma.com/file/xdV4PuI3DlzA1EiBvbrggz/Login-Flow-v2?node-id=2523%3A42803

![Screenshot 2022-02-21 at 18 43 26](https://user-images.githubusercontent.com/89144281/155011415-74608a18-3ba6-4e61-ba72-a6b50f9b32fc.png)

- \[x\] Add a "sign out of all sessions" option. Default unticked.

**Comment by daniellekirkwood** [comment]
https://github.com/vector-im/element-android/issues/5284	
https://github.com/vector-im/element-ios/issues/5655

**Comment by hughns** [comment]
@daniellekirkwood can I suggest that the "sign out all devices" option from https://github.com/matrix-org/matrix-react-sdk/pull/8259 is incorporated into these mobile designs?

**Comment by daniellekirkwood** [comment]
@hughns Happy to discuss that for sure! Is this the reset password flow when the user is signed in, or when the user is attempting to sign in?

**Comment by hughns** [comment]
@daniellekirkwood the linked issue covers both cases, but I am only suggesting incorporating a "Sign out all devices" checkbox similar to the following on the forgot password part of signing in:

![image](https://user-images.githubusercontent.com/6955675/162783227-ccebe61d-2a13-439b-8c14-af34178c9ad5.png)

**Comment by daniellekirkwood** [comment]
@amshakal & @ouchadam & @pixlwave 
Is this do-able for us? How long would this scope change set us back? WDYT?
Thanks!

**Comment by ouchadam** [comment]
very doable https://spec.matrix.org/v1.2/client-server-api/#post_matrixclientv3accountpassword would lean towards this being a small/small-medium amount of work

it seems like something that could be done in a second iteration though (we'll probably want the extra behaviour in the settings -> change password flow as well)

**Comment by hughns** [comment]
Re: scope. Please note that there is need to vary behaviour based on which version of the matrix spec the homeserver supports. The logic is captured in https://github.com/matrix-org/matrix-react-sdk/pull/8259

**Comment by ara4n** [comment]
Real-life microcosm of why [Hugh's refinement](https://github.com/vector-im/element-meta/issues/135#issuecomment-1095249727) is important:

![image](https://user-images.githubusercontent.com/1294269/166912605-373222ec-9227-4e30-a706-7894f8e3d8c4.png)

**Comment by daniellekirkwood** [comment]
@hughns We discussed this yesterday as a team and have added "sign out of all sessions" to the definition of done for this issue. I'm sure @ouchadam and @pixlwave will reach out with any questions if we have them :)

**Comment by jdauphant** [comment]
Can we update it for the web version ? (having the same new workflow as mobile)

cc @gaelledel @giomfo
