### ISSUE TITLE
Mails containing "element.io" dropped by spamfilter

### ISSUE THREAD

**Issue by Stapper** [vector-im/element-meta#1351]
The URI element.io is being blocklisted on https://raptor.pccc.com/raptor.cgim?template=RBL

Emails mentioning element.io get dropped by this spamfilter. I already contacted pccc.com but as I do not work for the company, I can't request a delisting.

**Comment by Arkaniad** [comment]
Thanks for reaching out, @Stapper! - I've filed a de-listing request just a minute or two ago and a request for clarification if possible to adjust our outbound sending filters. Will update here when I hear back from Raptor.

**Comment by Arkaniad** [comment]
Hi @Stapper - I've gotten us de-listed with the Raptor filter (email confirmation and a manual check just now to verify) and we have a good inkling of why it happened in the first place and it will be remedied. I'm going to close this issue, please feel free to re-open if this comes up again :)
