### ISSUE TITLE
Expose a setting to make a room read-only.

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-meta#1385]
Currently you have to do this:

> there isn't a nice UI in Element to do this currently, but if you type `/devtools` in element web, you can Explore Room State, go find the `m.room.power_levels` event, and change the `events_default` threshold from 0 to (say) 50

Whereas we should expose this manoeuvre with some nice UI, as it's not that unusual a move.

It could also be nice to expose UI for putting a tombstone on a room to EOL it in favour of another room.

**Comment by daniellekirkwood** [comment]
<img width="637" alt="Screenshot 2023-04-05 at 12 08 59" src="https://user-images.githubusercontent.com/89144281/230063484-c598380b-2b57-4034-b16b-062e9a1ee2c7.png">

You can also control reactions

**Comment by daniellekirkwood** [comment]
I think we can close this as completed as the request is complete. 

If we want to discuss more the 'tombstoning' comment, let's open a new issue for that
