### ISSUE TITLE
Release artefacts for IA1.5 Beta (new search experience)

### ISSUE THREAD

**Issue by kittykat** [vector-im/element-meta#139]
- Target RC date: 8 Feb
- Target release date: 14 Feb
- [x] Tweet (Caitlin)
- [x] Toast with a delay to tell users about the new feature (Michael)
- [x] [Splash image and text needed](https://github.com/vector-im/element-web/issues/20886) - Kat and Nique to pair, get review from team. Example from Spaces:
![image1](https://user-images.githubusercontent.com/51663/151383663-8cbbe041-fec3-4432-b71c-af2e23b87b35.png)

**Comment by kittykat** [comment]
@niquewoodhouse @t3chguy Any objection to calling it the "new search experience" and leave it otherwise unnamed? This was the conclusion from marketing too

**Comment by niquewoodhouse** [comment]
### Labs ad

<img width="1440" alt="ad@2x" src="https://user-images.githubusercontent.com/1587166/152379824-eeaa1df2-2d12-4c54-aaeb-0d80a61fba7c.png">

**Copy**
- A new quick way to search spaces and rooms you’re in.  This feature is a work in progress, so all feedback is very welcome.
- Leave beta: Just return to this page or tap on the beta badge when you search.
- Feedback: Search and click on feedback.

**Ad images**

![ele-web-search-ad-01](https://user-images.githubusercontent.com/1587166/152389504-f5565211-8d30-45ed-b25b-4fc15df7112b.gif)
![ele-web-search-ad-02](https://user-images.githubusercontent.com/1587166/152389519-759a083e-4ba3-4c5a-a36f-974efb7a54f6.gif)


If gif in practice makes it hard to focus on page content, a still should be fine:
<img width="600" alt="new-search-ad01@2x" src="https://user-images.githubusercontent.com/1587166/152389655-a81993b1-24d5-46bf-b2e9-f2924ff96aca.png">
