### ISSUE TITLE
Encryption is killing me; please make it optional

### ISSUE THREAD

**Issue by h-2** [vector-im/element-meta#1403]
### Steps to reproduce

![image](https://user-images.githubusercontent.com/2996863/230646430-c52deaa2-f6dd-4a4c-9624-1d6a4ab0ab09.png)

We used to use Gitter for project discussions. Now this changed to Matrix/Element. I am big fan of open standards in general, but whatever Element is doing with encryption is making my life super difficult.

For exactly one user, it always setups encryption, and whenever I start a new session (my browser deletes cookies automatically), all the history cannot be decrypted, and I cannot chat anymore.
If I click "reset", it wants to "Set up secure backup", which I don't want, because I don't need it. The benefit of using gitter for project communication is 0-overhead and working with my github-account. I don't want extra passwords, keyfiles or any of that.
Anyways, I press "Cancel" which brings me to a dialog called "Are you sure":
![image](https://user-images.githubusercontent.com/2996863/230647062-b78e7657-aceb-4644-8673-0fb8cf215baf.png)
"Cancel" and "Go back" have exactly the same outcome: nothing happens.

The only way to resolve the situation is to delete the entire chat and start a new one. But then it starts encrypting again 🤯 

I would like to please have an option to not use any encryption. Thank you

#### What did you expect?

I never opted into encryption.

#### What happened instead?

I got forced into encryption which doesn't work. For one user but not for others. I don't know why.

### Operating system

Multiple

### Browser information

Multiple

### URL for webapp

gitter.im

### Will you send logs?

Yes

**Comment by h-2** [comment]
Any news on this? It's now happening for more people, making this quite unusable for the intended purpose.
If gitter now effectively requires extra accounts / passwords / keyfiles, we might as well switch to a different service altogether.

I understand that people want encryption for their private communication, and I support all efforts to make that happen. But **gitter is not private communication**, it's technical project communication. It needs to integrate with github (or gitlab or whatever), and not much else.

Maybe Matrix is just not the right tool for that?

**Comment by t3chguy** [comment]
Encryption is optional, create an unencrypted room and invite anyone you wish to it. As for whether DMs are encrypted or not is up to your server, `gitter.im` goes with the default and encrypts DM

**Comment by richvdh** [comment]
Not really sure what this issue is asking for. As @t3chguy has said, encryption *is* optional. We do not intend to disable encryption by default in DMs.
