### ISSUE TITLE
Space : If I make any space room favourites or Low priority it shows in my home

### ISSUE THREAD

**Issue by AnisTaluqdar** [vector-im/element-meta#141]
**Is your feature request related to a problem? Please describe.**

I created a personal space for organize my room. In space if I make any room favorites or low priority, that room also show in my home.

**Describe the solution you'd like**

It should not show in my home. It only should be in space and be favorites or low priority there not in home. 

**Describe alternatives you've considered**

**Additional context**

**Comment by daniellekirkwood** [comment]
Hi there! Thanks for your feedback. 

Please note, you can toggle "Home" to show All Rooms, or just rooms that are not in a Space. If you set this toggle to "off" the Rooms that live in Favourites and Low Priority will only show in the Space they are a part of, as you requested. 

<img width="248" alt="Screenshot 2022-03-07 at 10 15 43" src="https://user-images.githubusercontent.com/89144281/157012220-aacd5bc7-47da-491d-85f8-c1ecf617cd98.png">

Right click the Home space to see this view. 

I'm going to close this issue as we've found a solution for your problem but feel free to re-open if this hasn't resolved it for you.

**Comment by AnisTaluqdar** [comment]
Waiting for other platform as well.
