### ISSUE TITLE
Switch from org.matrix.room_key.withheld to m.room_key.withheld #5115

### ISSUE THREAD

**Issue by BillCarsonFr** [vector-im/element-meta#143]
- https://github.com/matrix-org/matrix-js-sdk/issues/2233
- https://github.com/vector-im/element-android/issues/5115

iOS: MSC 2399 is not implemented :\(

Timeline:

1\) Client should start supporting m.room*key.withheld \(as well as org.matrix.room*key.withheld\)
2\) Few month after => Client shoudl start sending instead of org.matrix.room\_key.withheld

**Comment by richvdh** [comment]
I think we consider this done given element-iOS is essentially unmaintained.
