### ISSUE TITLE
The error message shown by rooms with m.federate: false is useless

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-meta#1466]
### Steps to reproduce

Try to invite someone on a different server to an `m.federate: false` room, you get a 'you have no permission to invite' but it doesn't tell you why

### What happened?

You get a 'you have no permission to invite' error message. And it only tells you why buried as the second line of a text block in Advanced settings, where no normal user is going to look.

### What did you expect?

Explain more clearly the why this failed

### Operating system

n/a

### Application version

n/a

### How did you install the app?

n/a

### Have you submitted a rageshake?

No

**Comment by ara4n** [comment]
correction: it does tell you about `m.federate`, buried as the second line of a text block in Advanced settings, where no normal user is going to look.

**Comment by turt2live** [comment]
I don't think this needs design. We just need to fix the error message to understand what unfederated rooms are. We currently assume any `M_FORBIDDEN` error is a generic permissions error:
![image](https://user-images.githubusercontent.com/1190097/168376305-44b89a48-d260-4cab-9363-582fd91966a8.png)

**Comment by turt2live** [comment]
related: https://github.com/vector-im/element-web/issues/22102
