### ISSUE TITLE
Release Pinned messages to public Labs

### ISSUE THREAD

**Issue by JokerGermany** [vector-im/element-meta#1528]
### Your use case

I like using pinned Messages, but it's really sad that you have to activate the "hidden" labs to use it and if i am right, you can't use it on mobile at all.
Would be great if you would release pinned messages in the public Labs. 

### Additional context

https://github.com/vector-im/element-meta/issues/1624

**Comment by t3chguy** [comment]
It's blocked behind mobile support, can't rely on it without it working cross platform.

**Comment by JokerGermany** [comment]
Ok than it would probably better to move this to element-web :thinking: 

In my opinion you shouldn't rely on anything in beta, but i think it would be a good thing, when it would get into public Labs...

But i think pinned messages is a really important feature...

**Comment by t3chguy** [comment]
Oh sorry I misunderstood, you're asking it to be promoted from labs to beta?

**Comment by JokerGermany** [comment]
Yeah, don't know it there is anything on mobile to get promoted, if not it's perhaps better to move the issue to element web :thinking:

**Comment by t3chguy** [comment]
@JokerGermany yeah unfortunately it is very unlikely to reach Beta until mobile at least has it in Labs. I suggest chasing from the mobile end for this to happen.
