### ISSUE TITLE
Information architecture, web (phase II)

### ISSUE THREAD

**Issue by kittykat** [vector-im/element-meta#154]
### Phase II: Secondary: Lower impact changes, for more committed actions

- \[ \] https://github.com/vector-im/element-web/issues/19715
- \[x\] https://github.com/vector-im/element-web/issues/20616
- \[x\] https://github.com/vector-im/element-web/issues/21121

**Comment by daniellekirkwood** [comment]
Hey @kittykat Do you think this should be moved to Concept on the Product Pipeline board as we're not actively looking at this right now? Or is it done?

**Comment by kittykat** [comment]
I think we can close this one as are focus has shifted significantly
