### ISSUE TITLE
Archiving direct chats

### ISSUE THREAD

**Issue by madduck** [vector-im/element-meta#1555]
I'm an early adopter and power-user of Matrix. However, I found that I am hesitant opening direct chats, and I was trying to get to the bottom of that.

One of the reasons is that I already have too many rooms, to the point that it's hard for me to find any particular room at any time. So when I am about to ask a colleague a once-off question, part of my brain goes "I won't make another room just for that".

I'm aware I can tag rooms low-prio, but that's a permanent flag.

I'd like to see a temporary flag "archived", similar to what Whatsapp does: when I am done asking my colleague, I can archive the chat, and it just disappears from my view. It still shows when I click on the colleagues profile, and should the colleague write a message, then it gets unarchived right away, but otherwise the room just isn't shown anymore.

Thanks for your consideration!

**Comment by HammyHavoc** [comment]
After bridging all my different messaging apps into Matrix and thus Element, it's really quite messy scrolling through hundreds of no longer relevant chats. Would make organizing myself much easier if archival ala WhatsApp was a thing, especially if when a new message in an archived chat happened, it ended up being removed from `Archived` status and being brought to my attention. As it stands, it's a total mess.

**Comment by daniellekirkwood** [comment]
Thanks for the suggestion! I'm going to go ahead and move this issue to our Discussions section as it's not something we're working on right now but want to ensure that this feedback is captured and searchable in the future
