### ISSUE TITLE
Information architecture, iOS (phase I)

### ISSUE THREAD

**Issue by kittykat** [vector-im/element-meta#156]
### Phase I: Foundations & quick fixes

*Highest impact changes, solving fundamentals for everyone.*

* \[ \] https://github.com/vector-im/element-ios/issues/5631
* \[x\] https://github.com/vector-im/element-ios/issues/5499
* \[x\] https://github.com/vector-im/element-ios/issues/5501
* \[ \] https://github.com/vector-im/element-ios/issues/5508

#### Build

* \[x\] https://github.com/vector-im/element-ios/issues/5500
* \[x\] https://github.com/vector-im/element-ios/issues/5627
* \[ \] https://github.com/vector-im/element-meta/issues/163
* \[x\] #164

**Comment by daniellekirkwood** [comment]
@kittykat What do you think to closing this one? The remaining items are well written and not in our short-term backlog. We could close this issue and ensure the remaining items are labelled correctly as enhancements for us to apply in the future?
