### ISSUE TITLE
Silent hiding of discussions via auto-created threads considered harmful.

### ISSUE THREAD

**Issue by lamech** [vector-im/element-meta#1590]
#### What would you like to do?

Allow me to create threads deliberately and subscribe only to threads I'm interested in.

#### Why would you like to do it?

Auto-threading hides discussions I want to be able to see, without me even knowing they've happened or been hidden. Worse yet, they multiply the effort required to find those discussions. If I'm in 15 Element rooms, I don't want to also have to check 20 auto-magically created threads in each room just because someone replied to someone else.

#### How would you like to achieve it?

Discord gets this right by allowing the user to decide when to create a thread, and having other users have to subscribe to ("follow") a thread. But they get it wrong by not having a preference to be notified when a new message occurs in threads to which the user has subscribed. So you end up `@`-ing everyone all the time in threads to get their attention. Element seems to get it all wrong by both auto-creating threads (thus: silently and dangerously hiding discussions), *and* having a preference ("messages in group chats") that can only notify me of *every* message in *every* thread in *every* room I'm in, which is so noisy as to be useless. There is no granularity, no signal-to-noise control.

**Comment by clokep** [comment]
Element does not auto-create threads -- user can either reply or create a thread when they reply. Being able to subscribe to threads is #1045 among other issues.

**Comment by t3chguy** [comment]
Closing in favour of #1045
