### ISSUE TITLE
Creating & managing Spaces on iOS

### ISSUE THREAD

**Issue by daniellekirkwood** [vector-im/element-meta#16]
### Quick links

* [Figma](https://www.figma.com/file/PhB0Bf05EdMpdI9rsSsQZ5/%5BExit-beta%5D-Spaces?node-id=602%3A134249)
* [Project board](https://github.com/orgs/vector-im/projects/20/views/1)
* [iOS issues](https://github.com/vector-im/element-ios/issues?q=is%3Aissue+is%3Aopen+label%3Aa-spaces)

---

# Overview

We'd like iOS to achieve parity with other implementations of Spaces. We'd like iOS to:

- Follow the same navigational patterns as Android, but using native iOS interaction patterns
- Reach enough parity where users can achieve the same main goals as Android
- Not burn time building complex or highly committed actions we have no evidence users need on iOS

# Milestones & Issues

Each milestone below is designed to be a set of holistic changes we'd be happy to ship to production. To ease using issue search, we're experimenting prefixing issues with easy to search tags by milestone. Once *this* epic concludes, we should remove the issue prefixes.

## 1: Space creation & rough edge warnings

This set of changes allows users to create Spaces and perform the most common actions within their newly created Space. Subsequent milestones are leaner, and could ship independently.

- This milestone includes placing short lived ‘rough edge’ warnings in several places, which:
- Inform users a feature is coming soon
- Let users know they can achieve their goals on other platforms
- Should be implemented with low effort/iOS native modals
- Will be replaced by working features in subsequent milestones

* \[x\] https://github.com/vector-im/element-ios/issues/5224
* \[x\] https://github.com/vector-im/element-ios/issues/5225
* \[x\] https://github.com/vector-im/element-ios/issues/5226
* \[x\] https://github.com/vector-im/element-ios/issues/5227
* \[x\] https://github.com/vector-im/element-ios/issues/5228
* \[x\] https://github.com/vector-im/element-ios/issues/5229

## 2: Adding rooms to Spaces

- \[x\] https://github.com/vector-im/element-ios/issues/5230

## 3: Update Room Settings

- \[x\] https://github.com/vector-im/element-ios/issues/5231
- \[x\] https://github.com/vector-im/element-ios/issues/5232

## 4: Implement Space Settings

- \[x\] https://github.com/vector-im/element-ios/issues/5233

## 5: Stretch / value adds

A list of stuff we think would be really valuable to iterate on, and add huge value to Spaces. These are in concept until we close out the milestones above:

* Make it easier to access Space menu [\[Figma](https://www.figma.com/file/PhB0Bf05EdMpdI9rsSsQZ5/%5BExit-beta%5D-Spaces?node-id=994%3A120651)\]
* Make it easier to access Spaces [\[Figma](https://www.figma.com/file/PhB0Bf05EdMpdI9rsSsQZ5/%5BExit-beta%5D-Spaces?node-id=994%3A121195)\]
* Increase the left swipe animation speed \(feels like 2-300ms, where most left swipes feel more like 50-100ms\)

~~\* Make it easier to search a Space [\[Figma](https://www.figma.com/file/PhB0Bf05EdMpdI9rsSsQZ5/%5BExit-beta%5D-Spaces?node-id=994%3A121370)\]~~

## Release prep

- \[x\] https://github.com/vector-im/element-ios/issues/5413
- \[x\] https://github.com/vector-im/element-ios/issues/5414
- \[x\] #167

**Comment by nadonomy** [comment]
@kittykat @gileluard can we close this now?
