### ISSUE TITLE
Seperate mentions notifications from username

### ISSUE THREAD

**Issue by webbongithub** [vector-im/element-meta#1623]
#### What would you like to do?

Be able to get notifications when I'm mentioned but not when someone types my username.

#### Why would you like to do it?

My username is "w", and literally any time even remotely uses w it mentions me, such as:

- "w/e"
- "w hat"
- "o w o"
- "https://www.google.com/search?q=massive+w+fortnite"

If I disable it, I don't get notified about mentions.

#### How would you like to achieve it?

Have a separate setting for mentions rather than it being triggered by my username being present

### Have you considered any alternatives?

No.

### Additional context

oh god make it stop

**Comment by t3chguy** [comment]
@clokep can you confirm this is fixed by Intentional Mentions

**Comment by clokep** [comment]
> @clokep can you confirm this is fixed by Intentional Mentions

Yes, this will be fixed by MSC3952 once that's implemented everywhere.

People will need to turn your username into a pill in order to mention you.

As a workaround you can likely disable the "Messages containing my username" notification setting.
