### ISSUE TITLE
The 'on' versus 'noisy' distinction for notifications is confusing

### ISSUE THREAD

**Issue by robintown** [vector-im/element-meta#1632]
### Steps to reproduce

Open notification settings

#### What did you expect?

To be able to understand that setting a particular notification category to 'on' will not cause it to play sounds or vibrate any of my devices.

#### What happened instead?

A long-term failure to understand the conceptual design of notifications.

I assumed that 'on' would cause sounds for those notifications, and ended up using notifications wrong for 4 entire years as a result. Because of this, I was also confused about 'noisy', assuming that it must just be a louder/more vibrate-y version of 'on', which is not correct.

My suggestion is that 'on' be renamed to 'silent', to be clearer about what it does, and to match the notification categories on Element Android.

### Operating system

NixOS unstable

### Browser information

Firefox 99.0

### URL for webapp

develop.element.io

### Application version

Element version: 03ab1237ed77-react-d151365fd751-js-c3d7a4977afa Olm version: 3.2.8

### Homeserver

Synapse 1.56.0

### Will you send logs?

No

**Comment by daniellekirkwood** [comment]
I don't believe we have the concept of noisy in the UI on mobile so this is Web specific. 

Instead of moving it back to the web repo, I'll link the items that will resolve this issue and close it :)

**Comment by daniellekirkwood** [comment]
Here's our epic: https://github.com/vector-im/element-web/issues/24291
Here's the task removing Noisy: https://github.com/vector-im/element-web/issues/24567
