### ISSUE TITLE
Option to hide "Message deleted" on rooms.

### ISSUE THREAD

**Issue by ghost** [vector-im/element-meta#1641]
I want to have a room for rules on my community, clean and simple. But deleted messages leave behind the "Message deleted"

I want to have an option to hide that.

**Comment by daniellekirkwood** [comment]
<img width="655" alt="Screenshot 2023-05-16 at 09 49 56" src="https://github.com/vector-im/element-meta/assets/89144281/5bb79aa9-7c12-4df8-8828-d179425a8fa4">


Being able to control this for all users in a room isn't something we'd look to do at the moment. Therefore I'm going to close out this enhancement request.

**Comment by localhost-anon** [comment]
Proposal: add a "Show a placeholder for removed messages" toggle to Element X (iOS + Android), matching Element Web

Element Web already has this setting — showRedactions ("Show a placeholder for removed messages") under Settings → Preferences — which, when disabled, hides redacted events entirely (shouldHideEvent returns true for redacted, non-thread events). Element X has no equivalent, so on mobile every redacted message leaves a permanent "Message removed" tombstone with no way to opt out. For people who redact frequently (cleanup, privacy/retention workflows, self-hosted servers without server-side purge), timelines fill with tombstones on mobile while Web users can already hide them.

Ask: is the team open to a community contribution adding this as an opt-in toggle in Advanced Settings on both Element X iOS and Android, for parity with Web? 

Defaults unchanged (placeholders shown), so no behavior change unless explicitly enabled.

Scope (kept deliberately small, no rust-sdk changes):
- iOS: hideRedactedMessages in AppSettings, a toggle row in AdvancedSettingsScreen, and filtering redacted items by returning nil in TimelineController.buildTimelineItem when enabled (day separators / read markers are separate virtual items, so they're unaffected). ~50 LOC.
- Android: the setting in AppPreferencesStore + an Advanced Settings toggle (mirroring the existing renderReadReceipts plumbing), and dropping TimelineItemRedactedContent in TimelineItemsFactory — filtering the output list, so the rust-sdk diff cache is untouched. ~120–180 LOC.

Happy to open the iOS and Android PRs (with unit + re-recorded snapshot tests) once there's a design/product 👍. Just wanted to align before writing code, per CONTRIBUTING. Thanks!

**Comment by t3chguy** [comment]
@localhost-anon that option is being removed: https://github.com/element-hq/element-web/pull/33192

Also please do not necropost
