### ISSUE TITLE
Define app layout and information architecture for Element mobile

### ISSUE THREAD

**Issue by niquewoodhouse** [vector-im/element-meta#166]
**Context**

Today, Android has 2 (or, depending on your preferences, 3)  tabs.  iOS has 4 (or, depending on your content, 5) tabs.   Each app is a very different experience to navigate, and the aim of this work is to make them:

- As consistent as we can
- As easy to use as we can

The Experiments we are looking at running are [detailed here](https://github.com/vector-im/element-meta/issues/218)

**Comment by kittykat** [comment]
Assigning to Nique for initial user research, which should be followed up with a kickoff call with the team.

**Comment by niquewoodhouse** [comment]
I've edited the issue to (try to) better represent the current state of the project, and assigned to all the designers on the team working on it.

**Comment by daniellekirkwood** [comment]
I think this has been superseded by https://github.com/vector-im/element-meta/issues/218
@niquewoodhouse & @kittykat any objections to closing this issue?
