### ISSUE TITLE
[Story] Edit my text message

### ISSUE THREAD

**Issue by VolkerJunginger** [vector-im/element-meta#1698]
As a user that has send a text message I want to be able to edit my message to send what I actually wanted to send.
- long press a text message to access the context menu
- the content of the text message is copied into the composer and can be modified
- if the user sends the message the message is inserted into the timeline at the same position as the edited message has been.
- show that the message has been edited to sender & receiver.

## Scope
*These should be a list of technical tasks which take ½-1 day to complete*
```[tasklist]
### Signoffs
- [x] QA signoff on completion
- [x] Design signoff on completion
- [x] Product signoff on completion
```

##  Stretch goals
None at this time

## Out of scope
-

**Comment by ghost** [comment]
**QA Sign-off Status:** :+1: ready to ship for public testing

| Acceptance Criteria | iOS | Android |
| :--- | :---: | :---: |
| Long press a text message to access the context menu | :heavy_check_mark: | :heavy_check_mark: |
| Content of the text message is copied into the composer and can be modified | :heavy_check_mark: | :heavy_check_mark: |
| Edited messages are inserted into the timeline at the same position as the original | :heavy_check_mark: | :heavy_check_mark: |
| Show that the message has been edited to sender & receiver | :heavy_check_mark: | :heavy_check_mark: |

_iOS: Element X 1.2.1 (281) on iPhone 12 mini with iOS 16.5.1_
_Android: Element X 0.1.0-nightly (July 12, 2023) on Google Pixel 6a with Android 13_
