### ISSUE TITLE
Tapping on a user in the message timeline should open the User Details view for that user

### ISSUE THREAD

**Issue by ghost** [vector-im/element-meta#1701]
#### What would you like to do?
Access the user details view for a particular user in one step.

#### Why would you like to do it?
Parity with Element legacy app, and not having to go through the Room Details > People > [user] flow.

#### How would you like to achieve it?
As with Element legacy, simply tapping on the user name or avatar in the messages timeline or a thread should work.

### Additional context

This is a follow up from testing #1105.

**Comment by ShadowJonathan** [comment]
Maybe interesting/important context: on Element Web, currently, there is a duality to this behaviour:
- clicking a user's avatar opens their user profile
- clicking their username adds their mention to the composer

Deciding to define the behaviour here might also require updating that behaviour on web, to harmonise it.

**Comment by manuroe** [comment]
good point @ShadowJonathan! Even if we do not have mentions on EX yet. Mentioning someone is always hard on mobile.
@callumu, @amshakal , what do you thing?

**Comment by manuroe** [comment]
@jmartinesp @Velin92. I am assigning you this user story in order to complete #1105.

**Comment by callumu** [comment]
My opinion is that tapping on the user avatar or name in the timeline should open the user profile page, and then when you press back it takes you back to the same point in the timeline.

I don't think the web behaviour of tapping on the user name to add their mention should be implemented as:

1. It would be very difficult to provide appropriately sized tappable areas for the two different actions
2. It overcomplicates things and we're trying keep things simple for Element X

**Comment by amshakal** [comment]
I agree with what Callum is suggesting. Tapping on the name or avatar of a user in timeline should take them to the user's profile and thats it. We should not consider the mention capability from this, it's confusing and unintuitive.

**Comment by ShadowJonathan** [comment]
I would ask to please back-feed this design decision into Element Web then, but i'm only doing it softly, since I understand that EX is the priority right now :)

**Comment by Velin92** [comment]
https://github.com/vector-im/element-x-ios/issues/1017 opened an issue and currently working on it

**Comment by Velin92** [comment]
This story has been completed and merged on El-X-iOS, will be available on the next nightly.

**Comment by jmartinesp** [comment]
I forgot to mention it's [already done in Element Android X](https://github.com/vector-im/element-x-android/issues/480) too. It's been included in the nightlies for some time now.

**Comment by manuroe** [comment]
thanks @Velin92 , @jmartinesp! Let's move it to QA by using the `X-Needs-Signoff` label.

**Comment by kittykat** [comment]
@jmartinesp on Android, should the "Send message" button do anything yet?

**Comment by jmartinesp** [comment]
> @jmartinesp on Android, should the "Send message" button do anything yet?

Same as https://github.com/vector-im/element-meta/issues/1105#issuecomment-1593452956. It seems like we forgot about that and it was never implemented after the actual logic for creating rooms was built.

**Comment by kittykat** [comment]
Filed issue: https://github.com/vector-im/element-x-android/issues/616

**Comment by ghost** [comment]
Considering this done for QA as launching User Details from the timeline now works both on iOS and Android. 

However, I did encounter a crash on iOS just now and I reported the crash through the iOS crash reporter. I was trying to tap on a user name in the Matrix HQ room timeline and Element X hung then crashed. When I restarted Element X opening the user details worked but was slow to load on the first try (~15s). I have not replicated the crash.
