### ISSUE TITLE
Accepting an invite does not move me from pending to participants for a room

### ISSUE THREAD

**Issue by ghost** [vector-im/element-meta#1702]
Tested on Element X 1.1.1 (222) on an iPhone 12 mini with iOS 16.3.1. This impacts 
_[Story] Join a room following an invitation_ (#991).

#### Steps
1. Be invited to a room with only one other user
2. Accept the invitation
3. Send a message in the room
4. Tap on the room title to open the Room Details view
5. Note the user count on the People button
6. Tap on the People button

#### Expectation
The _People_ count should be 2 and I should show up in the participants list.

#### Result
The _People_ count is 1 and I show up under the _pending_ user list.

**Comment by alfogrillo** [comment]
@ashughes1 can you verify this on newer versions? It looks resolved to me on `1.1.2 (226)`.

**Test**
![result](https://github.com/vector-im/element-meta/assets/19324622/2298606f-55b9-421f-9e1d-70003ac64397)

**Comment by alfogrillo** [comment]
> @ashughes1 can you verify this on newer versions? It looks resolved to me on `1.1.2 (226)`.
> 
> **Test** ![result](https://user-images.githubusercontent.com/19324622/241744692-2298606f-55b9-421f-9e1d-70003ac64397.gif)

@ashughes1 actually this has still a bug: 
the room's details for a dm chat are supposed to look as a user's profile (you don't see the number of members at all in this case) and not as a group chat.
Maybe we can raise an issue for this if you agree.

**Example of correct room's settings for a direct chat**
![Simulator Screenshot - iPhone 14 Pro - 2023-05-29 at 16 26 17](https://github.com/vector-im/element-meta/assets/19324622/cef5cb37-99a3-4e9c-a323-2a0a7afe08d2)

**Comment by ghost** [comment]
@alfogrillo I retested this on Element X 1.1.6 (257) on my iPhone 12 mini and the issue as reported is no longer happening. I will close this issue for now.

As for the DM vs Group UI in your comment above I can confirm I am seeing the standard room UI if the invite is sent from outside Element X (Element legacy or Element web). If the invite is sent from Element X it displays with the DM UI. 

If this is a bug then I will file it. Please let me know.

**Comment by alfogrillo** [comment]
@ashughes1 in theory it doesn't matter if you send the invite from EX or from another client.
After accepting the invite you should see the "direct message" UI.
Again I think this problem may be related with this [issue](https://github.com/matrix-org/matrix-rust-sdk/issues/2078).
Please let me know if clearing the cache from the "Developer options" fixes the problem.

**Comment by ghost** [comment]
@alfogrillo if I clear cache it starts showing the DM UI but not for newly created DMs.

#### Steps
1. _UserA_: Create a DM with _UserB_ on Element Web
2. _UserB_: Accept the invite on Element X iOS then tap the room title (note, UI is the _Room Details_ UI)
3. _UserB_: Go back to the _All Chats_ screen, open the developer options and clear cache
4. _UserB_: Go back to the DM room and open the room details again (note, UI this time is the _DM_ UI)
5. _UserB_: Leave the room
6. _UserA_: Leave the room and send another DM request to _UserB_
7. _UserB_: Accept the invite then tap the room title (note, UI is the _Room Details_ UI again)

**Comment by alfogrillo** [comment]
> @alfogrillo if I clear cache it starts showing the DM UI but not for newly created DMs.
> 
> #### Steps
> 1. _UserA_: Create a DM with _UserB_ on Element Web
> 2. _UserB_: Accept the invite on Element X iOS then tap the room title (note, UI is the _Room Details_ UI)
> 3. _UserB_: Go back to the _All Chats_ screen, open the developer options and clear cache
> 4. _UserB_: Go back to the DM room and open the room details again (note, UI this time is the _DM_ UI)
> 5. _UserB_: Leave the room
> 6. _UserA_: Leave the room and send another DM request to _UserB_
> 7. _UserB_: Accept the invite then tap the room title (note, UI is the _Room Details_ UI again)

If after `7.` you clear the cache again, does the UI get fixed again?
I think this is again related with [this rust issue](https://github.com/matrix-org/matrix-rust-sdk/issues/2078)

**Comment by ghost** [comment]
Yes, every time I clear the cache it fixes it for any active DMs but any newly created DMs will have the same problem until the cache is subsequently cleared.

**Comment by alfogrillo** [comment]
> Yes, every time I clear the cache it fixes it for any active DMs but any newly created DMs will have the same problem until the cache is subsequently cleared.

Thanks for clarifying.
So I think it's still related with the above [issue](https://github.com/matrix-org/matrix-rust-sdk/issues/2078).
Let's try again after the other team close it. 👍🏻
