### ISSUE TITLE
[Story] Copy text message content to clipboard

### ISSUE THREAD

**Issue by VolkerJunginger** [vector-im/element-meta#1704]
As a user I want to copy the content of text message to the clipboard so that I can paste it somewhere else.

## Scope
*These should be a list of technical tasks which take ½-1 day to complete*
```[tasklist]
### Signoff
- [x] QA signoff on completion
- [x] Design signoff on completion
- [x] Product signoff on completion
```

##  Stretch goals
None at this time

## Out of scope
Copy other content than text.

**Comment by ghost** [comment]
Tested on Element X iOS 1.2.1 (281) and Element X Android 0.1.0-nightly (July 12, 2023) without any issues.
