### ISSUE TITLE
[Story] Show a message has been deleted

### ISSUE THREAD

**Issue by VolkerJunginger** [vector-im/element-meta#1706]
### A story should take roughly a week or a sprint to finish. Each story is usually made up of a number of tasks that take half to a full day.

As a user that has a deleted message in the timeline I want to see a hint that the message has been deleted.
- Don't show a context menu for the deleted message (no actions, no reaction).

## Scope
*These should be a list of technical tasks which take ½-1 day to complete*
```[tasklist]
### Signoffs
- [x] QA signoff on completion
- [x] Design signoff on completion
- [x] Product signoff on completion
```

##  Stretch goals
None at this time

## Out of scope
-

**Comment by ghost** [comment]
Confirmed this is working on Element X iOS 1.2.1 (281) and Element X Android 0.1.0-nightly (July 12, 2023).
