### ISSUE TITLE
[Story] Forward a message

### ISSUE THREAD

**Issue by VolkerJunginger** [vector-im/element-meta#1707]
As a user that has (almost any) message in the timeline I want to forward that message.

- long press a message to open the context menu
- if the user selects "forward" show a list of room the user is a member in
- the user can choose the room they want to send the message in
- After sending the message the user is in the timeline where they send the message

## Scope
*These should be a list of technical tasks which take ½-1 day to complete*
```[tasklist]
### Signoff
- [x] QA signoff on completion
- [x] Design signoff on completion
- [x] Product signoff on completion
```

##  Stretch goals
None at this time
<or add a tasklist>

## Out of scope
- Showing that a message has been forwarded.
- Forwarding multiple messages
- forwarding exotic / custom messages like polls

**Comment by jplatte** [comment]
What about forwarding replies? Should the replied-to message be included as a quote? It might be worth noting that this would make the implementation more complex, since reply fallbacks are going away and we're already stripping them in EX – plus they might not be appropriate anyways.. do we want to leak the info which room a message was forwarded *from*?

**Comment by VolkerJunginger** [comment]
No, do not refer to the replied-to message in any way.
No, don't show any origin of the original message.

The forwarded message should look like a normal message by the user that forwarded it.

**Comment by jmartinesp** [comment]
In this screen we need to:

- List a subset of the joined rooms so we can select them.
- Update the contents of this list based on a text query.

I was taking a look at what we could use from the Rust SDK to achieve those and I'm not really sure about those, specially the 'search/filter rooms' part. Do we have some helper for that in the SDK? Should we instead try to load *all* joined rooms and then filter them in the platform side?

EDIT:

I see we could try to use a `SlidingSyncList` whose `Builder` uses a filter with `roomNameLike = $query`, and we'd have to close and create a new list for every change in this query. Is this the best way to achieve this feature?

**Comment by ghost** [comment]
**QA Sign-off Status:** :+1: ready to ship for public testing _(with a couple minor issues)_

| Acceptance Criteria | iOS | Android |
| :--- | :---: | :---: |
| Long press a message to access the context menu | :heavy_check_mark: | :heavy_check_mark: |
| Select "forward" shows a list of rooms the user is a member in | :heavy_check_mark: | :heavy_check_mark: |
| Can choose the room they want to send the message in | :heavy_check_mark: | :heavy_check_mark: |
| After sending the message the user is in the timeline where they sent the message | :heavy_check_mark: | :heavy_check_mark: |

_iOS: Element X 1.2.1 (281) on iPhone 12 mini with iOS 16.5.1_
_Android: Element X 0.1.0-nightly (July 12, 2023) on Google Pixel 6a with Android 13_

#### Issues Found
I found two issues of note:

First, forwarding a reply to an attachment (a photo for example) only forwards the text of the reply and not the attachment replied to. 

Example of what I am forwarding:
<img src="https://github.com/vector-im/element-meta/assets/766595/f919c34d-b3e9-44ed-9785-146e53dbeb57" width="50%" />

Example of what it looks like when forwarded:
<img src="https://github.com/vector-im/element-meta/assets/766595/72bdb11f-5409-4ed2-a6cb-4906662130b9" width="50%" />

The second issue is that when forwarding we only get the content of the message forwarded, not who it was forwarded from (ie. the originator of the content being forwarded). This is perhaps a design decision but it might be useful to include that info.
