### ISSUE TITLE
[Story] Resend a message

### ISSUE THREAD

**Issue by VolkerJunginger** [vector-im/element-meta#1708]
As a user that has a message in the timeline that failed to be send I want to be able to resend that message so that I don't have to create that message again.

-Show that a message could not be send.
- When tapping that indicator give the option to resend the message.

## Scope
*These should be a list of technical tasks which take ½-1 day to complete*
```[tasklist]
### Tasklist
- [ ] Task 1
- [x] QA signoff on completion
- [x] Design signoff on completion
- [x] Product signoff on completion
```

##  Stretch goals
None at this time
<or add a tasklist>

## Out of scope
-

**Comment by ghost** [comment]
Tested this on Element X iOS 1.2.1 (281) and Element X Android (July 12, 2023). Not finding any major issues I consider this signed off by QA for public testing.

I would not that there is one minor UI issue on Android with the timestamp overlapping message content in send failure bubbles. This is not present on iOS.
![1000000039](https://github.com/vector-im/element-meta/assets/766595/dc8bed80-48b5-457f-be6f-4c319f7037ed)
