### ISSUE TITLE
Add Project Board Automation to the Element-Meta repo (LABELLED)

### ISSUE THREAD

**Issue by daniellekirkwood** [vector-im/element-meta#173]
Adding project board automation to the Element-Meta repo. 

Copy the automation from the other repo's

| Web jobs | Android Jobs | iOS Jobs  |
| --- | --- | --- |
| - apply_Z-Labs_label:<br />- move_needs_info_issues:<br />- add_priority_design(...):<br />- add_product_issues:<br />- Delight_issues_to_board:<br />- move_voice-message_issues:<br />- move_threads_issues:<br />- move_message_bubbles_issues:<br /> | - apply_Z-Labs_label: <br />- move_needs_info_issues: <br />- add_priority_design(...):<br /> - add_product_issues:<br /> delight_issues_to_board:<br /> - move_voice-message_issues:<br /> - move_threads_issues:<br /> - move_message_bubbles_issues:<br /> - move_ftue_issues:<br /> - move_WTF_issues:<br /> | - apply_Z-Labs_label:<br /> - move_needs_info_issues:<br /> - add_priority_design(...):<br /> - add_product_issues_to_project:<br /> - Delight_issues_to_board:<br /> - move_voice-message_issues:<br /> - move_threads_issues:<br /> - move_message_bubble_issues:<br /> - move_FTUE_issues:<br /> - move_WTF_issues:<br /> |

Looking at the Labelled only file already in Element-Meta to confirm or add the automation: 
- [x] Z-Labels
- [x] Design
- [x] Product
- [x] Delight
- [x] VMs
- [x] Threads
- [x] Bubbles
- [x] FTUE
- [x] WTFs

**Comment by kittykat** [comment]
In `triage-labelled.yml`, the `move_needs_info_issues` bit won't work.
And in `triage-unlabelled.yml`, the `Move_Unabeled_Issue_On_Project_Board` should be excluded.

Otherwise, the other automation in those two files should be added

**Comment by daniellekirkwood** [comment]
Added FTUE and WTF automations as the rest of the list was already in the Labelled file
