### ISSUE TITLE
[Story] Add notifications decoration in the rooms list

### ISSUE THREAD

**Issue by giomfo** [vector-im/element-meta#1746]
## Description ##

<img width="865" alt="image" src="https://github.com/vector-im/element-meta/assets/8969772/a2cddfa0-f81f-4886-b916-a6a30df98b46">

## Scope
```[tasklist]
### Android
- [ ] https://github.com/vector-im/element-x-android/issues/547
- [ ] https://github.com/vector-im/element-x-android/issues/548
```

```[tasklist]
### iOS
- [ ] https://github.com/vector-im/element-x-ios/issues/1035
- [ ] https://github.com/vector-im/element-x-ios/issues/1037
```

- [x] QA signoff on completion
- [x] Design signoff on completion
- [x] Product signoff on completion

##  Stretch goals
None at this time

## Out of scope
-

**Comment by giomfo** [comment]
@langleyd FYI:
- iOS: @nimau is currently working on the first task
- Android: not started

**Comment by callumu** [comment]
@langleyd Can we make sure the icon colours for mute and mentions are color/icon/tertiary on both platforms?

**Comment by kittykat** [comment]
We're happy with how it works for now, will revisit with improvements later on
