### ISSUE TITLE
Review IA flow on how user receives invites to a space and a room

### ISSUE THREAD

**Issue by kittykat** [vector-im/element-meta#178]
Converge on notifications, and how invites are shown

#### Web
Space missing from list of invites:
![Screenshot from 2022-02-23 23-41-52](https://user-images.githubusercontent.com/51663/155429703-d1b5b13c-516e-4540-9d04-e52452c8b97f.png)

#### iOS
![ima_bad2a71](https://user-images.githubusercontent.com/51663/155427107-786eebc8-5da6-4deb-91e4-95aac1aacf95.png)

#### Web
![Screenshot from 2022-02-23 22-27-56](https://user-images.githubusercontent.com/51663/155426858-aa20d534-efdf-4cb2-b741-cfacb6ad35e5.png)

#### Android
![Screenshot_20220223-224457](https://user-images.githubusercontent.com/51663/155426970-0dc106f3-a7b2-4f69-b537-336dfe3eaf4b.png)
![Screenshot_20220223-224505](https://user-images.githubusercontent.com/51663/155426997-f28ed4e7-7224-450d-b04c-9657ab8549b3.png)

#### iOS
![ima_75fe818](https://user-images.githubusercontent.com/51663/155427100-24e9eaf2-6635-4ab9-8ea3-d0d7d57a0601.png)
![ima_1f7c571](https://user-images.githubusercontent.com/51663/155427104-91bff845-5644-4502-bb15-6a62b18d150e.png)

#### Web
![Screenshot from 2022-02-23 22-35-16](https://user-images.githubusercontent.com/51663/155427208-696556a3-443d-45b5-a280-ac3cc64413da.png)

#### Android
![Screenshot_20220223-224513](https://user-images.githubusercontent.com/51663/155427265-95e62121-578c-4af9-ada8-fd6e00d59e8e.png)
![Screenshot_20220223-224520](https://user-images.githubusercontent.com/51663/155427287-872dcbf6-6122-4704-90f2-6432bb2c1cf8.png)

#### iOS
![ima_0abbee2](https://user-images.githubusercontent.com/51663/155427106-464ce8a2-e488-4913-b079-be2ec96fe0d3.png)
![ima_6393362](https://user-images.githubusercontent.com/51663/155427103-85fb2e04-bdfa-427f-aeb4-245ef4323a99.png)

#### Web
![Screenshot from 2022-02-23 22-50-21](https://user-images.githubusercontent.com/51663/155427340-aaa5e6ad-430a-4ff9-9dc7-389cc4ba9825.png)

#### Android
![Screenshot_20220223-225044](https://user-images.githubusercontent.com/51663/155428740-486958ea-ee05-4e41-ab4e-a101315120c0.png)

![Screenshot_20220223-225100](https://user-images.githubusercontent.com/51663/155428103-a7e45bc9-66c9-4659-9936-63f5a0db6e15.png)
![Screenshot_20220223-225106](https://user-images.githubusercontent.com/51663/155428241-b55e80cf-71e6-4242-a7b2-e4d95366c222.png)

#### iOS
![ima_a70f229](https://user-images.githubusercontent.com/51663/155427111-9bb7af4d-11b9-4d4e-88f1-30b28712fed8.png)
![ima_85c59b8](https://user-images.githubusercontent.com/51663/155427114-b28fee61-9f4e-45d3-a018-45ba3e26f586.png)

**Comment by niquewoodhouse** [comment]
After discussion with @kittykat the first step would be fixing the room invite on Android to be more about the room than the inviter.


![](https://user-images.githubusercontent.com/51663/155427287-872dcbf6-6122-4704-90f2-6432bb2c1cf8.png)

**Comment by niquewoodhouse** [comment]
I think we should try to re-use the logic/content of the a space invite preview:

<img width="360" alt="re-use space preview@2x" src="https://user-images.githubusercontent.com/1587166/157890503-a4236590-9c2f-49ad-88c1-f34bf5dcc2ed.png">

Trying to use what we already have. [Figma](https://www.figma.com/file/IkbPpsC0XGCV745NZQcxc2/Untitled?node-id=2%3A3141)

**Comment by kittykat** [comment]
I'm going to close this issue as the DM flow has been reviewed and updated/in progress. The other two flows can be descoped to FTUE
