### ISSUE TITLE
Ad missing posthog events

### ISSUE THREAD

**Issue by VolkerJunginger** [vector-im/element-meta#1783]
### A story should take roughly a week or a sprint to finish. Each story is usually made up of a number of tasks that take half to a full day.

The following posthog events are needed for the EX dashboard.

composer
- isEditing
- is reply

ViewRoom
- isDM

CreatedRoom
- isDM

JoinedRoom
- isDM

screen
- screenName
- durationMs

```[tasklist]
### Tasks
- [x] [iOS] Add missing posthog events https://github.com/vector-im/element-x-ios/issues/1097
- [x] [Android] Add missing posthog events https://github.com/vector-im/element-x-android/issues/624
```

**Comment by giomfo** [comment]
@VolkerJunginger I have 2 questions:
- what do you expect exactly about `isDM` boolean? should we keep the legacy way to decide if a room is a DM, or do you expect a change? I heard that we plan to limit DM to the 2 members rooms, but perhaps this is too early to change the conditions to be a direct (This question is mainly about `ViewRoom` where we can check members number) 
- can you confirm the last one is `MobileScreen`? FYI we will use first the existing screenName defined [here](https://github.com/matrix-org/matrix-analytics-events/blob/main/schemas/MobileScreen.json).

**Comment by VolkerJunginger** [comment]
Treat isDM the same we have in the other apps.

**Comment by giomfo** [comment]
@VolkerJunginger FYI I checked with @yostyle and @nimau the existing Analytics implementation. It seems that `durationMs` is not available for the Screen event for the moment. It was not sent in the Legacy app at least for the code we checked. So we will not probably include this duration in our commits for this task

**Comment by nimau** [comment]
For the `JoinedRoom` event, the room size is calculated using the `activeMembersCount` room property available in the RustSDK.
The `activeMembersCount` is the number of members who have joined or been invited to the room.

Note: in the legacy Element-iOS, this room size was considering only joined members. We consider more relevant to include the invited members

@yostyle
