### ISSUE TITLE
Location Sharing Tracking

### ISSUE THREAD

**Issue by VolkerJunginger** [vector-im/element-meta#1797]
For the location sharing feature implement the following tracking events for posthog:

**When sending a location**
Event: Composer
Property: isLocation
Property Type: enum
Value: Mylocation, otherlocation

**Viewing a location when sharing**
Event: ¢screen
Property: LocationShare

**Viewing a location**
Event: ¢screen
Property: LocationView

**Comment by Johennes** [comment]
I've converted this into the individual stories. Thanks for logging.
