### ISSUE TITLE
[Story] Show a "migrating..." screen 

### ISSUE THREAD

**Issue by VolkerJunginger** [vector-im/element-meta#1805]
As a user that has logged in to EX for the first time I want to have transparency how long the initial setup takes so that I can wait patiently and don't panic that something might be broken.

- After  1st time login show a "migrating..." screen that tells the use that his account is being setup and migrated to be used with EX.
- Show an activity indicator.

## Scope
*These should be a list of technical tasks which take ½-1 day to complete*
```[tasklist]
### Tasklist
- [ ] Task 1
- [ ] QA signoff on completion
- [ ] Design signoff on completion
- [ ] Product signoff on completion
```

##  Stretch goals
None at this time
<or add a tasklist>

## Out of scope
-

**Comment by pixlwave** [comment]
A couple of options here for feedback:

**With fake progress bar**
Feels slow but could be for some users. Bar stops at 90% incase it needs longer

https://github.com/vector-im/element-meta/assets/6060466/a3429a1a-28a1-4a9b-b990-03f65272cbf6 

**With progress indicator**
Feels indeterminate

https://github.com/vector-im/element-meta/assets/6060466/3251df3f-cd35-4396-bb7f-97cb5c0731a0

**Comment by VolkerJunginger** [comment]
Why does the progress bar take 7 minutes?

In general I would go with the progress bar because it gives you "some" hope that something is happening - you get constant feedback. Whereas starring at a spinner leaves the user quite in the dark.

**Comment by VolkerJunginger** [comment]
Based on personal discussion we'll go with the spinner.

**Comment by ryanmcgrath** [comment]
Would it make sense to show some basic log text here, e.g what "step" the migration is on? The current infinite spinner leaves a bit to be desired since it's hard to know if something has just broken silently in the background.

From a UI/UX perspective I understand perhaps not wanting to overwhelm the user, but a basic label would help get a sense of what's going on when it hangs.

**Comment by pixlwave** [comment]
Closing this as done on both platforms.
