### ISSUE TITLE
Converge on suggested room preview in Spaces

### ISSUE THREAD

**Issue by kittykat** [vector-im/element-meta#181]
Android and iOS should have the same behaviour in terms of what to show when a suggested room for a Space is previewed from the Rooms tab.

- iOS: Click on suggested rooms navigates to room preview
![ima_3a9ccab](https://user-images.githubusercontent.com/51663/156764656-9ec8f2ac-0a8d-41e3-8275-2c013951e0a2.png)

- Android: no preview shown, only toast
![Screenshot_20220304-115333](https://user-images.githubusercontent.com/51663/156764690-161446a7-d3e8-4e0a-8fbd-e221bf1ff634.png)

## Tasks

- [x] Design input on what the correct behaviour should be
- [x] File an issue with designs for the change

**Comment by niquewoodhouse** [comment]
@gileluard would you mind confirming please if this always happens for suggested rooms in Spaces?

> iOS: Click on suggested rooms navigates to room preview
> ![](https://user-images.githubusercontent.com/51663/156764656-9ec8f2ac-0a8d-41e3-8275-2c013951e0a2.png)

Because I remember you sharing something like this: 
<img width="414" alt="image" src="https://user-images.githubusercontent.com/1587166/157029074-3d9d49a5-84b0-440f-bc7c-a8d506ab702a.png">

Thanks

**Comment by gileluard** [comment]
@niquewoodhouse you're right. The room preview is inconsistent over the app. From Space Explore Rooms the bottom sheet is opened while the room preview screen is opened from the other parts of the app.

**Comment by niquewoodhouse** [comment]
@gileluard can we make suggested rooms in Home act the same way as the room preview in Space Explore Rooms please?  This would resolve this issue and if we wanted to make all previews the same/similar, it would be a different issue.

**Comment by gileluard** [comment]
@niquewoodhouse we definitively can!

**Comment by kittykat** [comment]
Issue for development filed at https://github.com/vector-im/element-ios/issues/5771
