### ISSUE TITLE
Decryption errors between two parties

### ISSUE THREAD

**Issue by madduck** [vector-im/element-meta#1814]
Taking this over from https://github.com/matrix-org/olm/issues/84 — my cousin `@bebeas:matrix.org` and I (`@madduck:madduck.net`) just reproduced the problem on our respective devices (iOS, Android (post-Rust-e2e upgrade)) and referenced this issue in both reports.

Thanks for looking into this!

CC: @richvdh

**Comment by richvdh** [comment]
I've found the rageshakes (btw, "element-meta/1814" doesn't auto-link: you need the full URL `https://github.com/vector-im/element-meta/issues/1814`). Can you point me to an event that did not decrypt?

**Comment by t3chguy** [comment]
FTR `vector-im/element-meta#1814` would autolink

**Comment by madduck** [comment]
@richvdh

`$C0Ruaw20Dbp5L64JWZ3DtcJ6RuTptXNdmB2LHKTRxXY` is the event I sent from Android, which my cousin on iOS could read, though I think that's a first;

`$MrUVGkONCxqggejLnAwiV4dJgbkQ1zlqjplzJ_LnEcg` is the event she sent, which shows up as unable to decrypt:

```
{
  "type": "m.room.message",
  "content": {
    "msgtype": "m.bad.encrypted",
    "body": "** Unable to decrypt: DecryptionError: The sender's device has not sent us the keys for this message. **"
  }
}
```

and here is the original event source:

```
{
  "content": {
    "algorithm": "m.megolm.v1.aes-sha2",
    "ciphertext": "AwgCEoABx4L29B31mry6M7z0+Iaorlzo+qv7UeGme9tfxfcVkodnBPdukDFvc4YealHVWe9xhElkJLVX7To/jIPhhLrYgzz5pDR1yh1cIUW8zkgUhnZOL7r50lUK75SPx9yNUtINUmLYaQF2OIaDZ50gZzuVkHJFNmImpO5oZpyTasoVNofoC6QzR0f+u67OBNxg7j2QXjgMwrir9ssrVEuwcufqVd9CAGS3fc4MTMt6uwLXf5D04ahZ0VJGU98bwYXlsoLmebe3G5m8IAA",
    "device_id": "ZEVTWSJYVB",
    "sender_key": "bX86j31w35dUkAKdxUVejnOUIkWtsE/zOtEvqhGm9zE",
    "session_id": "f+SZni6qwvLkwdhRQV9nofWP+ODJjvoCk9TmxKDr+jk"
  },
  "origin_server_ts": 1688460082671,
  "sender": "@bebeas:matrix.org",
  "type": "m.room.encrypted",
  "unsigned": {},
  "event_id": "$MrUVGkONCxqggejLnAwiV4dJgbkQ1zlqjplzJ_LnEcg",
  "room_id": "!fJCjGgkLyroBqggsEo:madduck.net"
}
```

**Comment by richvdh** [comment]
From the sender's rageshake:

```
2023-07-03 09:56:27.205 Element[47458:3140557] [MXCryptoSDK] TRACE share_room_key{room_id="!fJCjGgkLyroBqggsEo:madduck.net"}: matrix_sdk_crypto::olm::account: Creating a new room key room_id="!fJCjGgkLyroBqggsEo:madduck.net" algorithm="m.megolm.v1.aes-sha2"
2023-07-03 09:56:27.205 Element[47458:3140557] [MXCryptoSDK] TRACE share_room_key{room_id="!fJCjGgkLyroBqggsEo:madduck.net"}: matrix_sdk_crypto::session_manager::group_sessions: Calculating group session recipients users={"@madduck:madduck.net", "@bebeas:matrix.org"} settings=EncryptionSettings { algorithm: "m.megolm.v1.aes-sha2", rotation_period: 604800s, rotation_period_msgs: 100, history_visibility: "shared", only_allow_trusted_devices: true } session_id="f+SZni6qwvLkwdhRQV9nofWP+ODJjvoCk9TmxKDr+jk" room_id="!fJCjGgkLyroBqggsEo:madduck.net"
2023-07-03 09:56:27.208 Element[47458:3140557] [MXCryptoSDK] TRACE share_room_key{room_id="!fJCjGgkLyroBqggsEo:madduck.net"}: matrix_sdk_crypto::session_manager::group_sessions: Done calculating group session recipients should_rotate=false session_id="f+SZni6qwvLkwdhRQV9nofWP+ODJjvoCk9TmxKDr+jk" room_id="!fJCjGgkLyroBqggsEo:madduck.net"
2023-07-03 09:56:27.208 Element[47458:3140557] [MXCryptoSDK]  INFO share_room_key{room_id="!fJCjGgkLyroBqggsEo:madduck.net"}: matrix_sdk_crypto::session_manager::group_sessions: Trying to encrypt a room key index=0 recipients={"@bebeas:matrix.org": {"DQMZENMKPQ", "GZUKKKFINI", "HEVKFEZMTH"}} session_id="f+SZni6qwvLkwdhRQV9nofWP+ODJjvoCk9TmxKDr+jk"
```

In other words: `babeas`'s device is not sending the room key to any of `madduck`'s devices.

However, I note in particular: `only_allow_trusted_devices: true`. Has `babeas` enabled "encrypt to verified sessions only"? If so, have you and she gone through the verification process? Does she see a green shield for your user in her client?

**Comment by madduck** [comment]
This was the issue. What I find really weird is that my cousin doesn't even know about verification and has never verified with anyone, yet I am the only one she's having problems with.

Also, she swears to have never flipped that setting on. Just like it was for me, actually in https://github.com/matrix-org/olm/issues/84 — I generally never had issues with anyone except a few people, and I also know I never flipped that setting.

Regardless, I am wondering if there mightn't be a better way to expose this in the UI, i.e. the sender knows when they sent only to a subset of devices in a room, and should possibly visualise that, or at least offer a way to find out when recipients claim about undecryptable message.

And maybe there is a way to include in the event a list of devices that have been omitted, so that the receiver can get a better explanation of what's going on? Because currently ("unable to decrypt" or "waiting for the sender to send keys") don't contain any clues, and are misleading too, because the sender will never send keys.

**Comment by t3chguy** [comment]
> yet I am the only one she's having problems with.

The setting can be enabled both account-wide but also per-room. Likely it was enabled just in your DM.

> Regardless, I am wondering if there mightn't be a better way to expose this in the UI, i.e. the sender knows when they sent only to a subset of devices in a room, and should possibly visualise that, or at least offer a way to find out when recipients claim about undecryptable message.

Normally the recipient's client shows an error saying `** Unable to decrypt: DecryptionError: The sender has disabled encrypting to unverified devices. **` but this relies on the other side supporting notifying the recipient of that. Wouldn't surprise me if the mobile apps lacked that, the Web & Desktop clients definitely support it.

**Comment by madduck** [comment]
> The setting can be enabled both account-wide but also per-room. Likely it was enabled just in your DM.

Nope. It was definitely enabled globally for both of us. It's very strange.

**Comment by pmaier1** [comment]
Thanks for the report. This is very unfortunate behavior which we'd like to avoid in the future, of course. We are planning to take action with a couple of changes that will improve the user experience here:
- Avoid untrusted devices by forcing device verification during setup (as simple as scanning a QR code)
- Introduce TOFU (trust on first use; automated trust between users) and isolate untrusted devices (other users won't send them keys and won't accept their keys) => makes the setting in question obsolete

Hope this helps as an outlook.

**Comment by richvdh** [comment]
Ok, so this particular instance seems to be resolved. As @pmaier1 says, we're hoping to improve the UX in future to stop this being as much of a problem.
