### ISSUE TITLE
[Story] Hide UTDs for messages received before logging in

### ISSUE THREAD

**Issue by manuroe** [vector-im/element-meta#1816]
As a user, I do not want to see walls of UTDs just after logging in. I want to understand that history decryption is not available yet.
so that I cannot blame EX to another broken elements app.

We want to hide UTDs for message received before the user signed in. We will use the local time of the signin for that.
We are going to use the same collapsing logic as for state events. 

Considerations:
- This user story will be removed with key backup restore but we may continue to use the same collapsing logic for UTDs
- Using logic based on message timestamp is always something we avoid but this user story is temporary.

## Acceptance criteria:
 - User sees a new modal/pop up after you have signed in to explain why they will not be able to decrypt the history
 - Update verification banner copy
 - User does not see anymore those before signin UTDs
 - User cannot uncollapse them
 - The timeline stops back paginating after hiting a before-signin UTD.

## Scope
```[tasklist]
### iOS
- [x] Update verification banner copy. It is lying
- [x] Add an extra modal/pop up after you have signed in
- [ ] https://github.com/vector-im/element-x-ios/issues/1251
- [x] QA signoff on completion
- [x] Design signoff on completion
- [x] Product signoff on completion
```

Android needs to be considered only if we do not implement backup restore before.

```[tasklist]
### Android
- [x] Update verification banner copy. It is lying
- [x] Add an extra modal/pop up after you have signed in
- [ ] https://github.com/vector-im/element-x-android/issues/838
- [x] QA signoff on completion
- [x] Design signoff on completion
- [x] Product signoff on completion
```

##  Stretch goals
None at this time
<or add a tasklist>

## Out of scope
-

**Comment by jmartinesp** [comment]
Are there any designs for this? I can't find anything in Figma.

EDIT: found them in https://www.figma.com/file/0MMNu7cTOzLOlWb7ctTkv3/Element-X?node-id=7395%3A128396&mode=dev
