### ISSUE TITLE
Contact list 

### ISSUE THREAD

**Issue by AnisTaluqdar** [vector-im/element-meta#182]
**Is your feature request related to a problem? Please describe.**

I like to have a contact list in element. If I somehow leave the chat I lost the contact and it's not possible to remember every friends contact or matrix Id. Also people can create different id what actually their name so it's very difficult to find out old friend.

**Describe the solution you'd like**
Element can create a contact list and it can store whenever a new dm create it can save the contact also it can be possible to save manually. 

**Describe alternatives you've considered**
hmm, at least it can save as massage in room, contact name and Id and it can present as a contact list.

**Additional context**
https://github.com/matrix-org/matrix-doc/issues/2936
https://github.com/matrix-org/matrix-doc/issues/556
vector-im/element-meta#341

**Comment by t3chguy** [comment]
Merging with https://github.com/vector-im/element-meta/issues/341
