### ISSUE TITLE
Very slow / no response when adding 16 users to a room

### ISSUE THREAD

**Issue by nickbearman** [vector-im/element-meta#1822]
### Steps to reproduce

When inviting 16 users to join a new room, Element just hangs and I have no idea whether it is adding the users or not:

![Screenshot 2023-07-07 112033](https://github.com/vector-im/element-web/assets/6410645/7d651bb0-91ac-4de0-8ca5-dfecd2850b27)

I will attach debug logs. 

For clarity, this is an Element One room https://one.element.io/#/room/!xUzrFTPyOAvJFvabGE:one.ems.host created by @nickbearman:one.ems

And I am adding people from the user @nickbearman:matrix.org so people will be invited to create a Matrix account on matrix.org rather than one.ems.host which will fail. 

#### What did you expect?
I expected the users to be added, or some progress bar if this was going to take a while. 

#### What happened instead?
It just sat there as per the screenshot, now for 4 min. 

There are some related topics related to converting spaces to rooms which may be relevant:
https://github.com/vector-im/element-web/issues/19216
https://github.com/matrix-org/matrix-react-sdk/pull/6887
https://github.com/vector-im/element-web/issues/19362

And from this it looks like I should see a progress bar, but I don't. 

### Operating system

Windows

### Browser information

Google Chrome Version 114.0.5735.199 (Official Build) (64-bit)

### URL for webapp

https://app.element.io/#/room/!xUzrFTPyOAvJFvabGE:one.ems.host

### Application version

Element version: 1.11.35 Olm version: 3.2.14

### Homeserver

matrix.org / one.ems

### Will you send logs?

Yes

**Comment by nickbearman** [comment]
I have cancelled the add and added the logs

**Comment by nickbearman** [comment]
From here it looks like 6 people were added:

![image](https://github.com/vector-im/element-web/assets/6410645/9abc9079-a719-4cc4-84d4-5908eb82b92d)

**Comment by t3chguy** [comment]
`MatrixError: [429] Too Many Requests` seems like your server is aggressively rate-limiting you.

**Comment by nickbearman** [comment]
Thanks @t3chguy 
So I will try to invite more people later on. Any suggestions how long I should wait? 5min? an hour?

**Comment by t3chguy** [comment]
I do not know the settings on matrix.org or one.ems, I suggest contacting their respective supports

**Comment by nickbearman** [comment]
Thanks - have already contacted one.ems support, hopefully they can help. 
Thanks for your help.

**Comment by nickbearman** [comment]
After a while this error was shown:
![Screenshot 2023-07-07 113948](https://github.com/vector-im/element-web/assets/6410645/88faa86e-8437-489a-8de2-a6093f051166)

**Comment by t3chguy** [comment]
Yeah so it'll retry 5s after the M_LIMIT_EXCEEDED error but seemingly gives up when encountering such an aggressive throttling

**Comment by nickbearman** [comment]
Now (15 min later) trying to add the people who were missed one by one. I get this error:

![Screenshot 2023-07-07 114249](https://github.com/vector-im/element-web/assets/6410645/4deb2df3-cf34-4f99-a791-a259a1bcd11c)

So guessing I am still rate limited currently.

**Comment by nickbearman** [comment]
Thanks - I will wait for a bit longer then!

**Comment by nickbearman** [comment]
Still getting the error after ~1hr. Will try later

**Comment by nickbearman** [comment]
After 30 min extra, managed to invite 5 more people, then it timed out on me again. 
Will wait another ~90min or so.

**Comment by nickbearman** [comment]
Just invited the last 5 people (1 first, then 4 in a group) and it all worked fine. I'll be really interested to hear what the limits are and the expected behaviour.

**Comment by nickbearman** [comment]
Really useful reply from EMS Support:

Hi Nick,

I have checked the issue posted, it looks like you are inviting users via email not MXID, so this actually falls under a different rate limit. You can read up on all the different rate limits by checking the configuration manual: https://matrix-org.github.io/synapse/latest/usage/configuration/config_documentation.html#ratelimiting

I believe in your use case, you are hitting rc_third_party_invite. (https://matrix-org.github.io/synapse/latest/usage/configuration/config_documentation.html#rc_third_party_invite)

This option ratelimits 3PID invites (i.e. invites sent to a third-party ID such as an email address or a phone number) based on the account that's sending the invite.

The defaults for Element One on this are a queue maximum of 5, removing 0.0025 from the queue every second. So this translates to, 1 invite via email every 400 seconds after the initial burst of 5 invites.

Best wishes
Element Matrix Services (EMS) Support
https://ems.element.io/
EMS documentation and guides: https://ems-docs.element.io/

**Comment by t3chguy** [comment]
Thanks @nickbearman for surfacing that response here, unfortunately isn't an Element client issue but one of Element One the service provider, we don't track those issues here. Hopefully their response helps you somewhat.
