### ISSUE TITLE
Feature request: /2d6 (roll dice) / coin flipping command

### ISSUE THREAD

**Issue by r4dh4l** [vector-im/element-meta#1835]
**Is your suggestion related to a problem? Please describe.**
Sometimes I would like to have the option to roll some virtual dice or to flip a virtual coin, for example to decide something in a small group by chance casting for the highest pips (btw: Even though I'm not a role player this would make Matrix/Riot an ideal communication platform for RPGs / Role Playing Games maybe?).

**Describe the solution you'd like**
If someone types `/XdY` (while `X` is the amount of dice and `Y` the amount of pips of each die) the chat output would be `* r4dh4l rolls X dice and the result is Z` (while `Z` is the sum of the casted dice).
If someone types `/coin` the output would be `* r4dh4l flips a coin and and <heads or tails> is shown`.

Examples:
- `/2d6` would cause: `* r4dh4l rolls 2 6-sided dice and the result is <something between 2 and 12>`
- `/1d6` would cause: `* r4dh4l rolls 1 6-sided die and the result is <something between 1 and 6>`
- `/2d10` would cause: `* r4dh4l rolls 2 10-sided dice and the result is <something between 2 and 20>`
- `/coin` would cause: `* r4dh4l flips a coin and <heads or tails> is shown`

**Describe alternatives you've considered**
Flipping a real coin or rolling real dices while recording a video and uploading this to a room. ;)

**Comment by richvdh** [comment]
I'm afraid I think it's unlikely this is a feature that we're going to build into any of the Element clients.

**Comment by r4dh4l** [comment]
> I'm afraid I think it's unlikely this is a feature that we're going to build into any of the Element clients.
> richvdh closed this as completed

In other words: "Alea iacta est!" :D
