### ISSUE TITLE
Converge on Explore rooms view

### ISSUE THREAD

**Issue by kittykat** [vector-im/element-meta#184]
Android and iOS should have the same view for Explore Rooms in a Space. They are different at the moment:

- iOS:
  ![ima_fe20532](https://user-images.githubusercontent.com/51663/157213891-3c19ebfa-20db-4d0d-b1c1-996c62c1b570.png)

- Android:
 ![Screenshot_20220308-095525](https://user-images.githubusercontent.com/51663/157213909-5b5810bb-9a00-440c-a37c-573a661b5cf9.png)

## Tasks

- [x] Design input on what the correct view should be
- [x] File an issue to implement the change

**Comment by niquewoodhouse** [comment]
I took a look at the original designs and couldn't see any of the Android content at the top of explore, so in Figma they were always more similar to start with.

<img width="375" alt="Explore space_ iOS@2x" src="https://user-images.githubusercontent.com/1587166/157837168-5d774b37-e055-46c8-acb6-ec68d0ecbf35.png">

<img width="408" alt="Explore space_ And@2x" src="https://user-images.githubusercontent.com/1587166/157837155-3d4ace29-f13a-4162-8a5a-bcd47b3b80cd.png">

Small notes:

- After recent discsussions, its not clear what to do with subspaces, so just leave as they are on each platform for now
- Please on Android, if there's no description/topic for a room, can the `-` not be visible (see below)? It should also be a middle dot, not a dash.

<img width="234" alt="image" src="https://user-images.githubusercontent.com/1587166/157838459-5938b68c-2f9c-4247-89d1-4e444218a6c5.png">

Figma [Android](https://www.figma.com/file/Xu49rK2EdboLFYittPNJYb/Untitled?node-id=2%3A9571) 
No changes to make on iOS

**Comment by kittykat** [comment]
Development issue is at https://github.com/vector-im/element-android/issues/5658
