### ISSUE TITLE
Preview of uploaded BMP image doesn't work (image opens fine)

### ISSUE THREAD

**Issue by opusforlife2** [vector-im/element-meta#1916]
### Steps to reproduce

1. Upload an image to Element-Web in the BMP image format.
2. Look at the timeline after the upload is done.
3. Open the image.
4. Go back to the timeline.

#### What did you expect?

To see a preview of the image in the timeline.

#### What happened instead?

There is just a grey-filled box. Opening the image works fine. I can see what I've uploaded. But the timeline doesn't show a preview/thumbnail of the image.

### Browser information

Firefox 98

### Application version

Element-Web 1.10.7

### Will you send logs?

No

**Comment by SimonBrandner** [comment]
I don't think I can repro :/

**Comment by aaronraimist** [comment]
I can reproduce. When https://people.math.sc.edu/Burkardt/data/bmp/blackbuck.bmp is sent in an unencrypted room, I see:
<img width="675" src="https://user-images.githubusercontent.com/5855073/159129163-bbee9600-f30f-4f76-9e5d-1882378be798.png">
in the timeline. It works fine in the lightbox.

**Comment by t3chguy** [comment]
For me it just gets stuck on the blurhash

![image](https://user-images.githubusercontent.com/2403652/159434460-38d08e9a-4676-478d-949e-389a96d88bd4.png)


But fundamentally this is Synapse not being able to thumbnail this https://matrix-client.matrix.org/_matrix/media/r0/thumbnail/matrix.org/UOupUIqZCoSRCUJTmNLthUgX?width=800&height=600&method=scale

**Comment by clokep** [comment]
> But fundamentally this is Synapse not being able to thumbnail this [matrix-client.matrix.org/_matrix/media/r0/thumbnail/matrix.org/UOupUIqZCoSRCUJTmNLthUgX?width=800&height=600&method=scale](https://matrix-client.matrix.org/_matrix/media/r0/thumbnail/matrix.org/UOupUIqZCoSRCUJTmNLthUgX?width=800&height=600&method=scale)

I filed matrix-org/synapse#15990, I think we can close this since it isn't an Element issue, but a server one.
