### ISSUE TITLE
Create a 'Signup' event on each platform

### ISSUE THREAD

**Issue by novocaine** [vector-im/element-meta#193]
We'd like to be able to create cohorts according to how recently users have signed up. Adding a Signup event would allow us to create D1 / D7 / D30 cohorts in Posthog:

<img width="531" alt="Screenshot 2022-03-04 at 09 57 36" src="https://user-images.githubusercontent.com/57377/156742130-ef7c72c4-44f0-4d5e-85d9-da9e4f51f01a.png">

This wouldn't be present for older users, but given the purpose is mainly to analyse new users that will have raised this event, that's not a blocker.

As suggested by @pixlwave, simply send the event if the analytics opt in comes as part of the registration flow, and otherwise don't send one.

- [x] Web: https://github.com/vector-im/element-web/issues/21925
- [ ] Android: https://github.com/vector-im/element-android/issues/5841
- [x] iOS: https://github.com/vector-im/element-ios/issues/6074

**Comment by daniellekirkwood** [comment]
👀  @ouchadam & @pixlwave

**Comment by ouchadam** [comment]
if we're unable send events before the user opts in, I would imagine setting an account created timestamp on the user properties (and matrix account data) and inferring account creation from that, may need some custom logic in posthog to translate that timestamp to an analytics day

**Comment by pixlwave** [comment]
Can we simply send the event if the analytics opt in comes as part of the registration flow, and otherwise we don't send one? Seems like it would be the simplest approach.

**Comment by novocaine** [comment]
> Can we simply send the event if the analytics opt in comes as part of the registration flow, and otherwise we don't send one? Seems like it would be the simplest approach.

yep, updated the description

**Comment by germain-gg** [comment]
@ouchadam , you can backdate events on PostHog according to their HTTP documentation. I found that the JS sdk does not allow to set that property, but I have created a new issue to extend the library's capabilities https://github.com/PostHog/posthog-js/issues/390

That way we won't need to abuse the event properties in order to track an accurate registration time

**Comment by ouchadam** [comment]
nice find! it looks like we have a similar issue with the android SDK where the ability to mutate the timestamp for historical purposes exists internally but isn't exposed to the main public api 

https://github.com/PostHog/posthog-android/blob/master/posthog/src/main/java/com/posthog/android/payloads/BasePayload.java#L181

**Comment by germain-gg** [comment]
Has been completed on all platforms. closing.
