### ISSUE TITLE
[Story] Easily show/hide formatting buttons

### ISSUE THREAD

**Issue by langleyd** [vector-im/element-meta#1939]
### Description

* As a user
* I want to quickly show/hide the formatting options of Rich Text Mode
* so that I can add formatting and then hide the tools when I'm done.

# Size estimate

M

# Dependencies

- https://github.com/vector-im/element-meta/issues/1936

# Acceptance criteria

- Enable rich text formatting buttons from the action bottom sheet
- Quickly hide rich text formatting options with the X button

# Out of scope

- Enter/Exit full-screen mode from the rich text editor https://github.com/vector-im/element-meta/issues/1973

# Subtasks

```[tasklist]
### Android
```

```[tasklist]
### iOS
```

```[tasklist]
### Other
```

**Comment by jonnyandrew** [comment]
Closing as with the new designs this cannot be done independently from #1937. I've added the AC to #1937 instead.
