### ISSUE TITLE
Load the thread list using server-side sorting and pagination

### ISSUE THREAD

**Issue by daniellekirkwood** [vector-im/element-meta#195]
We currently load the entire thread list without pagination and sort it on the client so that we can sort by last-replied-to.

Add support for that sort to the server query and load the list using pagination.

- [x] Server side: matrix-org/synapse#13921
- [x] Web: https://github.com/vector-im/element-web/issues/21877
- [x] iOS: https://github.com/vector-im/element-ios/issues/6059
- [x] Android: https://github.com/vector-im/element-android/issues/5819

**Comment by clokep** [comment]
[MSC3856](https://github.com/matrix-org/matrix-spec-proposals/pull/3856): Threads List API was written to solve this issue.

**Comment by clokep** [comment]
See #152 for an earlier incarnation of this issue.

**Comment by daniellekirkwood** [comment]
All sub-tasks are marked as closed so I'm closing this issue...
