### ISSUE TITLE
No indication that user list is loading when inviting to room

### ISSUE THREAD

**Issue by kittykat** [vector-im/element-meta#1950]
### Steps to reproduce

1. Go to room -> room detail -> "Invite people"
2. Start typing username
3. Click "search"

#### What did you expect?
Instantly see results

#### What happened instead?
First time it took a minute to see the exact match

### Your phone model

Pixel 6a

### Operating system version

Graphene OS

### Application version and app store

Nightly

### Homeserver

matrix.org

### Will you send logs?

No

### Are you willing to provide a PR?

No
```[tasklist]
### Tasks
- [x] iOS: Add loading indicator to the user search screen
- [ ] https://github.com/element-hq/element-x-android/issues/2172
```

**Comment by kittykat** [comment]
Also do not get told that the search can't happen when in airplane mode/offline

**Comment by amshakal** [comment]
We should probably have a spinner if results are loading

**Comment by manuroe** [comment]
iOS spinner:

https://github.com/element-hq/element-meta/assets/8418515/d8f3b1ce-15f5-4a52-97c8-b1575757499e

**Comment by ganfra** [comment]
So we don't show the spinner before we have the minimal number of chars in the query (3 at the moment)?
Also  if the query is a userId, we are showing a fake result, but we are also searching for more results. So should the spinner be shown in those cases too?

**Comment by amshakal** [comment]
I dont think we show spinner on iOS before 3 characters as well, so we can use the same pattern on android. I think if are searching for more results, we should show the spinner.

**Comment by claell** [comment]
After implementing #2172, does this still need other implementations, or can this be closed?

**Comment by manuroe** [comment]
Sure, we can can close it.
