### ISSUE TITLE
[Story] EC in EX: Create a call

### ISSUE THREAD

**Issue by manuroe** [vector-im/element-meta#1956]
### Description

* As a user
* I want to initiate a call from a room
* so that I can talk to members in the room.

Reminder: DM and group call are treated equally as a group call in the first iteration of EC in EX.

# Size estimate

S

# Dependencies

* Some of https://github.com/vector-im/element-meta/issues/1954 but we can start building the UI without having the full webview + widget API integration

# Acceptance criteria

* The user should be able to initiate a call from within a room

# Out of scope

* Initiate a call from the room details screen. This should make a call in the DM room -> Not in MVP. There are edge cases like if the DM does not exist yet.
* Multiple calls in a single room
* No limitation on power level
* The call will always start as video call

# Subtasks

```[tasklist]
### To Be Defined - Update the acceptance criteria when a solution is found
- [x] Is it possible to let the user decide to initiate a video or an audio call ?
- [x] Define a min power level to initiate a call ?
```

```[tasklist]
### Android
```

```[tasklist]
### iOS
```

**Comment by toger5** [comment]
Can this be closed already?

**Comment by jmartinesp** [comment]
I believe everything here is done (sorry for the missing issues in Android/iOS to track the progress).
