### ISSUE TITLE
[Story] EC in EX: In Call

### ISSUE THREAD

**Issue by manuroe** [vector-im/element-meta#1958]
### Description

* As a user
* I want to ... enjoy my call experience

Most of call interactions (audio & video mute, call settings, etc) will happen within Element Call. This user story is more about handling a perfect integration of Element call into native mobile EX apps.

# Size estimate

S/M/L

# Dependencies

* None

# Acceptance criteria

* Element Call uses the user name and avatar
* Current music playback is pause when joining a call and resumed after leaving the call
* Permissions to access mic and camera are asked only on the first call
* The user can change the inbound audio volume 
* The user can switch camera
* The user can switch mic
* The user can switch audio output
* The call stays up when app is in bg. TBD what about audio & video?
* The call stays up when the device is locked. TBD what about audio & video?
* The user can come back to the app and use it normally during the call. They should be able to come back to the call with a single action. TBD: Do we want "back to the app"? Should we have PIP?

# Out of scope

* Screen sharing
* Call control like muting audio and video is only while Element Call is fullscreen. We can do nothing without callkit when the app is in bg or the device locked

# Subtasks

```[tasklist]
### Android
```

```[tasklist]
### iOS
```

```[tasklist]
### Other
```

**Comment by jmartinesp** [comment]
This was implemented on both platforms, except for PiP.
