### ISSUE TITLE
[Story] EC in EX: Leave a call

### ISSUE THREAD

**Issue by manuroe** [vector-im/element-meta#1959]
### Description

* As a user 
* I want to leave a call

# Size estimate

S/M/L

# Dependencies

* None

# Acceptance criteria

* The user can leave the call from Element Call screen. The EC screen is dismissed. The user is back to the app
* The EC screen is dismissed if the call is terminated elsewhere, forcing everyone to leave the call

# Out of scope

* We cannot leave outside of Element Call, especially when the EX is in bg or device locked 

# Subtasks

```[tasklist]
### Android
```

```[tasklist]
### iOS
```

```[tasklist]
### Other
```

**Comment by jmartinesp** [comment]
AFAIK both apps can hang up and will exit the call screen if a hang up message is received.
