### ISSUE TITLE
[Story] EC in EX: Terminate a call

### ISSUE THREAD

**Issue by manuroe** [vector-im/element-meta#1960]
### Description

* As a user (or call creator or room admin TBD)
* I want to terminate a call
* So that it does not appear anymore in the app as an ongoing call

# Size estimate

S/M/L

# Dependencies

* None

# Acceptance criteria

* The user can kill the call from EC
* The user can kill and remove an ongoing call from the EX room screen
* When a call is terminated, remaining users leave EC (part of #1959) 

# Out of scope

* Terminating the call outside of the app

# Subtasks

```[tasklist]
### Android
```

```[tasklist]
### iOS
```

```[tasklist]
### Other
```

**Comment by jmartinesp** [comment]
Did we implement this? AFAIK a call ends when there's no one else in it anymore, but it doesn't have a 'kill call' option?
