### ISSUE TITLE
Threads: Support Read receipts and read markers

### ISSUE THREAD

**Issue by daniellekirkwood** [vector-im/element-meta#197]
In order to make [improvements to the Notification](https://github.com/vector-im/element-meta/issues/196) solution in the [Fast Follow Epic](https://github.com/vector-im/element-meta/issues/187) we need read receipts and read markers in the Threads timeline...

**Comment by clokep** [comment]
I think due to implementation decisions this overlaps extensively with #196.

**Comment by daniellekirkwood** [comment]
as per @clokep's comment this can be closed.
