### ISSUE TITLE
A room that has predominantly images doesn't clear unread marker

### ISSUE THREAD

**Issue by amshakal** [vector-im/element-meta#1977]
A room that has predominantly images doesn't clear unread marker.

**Comment by amshakal** [comment]
https://github.com/vector-im/element-meta/issues/1043#issuecomment-1662275746

**Comment by stefanceriu** [comment]
That doesn't seem to be the problem. The last message in the timeline is edited so the last **event** isn't visible and the app can't mark it as seen. This is a known issue and already tracked in https://github.com/vector-im/element-x-ios/issues/1479
