### ISSUE TITLE
[Story] Device management with OIDC

### ISSUE THREAD

**Issue by manuroe** [vector-im/element-meta#1979]
### Description

* As a user
* I want to open the device management webapp
* So that I can manage my device

### Acceptance criteria

- The user can manage their device within web pages provided by OIDC
- The user can open the management web url from the app settings

### Size estimate

None

### Dependencies

- TBD

### Preconditions

- TBD

### Out of scope

- Device management in EX is limited to users on matrix servers supporting OIDC. matrix.org is out of scope for September

### Open questions

- Embedded web view or native browser?

### Subtasks

```[tasklist]
### Android
- [ ] https://github.com/vector-im/element-x-android/issues/1114
```

```[tasklist]
### iOS
- [ ] https://github.com/vector-im/element-x-ios/pull/1541
```

```[tasklist]
### Rust
```

**Comment by hughns** [comment]
With regards to embedded web view or native browser there are notes been collated in here: https://docs.google.com/document/d/1Jbt4p7blX5RZwO5MyvjDCFFjXUc8UnS7TFzgbrUeaHQ/edit

**Comment by manuroe** [comment]
It is now available on both apps with the `Manage account` button in settings
