### ISSUE TITLE
Synapse Admin API: Last seen timestamp also in list users endpoint

### ISSUE THREAD

**Issue by yncyrydybyl** [vector-im/element-meta#1982]
#### What would you like to do?

Description

As a admin I want to see when a user was active the last time without looking up every device.

With the [User List Accounts](https://matrix-org.github.io/synapse/latest/admin_api/user_admin_api.html#list-accounts) endpoint you can get a list of all users. 
How much work would it be to add the last_seen_ts field from the 
[List all devices](https://matrix-org.github.io/synapse/latest/admin_api/user_admin_api.html#list-all-devices) Endpoint to the above API and take the latest last_seen_ts value from all devices registered to the user?

**Comment by daniellekirkwood** [comment]
<table>
<tr><td> <img width="550" alt="Screenshot 2023-08-14 at 12 34 24" src="https://github.com/vector-im/element-meta/assets/89144281/06bc855f-54e2-4fe2-9746-52f2ff9e62b0">
</table>




@yncyrydybyl Already done :) 👍

**Comment by pmaier1** [comment]
> @yncyrydybyl Already done :) 👍

I think this isn't what they are asking for. They want to see the _latest_ `last_seen_ts` from a particular device in the response of the [List Accounts](https://matrix-org.github.io/synapse/latest/admin_api/user_admin_api.html#list-accounts) endpoint.

**Comment by daniellekirkwood** [comment]
> take the latest last_seen_ts value from all devices registered to the user

This is how I may have misinterpreted the ask. I believe @yncyrydybyl was asking for "when a user was active the last time without looking up every device" which we have in the profile. 

We also have a list of devices in the profile and _could_ add the last seen TS to that view fairly easily (I don't know how this works with MAS etc.) Is that what this issue now represents?

Could we get designs into the description of this issue? I'm a little lost as to what the Admin Console folks will need to work on vs the backend team :)

**Comment by daniellekirkwood** [comment]
<img width="640" alt="Screenshot 2023-08-31 at 18 33 48" src="https://github.com/vector-im/element-meta/assets/89144281/cf420f91-0829-4526-895c-e75e40047062">

This is the design we were given --

**Comment by daniellekirkwood** [comment]
<img width="515" alt="Screenshot 2023-08-31 at 18 37 19" src="https://github.com/vector-im/element-meta/assets/89144281/dbbdb2e2-b95e-4a16-98a8-48c15c677a13">

This is what we have in the product (close as we could get to the design). 

Let me know where I've missed a beat in the original ask! (other than the need to make that TS a time-stamp!)

**Comment by MatMaul** [comment]
@daniellekirkwood I think you are talking about having it in the ESS admin UI, while I think this request is for the Synapse admin API I believe.

**Comment by MatMaul** [comment]
@daniellekirkwood I think you are talking about having it in the console admin UI, while I think this request is for the Synapse admin API I believe.

For the UI you can then use that to have this value directly in the list of users instead of only the user details. I am also adding a sort parameter, so you will also be able to use that.

**Comment by pmaier1** [comment]
> this request is for the Synapse admin API I believe.

Yes, this is API only. No changes in admin console needed. With MAS, this needs to be implemented as well. But this ask is for the Synapse admin API today.

**Comment by daniellekirkwood** [comment]
Thank you :D I'm still learning - appreciate the help!
