### ISSUE TITLE
Revise and improve Key sharing and forwarding

### ISSUE THREAD

**Issue by BillCarsonFr** [vector-im/element-meta#199]
## Taking advantage of Key Sharing, Withheld code and Keybackup

The mechanism to recover from unable to decrypt errors or to access e2E history have greatly evolved since the begining of matrix.

 - The initial [Key Sharing mechanism](https://docs.google.com/document/d/1m4gQkcnJkxNuBmb5NoFCIadIY-DyqqNAS3lloE73BlQ/edit#)
- Introduction of [megolm server backup](https://github.com/uhoreg/matrix-doc/blob/e2e_backup/proposals/1219-storing-megolm-keys-serverside.md)
- Introduction of [withheld codes](https://github.com/uhoreg/matrix-doc/blob/reporting_no_key/proposals/2399-reporting-no-key-sent.md)
- Verification and Cross-Signing also open new fields for [sharing strategies](https://github.com/vector-im/element-meta/issues/115)

It's now time to re-define the reference algorithms for key sharing and key forwarding using all these new functionnalities together.

# Development Tasks

## Documentation \([WIP DOC](https://www.figma.com/file/RaWtCR9VZ2NC1v0lcDyumN/Key-Sharing-%2F-Forwarding-%2F-Requesting?node-id=535%3A742)\)

   - \[x\] Reference Flowchart for initial key sharing [Dot Graph](https://edotor.net/?engine=dot?engine=dot?engine=dot?engine=dot?engine=dot?engine=dot#%0Adigraph%20%7B%0A%0A%20%20%20rankdir%20%3D%20TB%3B%0A%0A%20%20%20%20%23%20Defaults%0A%20%20%20%20node%20%5Bshape%3D%22box%22%5D%3B%0A%0A%20%20%20%20%23%20Node%20definitions%0A%20%20%20%20onSend%20%5Blabel%3D%22On%20Send%20message%22%5D%0A%20%20%20%20rotate1%20%5Blabel%3D%22Rotate%20megolm%20session%20if%20needed.%5Cn%5Cl%20Session%20should%20be%20rotated%20if%3A%20%5Cl-%20Session%20is%20too%20old%20(1week)%5Cl-%20More%20than%20100%20messages%20has%20been%20sent%5Cl-%20Some%20devices%20that%20this%20session%20was%20previously%20shared%20with%20left%20the%20room%20%5C(or%20are%20not%20allowed%20anymore%5C)%5Cl-%20The%20room%20history%20visibility%20setting%20did%20change%5Cl%22%5D%0A%20%20%20%20computeUsersInRoom%20%5Blabel%3D%22Get%20list%20of%20users%20in%20room.%5Cn%20If%20encryption%20to%20invited%20users%20is%20enabled%20%5C(SDK%20config%5C)%5Cnand%20room%20history%20visibility%20is%20not%20joined%2C%20include%20invited%20users%20as%20well%5Cn%5C(do%20keys%2Fquery%20if%20needed%2C%20ok%20to%20use%20cache%5C)%20%22%5D%0A%20%20%20%20computeDevicesInRoom%20%5Blabel%3D%22Compute%20list%20of%20allowed%20devices%20in%20room.%5CnSplit%20the%20list%20in%20allowed%2Fnot%20allowed%20devices.%5CnRemember%20the%20list%20%5C(w0%5C)%20of%20devices%20not%20allowed%20eg.%20blacklisted%20%5Cnor%20unverified%20%5C(if%20crypto%20config%20set%20to%20not%20sent%20to%20those%5C).%5Cn%20Withheld%20code%20will%20be%20sent%20later.%22%5D%0A%20%20%20%20markIntendedShared%20%5Blabel%3D%22Mark%20megolm%20session%5Cnas%20intented%20to%20be%20shared%5Cn%20at%20this%20index%20with%5Cn%20all%20devices%20in%20list%22%5D%0A%20%20%20%20getOrCreateOutboundSession%20%5Blabel%3D%22Get%20existing%20or%20create%20outbound%20session%20for%20room.%5Cn%20%5C(created%20session%20should%20be%20persisted%20and%20survive%20app%20lifeccyle%5C)%22%5D%0A%20%20%20%20startSharingSession%20%5Blabel%3D%22Start%20Session%20Sharing%20for%20room%5Cn%20Should%20aquire%20a%20mutex%20lock%20per%20room%22%5D%0A%20%20%20%20releaseLock%20%5Blabel%3D%22Release%20the%20mutex%20lock%20on%20that%20room%22%5D%0A%20%20%20%20markShared%20%5Blabel%3D%22On%20success%2C%5Cnmark%20megolm%20session%20as%20shared%5Cn%20at%20this%20index%20the%20devices%20in%20batch%22%5D%0A%20%20%20%20keyClaimDefault%20%5Blabel%3D%22%2Fkeys%2Fclaim%20otk%20for%20devices.%5Cn%20Do%20this%20by%20chunk%20of%20100%20devices.%5CnIt's%20worth%20batching%20up%20devices%5Cn%20for%20the%20same%20users%20and%20on%20same%20server%22%5D%0A%20%20%20%20isKeyAlreadyShared%20%5Blabel%3D%22Filter%20out%20allowed%20devices%20with%20witch%5Cn%20the%20current%20outbound%20session%20was%5Cn%20already%20shared%20%5C(actually%20shared%20not%20just%20intended%5C)%22%5D%0A%20%20%20%20createOlm2%20%5Blabel%3D%22Create%20new%20Olm%20Sessions%5Cn%20using%20found%20OTK%22%5D%0A%20%20%20%20markAsNoOlm%20%5Blabel%3D%22Add%20device%20to%20the%20list%5C(w1%5C)%5Cnof%20devices%20without%20olm%5Cn%5C(a%20withheld%20code%20will%20be%20sent%20at%20the%20end%5C)%22%5D%0A%20%20%20%20encryptKey%20%5Blabel%3D%22Encrypt%20megolm%20keys%20%5Cnby%20100%20device%20batches%20using%20olm%20session.%5CnEncryption%20is%20slow%20and%20can%20be%5Cnparallelized%20for%20better%20performances%22%5D%0A%20%20%20%20sendRoomKey%20%5Blabel%3D%22Send%20encrypted%20m.room*key%20for%20the%20batch%5Cn%5C(encrypted%20to*device%20m.room*key%5C)%5CnClients%20should%20have%20basic%5Cn%20retry%20mecahnism%20for%20shaky%20connections%22%5D%0A%20%20%20%20db%20%5Blabel%3D%22%5CnStorage%5Cn%5CnFor%20each%20megolm%20session%20store%3A%5Cl-What%20%5Buser*id%20%7C%20device%20%7C%20sender*key%5D%20it%20was%20shared%20with%20%5C(and%20what%20index%5C)%5Cl-What%20%5Buser*id%20%7C%20device%20%7C%20sender*key%5D%20it%20was%20intended%20to%20be%20shared%20with%20%5C(and%20what%20index%5C)%5Cl-What%20%5Buser*id%20%7C%20device%20%7C%20sender*key%5D%20it%20has%20sent%20a%20withheld%20code%5Cl-When%20the%20session%20was%20created%5Cl-How%20many%20messages%20were%20encrypted%20with%20it%5Cl%22%5D%0A%20%20%20%20claimChunkCompletes%20%5Blabel%3D%22All%20chunk%20completed%22%5D%0A%20%20%20%20keyShareDone%20%5Blabel%3D%22Key%20share%20done%20for%20all%20slices%22%5D%0A%20%20%20%20sendEvent%20%5Blabel%3D%22Send%20event%20to%20room%22%5D%0A%20%20%20%20sendWithHeldForDevicesInRoom%20%5Blabel%3D%22Send%20withheld%20messages%5Cnfor%20devices%20that%20the%20session%5Cnis%20deliberatly%20withheld%20from%20%5C(by%20batch%20of%20100%5C)%5CnSee%20w0%20from%20compute%20devices%20in%20room%20%5C(m.unverified%20or%20m.blacklisted%5C)%5Cn%2C%20and%20w1%20from%20key%2Fclaim%20%5C(m.no*olm%5C)%5CnRemember%20on%20success%2C%5Cndo%20not%20resend%20withheld%20code%20if%20already%20done%22%5D%0A%0A%20%20%20%20markForBackup%20%5Blabel%3D%22Notify%20backup%20service%5Cn%20that%20a%20new%20key%20should%20be%20uploaded%22%5D%0A%0A%20%20%20%20commentRateLimit%20%5Blabel%3D%22Key%2FClaim%20calls%20should%20be%20rate%20limited%5Cnto%20avoid%20claiming%20keys%20on%20dead%20devices%5Cnfor%20each%20message%20sending%22%5D%0A%0A%20%20%20%20%23%20Vertex%0A%20%20%20%20onSend%20-%3E%20startSharingSession%3B%0A%20%20%20%20startSharingSession%20-%3E%20computeUsersInRoom%3B%0A%20%20%20%20computeUsersInRoom%20-%3E%20computeDevicesInRoom%3B%0A%20%20%20%20computeDevicesInRoom%20-%3E%20getOrCreateOutboundSession%3B%0A%20%20%20%20getOrCreateOutboundSession%20-%3E%20rotate1%3B%0A%20%20%20%20rotate1%20-%3E%20isKeyAlreadyShared%3B%0A%20%20%20%20isKeyAlreadyShared%20-%3E%20markIntendedShared%20%5Blabel%3D%22filtered%20list%22%5D%0A%20%20%20%20markIntendedShared%20-%3E%20keyClaimDefault%3B%0A%0A%20%20%20%20rotate1%20-%3E%20markForBackup%20%5Blabel%3D%22On%20new%20session%20created%22%2C%20style%3Ddashed%2C%20arrowhead%3Dnone%5D%0A%0A%20%20%20%20subgraph%20cluster0%20%7B%0A%20%20%20%20%20%20%20%20label%20%3D%22Share%20Megolm%20Key%22%0A%20%20%20%20%20%20%20%20encryptKey%20-%3E%20sendRoomKey%0A%20%20%20%20%20%20%20%20sendRoomKey%20-%3E%20markShared%0A%0A%20%20%20%20markShared%20-%3E%20keyShareDone%0A%20%20%20%20%7D%0A%0A%20%20%20%20subgraph%20cluster1%20%7B%0A%20%20%20%20%20%20%20%20label%20%3D%22Create%20missing%20olm%20sessions%22%0A%20%20%20%20%20%20%20%20keyClaimDefault%20-%3E%20markAsNoOlm%20%5Blabel%3D%22On%20Failure%5Cn%5C(no%20OTK%20or%20timeout%5C)%22%5D%0A%20%20%20%20%20%20%20%20keyClaimDefault%20-%3E%20createOlm2%20%5Blabel%3D%22Devices%20with%20otk%22%5D%0A%20%20%20%20%20%20%20%20createOlm2%20-%3E%20claimChunkCompletes%0A%20%20%20%20%20%20%20%20markAsNoOlm%20-%3E%20claimChunkCompletes%0A%20%20%20%20%20%20%20%20keyClaimDefault%20-%3E%20commentRateLimit%20%5Bstyle%3Ddashed%2C%20arrowhead%3Dnone%2C%20color%3Dlightgray%5D%0A%20%20%20%20%7D%0A%0A%20%20%20%20claimChunkCompletes%20-%3E%20encryptKey%0A%0A%20%20%20%20keyShareDone%20-%3E%20sendWithHeldForDevicesInRoom%0A%20%20%20%20sendWithHeldForDevicesInRoom%20-%3E%20releaseLock%0A%20%20%20%20releaseLock%20-%3E%20sendEvent%0A%0A%20%20%20%20%23%20Node%20Styling%0A%20%20%20%20onSend%20%5Bshape%3Dbox%2Cstyle%3Dfilled%2C%20fillcolor%3Dlightblue%5D%3B%0A%20%20%20%20startSharingSession%20%5Bstyle%3Dfilled%2C%20fillcolor%3Dorange%5D%3B%0A%20%20%20%20releaseLock%20%5Bstyle%3Dfilled%2C%20fillcolor%3Dorange%5D%3B%0A%20%20%20%20markIntendedShared%3B%0A%20%20%20%20rotate1%3B%0A%20%20%20%20sendWithHeldForDevicesInRoom%20%5Bstyle%3Dfilled%2C%20fillcolor%3D%22%23D27B2C%22%5D%3B%0A%20%20%20%20isKeyAlreadyShared%3B%0A%20%20%20%20db%20%5Bshape%3Dcylinder%2C%20style%3Dfilled%2C%20fillcolor%3Dyellow%20%5D%0A%20%20%20%20sendEvent%20%5Bshape%3Dbox%2Cstyle%3Dfilled%2C%20fillcolor%3Dgreen%5D%3B%0A%20%20%20%20commentRateLimit%20%5Bstyle%3Dfilled%2C%20fillcolor%3Dlightgray%2C%20shape%3Dnone%5D%0A%7D%0A)
   - [Key forwarding](https://edotor.net/?engine=dot?engine=dot?engine=dot?engine=dot?engine=dot#%0Adigraph%7B%0A%0A%20%20%20rankdir%20%3D%20TB%3B%0A%20%20%20label%20%3D%20%22Key%20Forwarding%5Cn%5Cn%22%3B%0A%20%20%20labelloc%20%3D%20%22t%22%3B%0A%0A%20%20%20%20start%20%5Blabel%3D%22m.room_key_request%5Cn%20received%22%5D%0A%20%20%20%20isSelfDevice%20%5Blabel%3D%22Is%20it%20one%20of%20our%20device%22%5D%0A%20%20%20%20isBlackListed%20%5Blabel%3D%22Is%20it%20blacklisted%3F%22%5D%0A%20%20%20%20isSelfDeviceVerified%20%5Blabel%3D%22Is%20it%20verified%3F%22%5D%0A%20%20%20%20isKeyKnown%20%5Blabel%3D%22Is%20the%20key%20known%20locally%3F%22%5D%0A%20%20%20%20wh_unvailable%20%5Blabel%3D%22Send%20room_key.withheld%5Cn%20reason%20m.unavailable%22%5D%0A%20%20%20%20wh_blacklisted%20%5Blabel%3D%22Send%20room_key.withheld%5Cn%20reason%20m.blacklisted%22%5D%0A%20%20%20%20wh_no_olm%20%5Blabel%3D%22Send%20room_key.withheld%5Cn%20reason%20m.no_olm%22%5D%0A%20%20%20%20wh_unauthorised%20%5Blabel%3D%22Send%20room_key.withheld%5Cn%20reason%20m.unauthorized%20if%20not%20one%20of%20our%20devices%5Cn%20if%20one%20of%20our%20devices%20then%20m.unverified%22%5D%0A%20%20%20%20ensure_olm1%20%5Blabel%3D%22Ensure%20Olm%20session%5Cn%20with%20device%22%5D%0A%20%20%20%20ensure_olm2%20%5Blabel%3D%22Ensure%20Olm%20session%5Cn%20with%20device%22%5D%0A%20%20%20%20was_shared%20%5Blabel%3D%22Was%20the%20session%20shared%20previously%5Cn%20with%20this%20userId%7CdeviceId%7Csender_key%22%5D%0A%20%20%20%20db%20%5Blabel%3D%22Crypto%5Cndatabase%22%5D%0A%20%20%20%20end_forward_early%20%5Blabel%3D%22Forward%20key%5Cnfrom%20the%20earliest%20known%20index.%5Cn(encrypted%20m.forwarded_room_key)%22%5D%0A%20%20%20%20end_forward_initial%20%5Blabel%3D%22Forward%20key%5Cnfrom%20the%20index%20it%20was%20shared%20initialy.%5Cn%5C(encrypted%20m.forwarded_room_key%5C)%22%5D%0A%0A%0A%0A%20%20%20%20%23%20To%20refactor%20nodes%2C%20place%20the%20cursor%20left%20to%20a%20node%20name%0A%20%20%20%20start%20-%3E%20isSelfDevice%0A%20%20%20%20isSelfDevice%20-%3E%20isSelfDeviceVerified%20%5Blabel%3D%22Yes%22%20color%3Dgreen%5D%3B%0A%20%20%20%20isSelfDevice%20-%3E%20isBlackListed%20%5Blabel%3D%22No%22%5D%3B%0A%20%20%20%20isSelfDeviceVerified%20-%3E%20isKeyKnown%20%5Blabel%3D%22Yes%22%20color%3Dgreen%5D%3B%0A%20%20%20%20isSelfDeviceVerified%20-%3E%20was_shared%20%5Blabel%3D%22No%22%5D%0A%20%20%20%20isKeyKnown%20-%3E%20ensure_olm1%20%5Blabel%3D%22Yes%22%20color%3Dgreen%5D%0A%20%20%20%20isKeyKnown%20-%3E%20wh_unvailable%20%5Blabel%3D%22No%22%5D%3B%0A%20%20%20%20isBlackListed%20-%3E%20was_shared%20%5Blabel%3D%22No%22%5D%3B%0A%20%20%20%20isBlackListed%20-%3E%20wh_blacklisted%20%5Blabel%3D%22Yes%22%5D%3B%0A%20%20%20%20was_shared%20-%3E%20db%20%5Bstyle%3Ddashed%2C%20arrowhead%3Dnone%5D%3B%0A%20%20%20%20was_shared%20-%3E%20ensure_olm2%20%5Blabel%3D%22Yes%22%20color%3Dgreen%5D%3B%0A%20%20%20%20was_shared%20-%3E%20wh_unauthorised%20%5Blabel%3D%22No%22%5D%0A%20%20%20%20ensure_olm1%20-%3E%20end_forward_early%20%5Blabel%3D%22Success%22%5D%3B%0A%20%20%20%20ensure_olm1%20-%3E%20wh_no_olm%20%5Blabel%3D%22Failure%22%5D%3B%0A%20%20%20%20ensure_olm2%20-%3E%20wh_no_olm%20%5Blabel%3D%22Failure%22%5D%3B%0A%20%20%20%20ensure_olm2%20-%3E%20end_forward_initial%20%5Blabel%3D%22Success%22%5D%3B%0A%0A%20%20%20%20%23%20Get%20completion%20when%20assigning%20a%20shape%20or%20color%0A%20%20%20%20start%20%5Bshape%3Degg%2C%20style%3Dfilled%2C%20fillcolor%3Dyellow%5D%3B%0A%20%20%20%20isSelfDevice%20%5Bshape%3Dtrapezium%5D%3B%0A%20%20%20%20isBlackListed%20%5Bshape%3Dtrapezium%5D%3B%0A%20%20%20%20isSelfDeviceVerified%20%5Bshape%3Dtrapezium%5D%3B%0A%20%20%20%20isKeyKnown%20%5Bshape%3Dtrapezium%5D%3B%0A%20%20%20%20wh_unvailable%20%5Bshape%3Dbox%2C%20style%3Dfilled%2C%20fillcolor%3D%22%23D27B2C%22%5D%3B%0A%20%20%20%20wh_blacklisted%20%5Bshape%3Dbox%2C%20style%3Dfilled%2C%20fillcolor%3D%22%23D27B2C%22%5D%3B%0A%20%20%20%20wh_unauthorised%20%5Bshape%3Dbox%2C%20style%3Dfilled%2C%20fillcolor%3D%22%23D27B2C%22%5D%3B%0A%20%20%20%20wh_no_olm%20%5Bshape%3Dbox%2C%20style%3Dfilled%2C%20fillcolor%3D%22%23D27B2C%22%5D%3B%0A%20%20%20%20ensure_olm1%20%5Bshape%3Dparallelogram%2C%20style%3Dfilled%2C%20fillcolor%3Dlightblue%5D%3B%0A%20%20%20%20ensure_olm2%20%5Bshape%3Dparallelogram%2C%20style%3Dfilled%2C%20fillcolor%3Dlightblue%5D%3B%0A%20%20%20%20was_shared%20%5Bshape%3Dtrapezium%5D%0A%20%20%20%20db%20%5Bshape%3Dcylinder%2C%20style%3Dfilled%2C%20fillcolor%3Dyellow%20%5D%0A%20%20%20%20end_forward_early%20%5Bshape%3Dbox%2C%20style%3Dfilled%2C%20fillcolor%3Dgreen%5D%0A%20%20%20%20end_forward_initial%20%5Bshape%3Dbox%2C%20style%3Dfilled%2C%20fillcolor%3Dgreen%5D%0A%0A%7D%0A)
   - \[x\] Reference Flowchart for outgoing key requests [figma](https://www.figma.com/file/RaWtCR9VZ2NC1v0lcDyumN/Key-Sharing-%2F-Forwarding-%2F-Requesting?node-id=484%3A115)
   - \[ \] Reference Flowchart for incoming key requests
   - \[ \] Convert all charts to DOT graph description language

## Spec Work

  - \[x\] New MSC to add `from_device` and `request_id` to withheld messages [3735](https://github.com/matrix-org/matrix-spec-proposals/pull/3735)

## Revise existing SDK implementation and ensure they implement the defined reference algorithm, add tests.

  - \[ \] Update SDKs to implement reference flowchart for key forwarding
      - \[ \] **Web**
          - probable changes
              - \[ \] Do not send key request on initial sync
              - \[x\] https://github.com/vector-im/element-web/issues/21026
              - \[ \] Keep track and store outcome of outgoing room key request [MSC3735](https://github.com/matrix-org/matrix-spec-proposals/pull/3735)
              - \[ \] Ensure that keys that was initialy shared with own unverified device are re-shared
              - \[x\] https://github.com/vector-im/element-web/issues/12851
      - \[ \] **IOS**
          - \[ \] https://github.com/matrix-org/matrix-ios-sdk/issues/1354
          - \[ \] Align to ref chart
      - \[x\] **Android** https://github.com/vector-im/element-android/issues/5494
          - \[x\] Align to ref chart
          - \[x\] Query key backup before sending to\_device
          - \[x\] Keep track and store outcome of outgoing key

**Comment by richvdh** [comment]
no longer relevant, apparently.
