### ISSUE TITLE
EX should not try to show history in for a new member of an existing encrypted room

### ISSUE THREAD

**Issue by pmaier1** [vector-im/element-meta#1990]
### Story

Currently there is no room history key sharing functionality available in EX. This feature will be added at a later point in time. Therefore the app should not attempt to show historical messages when a new user joins a room.

## Steps to reproduce
1. Alice creates an e2ee room
2. Normal room activity takes place
3. Bob joins the room (simple join or invite)

## Expected behavior
- Bob gets informed that he cannot read history in this room (similar to how the missing key backup functionality is handled)

## Actual behavior 
- Bob receives historical messages but all of them are UTDs (which is expected as he cannot get the keys for them)

## Related
- https://github.com/vector-im/element-x-ios/issues/1240

@manuroe @VolkerJunginger

**Comment by ara4n** [comment]
N.B. that you might still have the keys (e.g. if the non-EX client who invited you sent you the keys preemptively), so you should only hide the messages if empirically you don't have keys to decrypt them.

**Comment by pmaier1** [comment]
This is being handled as part of the current work on hiding expected UTDs https://github.com/element-hq/element-meta/issues/2312.
