### ISSUE TITLE
Remove woke "terminology" list

### ISSUE THREAD

**Issue by du82** [vector-im/element-meta#2008]
Element is about free speech, not woke censorship. Therefore, the wiki page on "inclusive" terminology (which is just censoring things that we tech people have been using for decades) should be removed.

The page I'm referencing: https://github.com/vector-im/element-meta/wiki/Terminology:-Word-list#words-matter

**Comment by du82** [comment]
I'm asian and I even think the "they/them" and "BiPOC" terminology is dumb

**Comment by daniellekirkwood** [comment]
We chose our terminology with care, and published this page to help others new to the project understand how we aim to communicate in order to foster an inclusive environment.

We don't intend to review our terminology guidelines at this stage and so I am closing this issue.
