### ISSUE TITLE
Converge on Spaces menu in left panel

### ISSUE THREAD

**Issue by kittykat** [vector-im/element-meta#205]
Android and iOS should have the same view for Explore Rooms in a Space. They are different at the moment:

- Menu items should be the same
- Strings should be the same
- Capitalisation should be the same
- Icons should be the same

I personally like having the "invite" shortcut there as that's my most common action when testing.

- iOS:
  ![ima_d810d9a](https://user-images.githubusercontent.com/51663/157431083-cda38607-c528-497c-9846-366c617f2858.png)
- Android:
  ![Screenshot_20220308-163330](https://user-images.githubusercontent.com/51663/157431084-67e463ef-6d14-43e1-8a58-80427d687e45.png)

## Tasks

- [x] Design input on what the correct view should be
- [x] File issue(s) to implement the change in Android and/or iOS repos

**Comment by niquewoodhouse** [comment]
@fedrunov can I check please, I think you've already had an issue that amends

- Leave space to be Leave
- Explore rooms to use a different icon
- List members to be Members

Is that right? Thanks

**Comment by fedrunov** [comment]
@niquewoodhouse yes, here it is:

https://github.com/vector-im/element-android/issues/5270

**Comment by niquewoodhouse** [comment]
**Android amends:**

- Alter ordering of list to be:
  - Invite people
  - Explore rooms
  - Members
  - Settings
  - Add rooms
  - Add space
  - Leave

Tasks 

- Invite people at top of menu
- Order to be:
  - Invite people
  - Explore rooms
  - Members
  - Settings
  - Add room
  - Add space<sup>1</sup>
  - Leave

<sup>1</sup> I actually don't know what we're doing with Spaces in spaces on mobile now, so including/removing from menu might require product input.

[Figma](https://www.figma.com/file/PhB0Bf05EdMpdI9rsSsQZ5/%5BExit-beta%5D-Spaces?node-id=570%3A127850)

**Comment by kittykat** [comment]
> I actually don't know what we're doing with Spaces in spaces on mobile now, so including/removing from menu might require product input.

It's functional on Android so should be left in. iOS should probably be updated.

**Comment by kittykat** [comment]
iOS updates: https://github.com/vector-im/element-ios/issues/5810
Android updates: https://github.com/vector-im/element-android/issues/5524
