### ISSUE TITLE
Converge on left panel string to add a Space

### ISSUE THREAD

**Issue by kittykat** [vector-im/element-meta#206]
Android and iOS should have the same strings for Spaces in the left menu. They are different at the moment:

- iOS:
  ![ima_70d1753](https://user-images.githubusercontent.com/51663/157439140-e74eebc4-9985-4319-af4a-038890c8e3be.png)
- Android:
  ![Screenshot_20220309-120130](https://user-images.githubusercontent.com/51663/157439144-56a29ad8-99dd-4723-9989-459c9799483a.png)

## Tasks

- [x] Design input on what the correct view should be
- [x] File an issue to implement the change

**Comment by niquewoodhouse** [comment]
The correct phrase is `Create space`.  Add space suggests you can add via invite or url or searching, which you can't.

**Comment by kittykat** [comment]
-> https://github.com/vector-im/element-android/issues/5516
