### ISSUE TITLE
Account creation fails without indication if password violates server side password policy

### ISSUE THREAD

**Issue by xenein** [vector-im/element-meta#2091]
### Steps to reproduce

1. use password policy in synapse homeserver.yaml
2. enforce 3pid email for account registration via homeserver.yaml
3. open element web -> register account
4. use password violating policy (e.g: no digits, too short)
5. receive mail with confirmation link
6. confirm register
7. enter account data to login

#### What did you expect?

- Client shows no error while registering. Expectation: Account created, ready for login.
- as password violates server side policy, there should be some indication while registering, but there is none

#### What happened instead?

 "incorrect username or password"

![image](https://github.com/vector-im/element-web/assets/76600392/8da0ba8f-037d-4700-aa74-35c9e5a28d80)

Account is not created. (as it should be, but there is no indication, as a user I assume that there should be an account now, because I did not see any error along the way.)

### Operating system

macOS

### Browser information

Firefox 117

### URL for webapp

private server

### Application version

v1.11.40

### Homeserver

matrix.queerchat.de

### Will you send logs?

No

**Comment by t3chguy** [comment]
> as password violates server side policy, there should be some indication while registering, but there is none

What error does your server send in this instance? Sounds like none. 

https://spec.matrix.org/v1.8/client-server-api/#post_matrixclientv3register does not list any valid error code for password not meeting requirements.

Please send logs from console after registering using `mxSendRageshake("vector-im/element-web#26270", true)`

**Comment by aurorasmiles** [comment]
The server returns a HTTP 401 for `POST /_matrix/client/r0/register HTTP/1.1` in this case

**Comment by t3chguy** [comment]
Raised issue https://github.com/matrix-org/synapse/issues/16415 as MSC2000 was abandoned and the error codes Synapse returns are in breach of spec policy

**Comment by t3chguy** [comment]
I can confirm the 401 in the logs, a 401 doesn't halt registration though. 401 is an expected error in the UIA flow - https://spec.matrix.org/v1.8/client-server-api/#user-interactive-authentication-api

Element Web/Desktop have no support for MSC2000 which this Synapse feature relies on so it not working is expected.

**Comment by xenein** [comment]
> Please send logs from console after registering using `mxSendRageshake("vector-im/element-web#26270", true)`

we have no rageshake locally, so I set https://element.io/bugreports/submit in element config to use the provided snippet. 
> Bug report sent!

**Comment by t3chguy** [comment]
This is a Synapse bug, the error should be a 400 not a 401

https://github.com/matrix-org/matrix-spec-proposals/blob/babolivier/password-policy/proposals/2000-password-policies.md

> By adding new error codes to the list of possible ones returned with a 400 status code:
