### ISSUE TITLE
Heart Rain

### ISSUE THREAD

**Issue by gierens** [vector-im/element-meta#2093]
#### What would you like to do?
Just as for some other emojis (https://github.com/vector-im/element-web/issues/16368) I think having this rain animation for :heart: would be very fitting :)

**Comment by t3chguy** [comment]
Closing in favour of https://github.com/vector-im/element-meta/blob/develop/docs/chat_effects.md#the-future-of-chat-effects

**Comment by gierens** [comment]
Ah, great thanks for the hint to the relevant part of the documentation :)
