### ISSUE TITLE
Test cross-organisation automation for PRs and issues

### ISSUE THREAD

**Issue by kittykat** [vector-im/element-meta#210]
We want to raise visibility of PRs and issues in the matrix-org organisation on GitHub for designers and product managers to action so that PRs are progressed quickly and issues are unblocked.

When we tried to add [automation to matrix-org/matrix-react-sdk](https://github.com/matrix-org/matrix-react-sdk/blob/develop/.github/workflows/triage-move-review-requests.yml), we found that the graphQL API restricts cross-organisation actions.

It is possible that PRs and issues can be added to a project from the organisation that hosts the project, but it's not possible for the actions to run based on triggers in another organisation. So can try to run the action from element-meta [with timed triggers](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#onschedule).

I can help set up a test environment as two organisations or users are needed.

**Comment by robintown** [comment]
I think we should be able to just sidestep the GraphQL restrictions by using the REST API instead, unless I'm misunderstanding something?

**Comment by robintown** [comment]
Alternatively, we can use a [repository dispatch](https://github.com/peter-evans/repository-dispatch) to trigger an action in this repo from matrix-org/matrix-react-sdk.

**Comment by kittykat** [comment]
> I think we should be able to just sidestep the GraphQL restrictions by using the REST API instead, unless I'm misunderstanding something?

The REST API doesn't support Beta projects. It feels like GitHub are pushing all new features to use GraphQL. E.g. projectNext has fields instead of columns.

> Alternatively, we can use a [repository dispatch](https://github.com/peter-evans/repository-dispatch) to trigger an action in this repo from matrix-org/matrix-react-sdk.

This looks promising!

**Comment by robintown** [comment]
Closing since we've determined that this is [not possible at the moment](https://github.com/github/feedback/discussions/6212), regardless of where the action runs.
