### ISSUE TITLE
[Story] Secure backup recovery fix

### ISSUE THREAD

**Issue by stefanceriu** [vector-im/element-meta#2107]
### Story

As an user with existing sessions
I want to be informed about recovery missconfigurations
so that I can attempt to fix them

Following verification we might encounter problems with how recovery has been setup (secrets missing/outdated or 4S out-of-sync). Can happen if you use another client that allows to delete backup and create a new one without updating 4S or rotating cross signing without udpating 4S.

### Acceptance criteria

* A new banner should be shown on the home screen asking the user to confirm their recovery key
* A new `Chat backup` entry should be visibile in the application setting
* Within `Chat backup` a `Confirm recovery key` option should be available
    * If this particular session isn't verified then `Chat backup` options aren't available
    * If key backup is disabled then this option should be hidden as well
* Badges should be shown throughout the app (user avatar, settings option, chat backup entry) to guide the user towards fixing recovery

```[tasklist]
### Android
- [x] TBD
```

```[tasklist]
### iOS
- [ ] https://github.com/vector-im/element-x-ios/issues/1899
- [ ] https://github.com/vector-im/element-x-ios/issues/1901
```

```[tasklist]
### Rust
```

### Designs

https://www.figma.com/file/0MMNu7cTOzLOlWb7ctTkv3/Element-X?type=design&node-id=12124-116601&mode=design&t=7YPtBpnsTXrsNrdP-0

#### Android
- [ ] Design sign-off on completion
- [ ] QA sign-off on completion
- [ ] Product sign-off on completion

#### iOS
- [ ] Design sign-off on completion
- [x] QA sign-off on completion
- [ ] Product sign-off on completion

**Comment by manuroe** [comment]
I am closing it. It is available on android too. QA now happens at the epic level
