### ISSUE TITLE
[Story] Set a PIN code and enable biometric unlock 

### ISSUE THREAD

**Issue by VolkerJunginger** [vector-im/element-meta#2128]
### Story

As a logged in user that uses the EX app I want to set a pin code to access the app so that I can be sure that my messages cannot be accessed by other users.

**General**
- EX can be locked through a **custom** pin code. (we don not re-use the phones pin-code)
- Setting a pin code can be mandatory or optional. This might be configurable later though the backend. It needs to be set in the build.
- The default is optional. 

**Userflow 1:  Pin code is optional**
- The user is logged into the app. The user has not set up a pin code yet
- In the settings menue there is a new section for pin code: "screen lock"
- In the section the user can enter the 4 digit pin and is asked to verify the pin once more in the next step.
- If the user fails to enter the pin again they have three more attempts to do so. If the user fails three times they have to start over.

**Userflow 2: Pin code is mandatory**
- When the user has logged into the app for the first time they are asked to set a 4 digit pin-code (the pin code is mandatory). There is an info telling the user that this is a mandatory step and why this is important.
- The user enters the 4 digit pin and is asked to verify the pin once more in the next step
- If the user fails to enter the pin again they have three more attempts to do so. If the user fails three times they have to start over.

If the phone supports biometric unlock (FaceID or fingerprint) **and** the user has set this up:
- The user may activate biometric unlock through Face-ID or fingerprint in the last step.
- This step is optional and the user must be able to skip this step.
- If the user has not set up biometric unlock for their phone: do nothing. Don't ask the user to set this up now.

### Dependencies

- None

#### Android
- [ ] Design sign-off on completion
- [ ] QA sign-off on completion
- [ ] Product sign-off on completion

#### iOS
- [ ] Design sign-off on completion
- [ ] QA sign-off on completion
- [ ] Product sign-off on completion

### Scope

```[tasklist]
### Android
- [x] Implementation
```

```[tasklist]
### iOS
- [x] Implementation
```

## Out of scope

- Any configuration from the server

**Comment by pixlwave** [comment]
> When the user has logged into the app for the first time

To clarify, should this be shown on app launch if the user is already logged in but mandatory app lock has just been enabled on the backend, or should it only be shown as part of the login flow?

**Comment by VolkerJunginger** [comment]
This is shown as part of the setup. If a user logs in to the app the first time (after installing it) AND the pin code is mandatory we show this as a next step once the user is logged in (before giving access to the room list).

I hope this is clearer once we have the user-flow in the design.

**Comment by amshakal** [comment]
Wait, this is not what we discussed in our meeting. We said we would keep in optional in settings for all users to start.

**Comment by manuroe** [comment]
> Setting a pin code can be mandatory or optional. This must be configurable though the backend.

Is it ok to do the configuration though backend later? We are not clear yet how to manage configuration from backend or MDM in EX. It could be a whole epic to decide which EX configuration we expose to the backend

**Comment by VolkerJunginger** [comment]
Yes, it is ok to do the configuration though backend later.

**Comment by amshakal** [comment]
Designs:
PIN in mandatory ([iOS](https://www.figma.com/file/0MMNu7cTOzLOlWb7ctTkv3/Element-X?type=design&node-id=13067%3A149595&mode=design&t=Foh8KXg5a6tfScTu-1), [Android](https://www.figma.com/file/0MMNu7cTOzLOlWb7ctTkv3/Element-X?type=design&node-id=13067%3A150738&mode=design&t=Foh8KXg5a6tfScTu-1))
PIN is optional ([iOS](https://www.figma.com/file/0MMNu7cTOzLOlWb7ctTkv3/Element-X?type=design&node-id=12768%3A13661&mode=design&t=Foh8KXg5a6tfScTu-1), [Android](https://www.figma.com/file/0MMNu7cTOzLOlWb7ctTkv3/Element-X?type=design&node-id=13049%3A19946&mode=design&t=Foh8KXg5a6tfScTu-1))
