### ISSUE TITLE
[Story] PIN code blacklist and UI

### ISSUE THREAD

**Issue by VolkerJunginger** [vector-im/element-meta#2129]
### Story

As a user that is going to configure a pin code for my EX app I want to be sure that my pin code is safe so that I can sleep well at night ;)

**General**
- Each pin-code the user enters *during setup* must be checked against a blacklist of insecure pin codes like "0000".
- The blacklist must be configurable.
- The blacklist check *only* happens when setting up a *new* pin code. A once accepted code may never turn invalid later on because the blacklist has changed.

**Userflow**
- If the user enters a pin that is on the blacklist when setting up a new pin code the user will see an error telling them that the entered pin code is not allowed due to security reasons.
- The user can set up an other pin code next.

### Dependencies

- None

#### Android
- [ ] Design sign-off on completion
- [ ] QA sign-off on completion
- [ ] Product sign-off on completion

#### iOS
- [ ] Design sign-off on completion
- [ ] QA sign-off on completion
- [ ] Product sign-off on completion

### Scope

```[tasklist]
### Android
- [x] Implementation
```

```[tasklist]
### iOS
- [x] Implementation
```

## Out of scope

- None

**Comment by manuroe** [comment]
> The blacklist must be configurable.

It is ok to have this list configured at build time ? This is the behavior of legacy apps).

**Comment by VolkerJunginger** [comment]
yes, it is ok to have this list configured at build time.

**Comment by amshakal** [comment]
Designs:
Blacklist ([iOS](https://www.figma.com/file/0MMNu7cTOzLOlWb7ctTkv3/Element-X?type=design&node-id=13067%3A152024&mode=design&t=Foh8KXg5a6tfScTu-1), [Android](https://www.figma.com/file/0MMNu7cTOzLOlWb7ctTkv3/Element-X?type=design&node-id=13067%3A153088&mode=design&t=Foh8KXg5a6tfScTu-1))

**Comment by pixlwave** [comment]
> yes, it is ok to have this list configured at build time.

Are we going to have a default list for our releases or are we leaving this empty for only forks?

**Comment by manuroe** [comment]
@pixlwave @ganfra we can start with an empty list. This is the current behavior of legacy apps. Let's see if @VolkerJunginger wants to change it later.

**Comment by pixlwave** [comment]
Can we start with just `0000` so it can at least be tested?

**Comment by manuroe** [comment]
No objection :D

**Comment by amshakal** [comment]
I think 0000 and 1234 will fall in it :D
