### ISSUE TITLE
[Story] Unlock Element X with a pin code or biometric unlock

### ISSUE THREAD

**Issue by VolkerJunginger** [vector-im/element-meta#2130]
### Story

As a user that has set up a pin code for the app I want to unlock the app so that I can read my messages.

**General**
- Each time the user opens the app the pin code is required.
- If the user has opened the app and backgrounds the app the code is required after 180 sec.

**Unlocking Failed**
If pin code is entered incorrectly for three times: 
- The user gets logged out and needs to login again w. username + password.
- The user is given an option to set up a new PIN now. 

**If the user has biometric unlock enabled**
- If the user has biometric unlock enabled then the feature is used to unlock the app. The pin is not needed.
- If biometrical login fails for 3 times the pin code is required.
- If the biometric authentication has changed by the user in the global device settings and he tries to open the app, he is forced to use his pin code once. After that the biometric login is used again.

### Dependencies

- None

#### Android
- [ ] Design sign-off on completion
- [ ] QA sign-off on completion
- [ ] Product sign-off on completion

#### iOS
- [ ] Design sign-off on completion
- [ ] QA sign-off on completion
- [ ] Product sign-off on completion

### Scope

```[tasklist]
### Android
- [x] Implementation
```

```[tasklist]
### iOS
- [x] Implementation
```

## Out of scope

- None

**Comment by du82** [comment]
It would be awesome to have per-chat unlocking as well, so I can lock down some chats like note to self even more

**Comment by amshakal** [comment]
Thats an interesting idea. We can think about it further, thanks for your suggestion!

**Comment by amshakal** [comment]
Designs:
Unlock successful ([iOS](https://www.figma.com/file/0MMNu7cTOzLOlWb7ctTkv3/Element-X?type=design&node-id=12768%3A13669&mode=design&t=Foh8KXg5a6tfScTu-1), [Android](https://www.figma.com/file/0MMNu7cTOzLOlWb7ctTkv3/Element-X?type=design&node-id=13049%3A19947&mode=design&t=Foh8KXg5a6tfScTu-1))
Unlock Failed ([iOS](https://www.figma.com/file/0MMNu7cTOzLOlWb7ctTkv3/Element-X?type=design&node-id=13067%3A151669&mode=design&t=Foh8KXg5a6tfScTu-1), [Android](https://www.figma.com/file/0MMNu7cTOzLOlWb7ctTkv3/Element-X?type=design&node-id=13067%3A151661&mode=design&t=Foh8KXg5a6tfScTu-1))
Forgot PIN ([iOS](https://www.figma.com/file/0MMNu7cTOzLOlWb7ctTkv3/Element-X?type=design&node-id=12768%3A13677&mode=design&t=Foh8KXg5a6tfScTu-1), [Android](https://www.figma.com/file/0MMNu7cTOzLOlWb7ctTkv3/Element-X?type=design&node-id=13049%3A19948&mode=design&t=Foh8KXg5a6tfScTu-1))

**Comment by du82** [comment]
> Designs: Unlock successful ([iOS](https://www.figma.com/file/0MMNu7cTOzLOlWb7ctTkv3/Element-X?type=design&node-id=12768%3A13669&mode=design&t=Foh8KXg5a6tfScTu-1), [Android](https://www.figma.com/file/0MMNu7cTOzLOlWb7ctTkv3/Element-X?type=design&node-id=13049%3A19947&mode=design&t=Foh8KXg5a6tfScTu-1)) Unlock Failed ([iOS](https://www.figma.com/file/0MMNu7cTOzLOlWb7ctTkv3/Element-X?type=design&node-id=13067%3A151669&mode=design&t=Foh8KXg5a6tfScTu-1), [Android](https://www.figma.com/file/0MMNu7cTOzLOlWb7ctTkv3/Element-X?type=design&node-id=13067%3A151661&mode=design&t=Foh8KXg5a6tfScTu-1)) Forgot PIN ([iOS](https://www.figma.com/file/0MMNu7cTOzLOlWb7ctTkv3/Element-X?type=design&node-id=12768%3A13677&mode=design&t=Foh8KXg5a6tfScTu-1), [Android](https://www.figma.com/file/0MMNu7cTOzLOlWb7ctTkv3/Element-X?type=design&node-id=13049%3A19948&mode=design&t=Foh8KXg5a6tfScTu-1))

Can you make the Figma designs public so everyone can see them?
