### ISSUE TITLE
[Story]Edit or disable pin-code

### ISSUE THREAD

**Issue by VolkerJunginger** [vector-im/element-meta#2131]
### Story

As a user that has set up a pin code I want to access the pin code in the settings so that I can edit it.

**General**
- In the settings menue there is a new section for pin code.
- If the user has already set up a pin: The section can only be visited by entering the pin.
- The user can either change an existing pin code, set up a pin code or deactivate the pin code.

**Userflow edit pin code**
If the user has already set up a pin code and wants to change it.
- the user is asked to enter the old pin code
- the user can set up a new pin code. The setup works the same as in https://github.com/vector-im/element-meta/issues/2128

**Userflow deactivating a pin code**
This option is only available if setting a pin code is NOT mandatory.
- the user is asked to enter the old pin code to deactivate the pin code

### Dependencies

- None

#### Android
- [ ] Design sign-off on completion
- [ ] QA sign-off on completion
- [ ] Product sign-off on completion

#### iOS
- [ ] Design sign-off on completion
- [ ] QA sign-off on completion
- [ ] Product sign-off on completion

### Scope

```[tasklist]
### Android
- [x] Implementation
```

```[tasklist]
### iOS
- [x] Implementation
```

## Out of scope

- None

**Comment by amshakal** [comment]
Designs:
Edit PIN ([iOS](https://www.figma.com/file/0MMNu7cTOzLOlWb7ctTkv3/Element-X?type=design&node-id=12768%3A13685&mode=design&t=Foh8KXg5a6tfScTu-1), [Android](https://www.figma.com/file/0MMNu7cTOzLOlWb7ctTkv3/Element-X?type=design&node-id=13049%3A19949&mode=design&t=Foh8KXg5a6tfScTu-1))
Remove PIN ([iOS](https://www.figma.com/file/0MMNu7cTOzLOlWb7ctTkv3/Element-X?type=design&node-id=12768%3A13701&mode=design&t=Foh8KXg5a6tfScTu-1), [Android](https://www.figma.com/file/0MMNu7cTOzLOlWb7ctTkv3/Element-X?type=design&node-id=13049%3A19950&mode=design&t=Foh8KXg5a6tfScTu-1))
