### ISSUE TITLE
Set "Show join/leave messages (invites/kicks/bans unaffected)" to off by default

### ISSUE THREAD

**Issue by kittykat** [vector-im/element-meta#2162]
#### What would you like to do?
As a user in busy public rooms with 100s or 1000s of people joining over 2 days, I don't want to see join and leave messages in the timeline

#### Why would you like to do it?
Having a timeline that looks like this is not ideal (note that while we're not in conference season, those messages are spread over a few days):
![Screenshot from 2023-10-25 10-22-17](https://github.com/vector-im/element-web/assets/51663/6e5a17e2-6fa4-4eac-9383-5c57d9b34ed3)

#### How would you like to achieve it?
In settings, make "Show join/leave messages (invites/kicks/bans unaffected)" to off by default.

### Have you considered any alternatives?

We can patch the FOSDEM app downstream

**Comment by t3chguy** [comment]
This setting would need to be set to the same default across all clients to not make a really confusing experience where one client says its off (unset) but another says its on (unset) - why not just change it on their deployment via config.json or in their rooms via state events?

**Comment by daniellekirkwood** [comment]
Agreed, for this season we probably wouldn't want to change this default (as to needing to do that cross-platform and knowing the larger impact longer-term is currently unknown). But if there's a config switch as @t3chguy suggests, that feels like it covers this case well enough

**Comment by t3chguy** [comment]
https://web-docs.element.dev/Element%20Web/config.html#default-settings

Closing in favour of configuration
