### ISSUE TITLE
[Story] Show setting for dark mode / light mode in advanced user settings

### ISSUE THREAD

**Issue by VolkerJunginger** [vector-im/element-meta#2185]
### Story

As a user that is a bit emotional in wintertimes I want to change the appearance of Element X to dark mode so that I can make Element X "wear black on the outside because black is how I feel on the inside".

- Expose a switch for dark / light mode in advanced user settings.

### Dependencies

- TBD

#### Android
- [ ] Design sign-off on completion
- [ ] QA sign-off on completion
- [ ] Product sign-off on completion

#### iOS
- [ ] Design sign-off on completion
- [ ] QA sign-off on completion
- [ ] Product sign-off on completion

### Scope

```[tasklist]
### Android
- [x] Verified with build in screen reader
- [ ] https://github.com/vector-im/element-x-android/issues/1499
```

```[tasklist]
### iOS
- [x] Verified with build in screen reader
- [ ] https://github.com/vector-im/element-x-ios/issues/2083
```

## Out of scope

- TBD

**Comment by kittykat** [comment]
"Appearance: system" doesn't really mean anything to me as a user. Can we use strings like "Theme", "Match system", (and existing ones like "Light" and "Dark")?

It feels like it follows an iOS pattern right now. Android has the word "theme" in the strings to disambiguate what they are about.

**Comment by stefanceriu** [comment]
> "Appearance: system" doesn't really mean anything to me as a user.
- That seems to be a normal Apple design choice
 
<img width="304" alt="Screenshot 2023-11-27 at 12 30 07" src="https://github.com/vector-im/element-meta/assets/637564/dd0f2cae-6db7-401c-bd76-23a0b07e5c18">

> Can we use strings like "Theme"
I don't think we can because this is not a theme. It again follows Apple's choice of word

<img width="457" alt="Screenshot 2023-11-27 at 12 33 39" src="https://github.com/vector-im/element-meta/assets/637564/89e8e6e7-fd55-4b1d-b76a-50cc663c1cec">

**Comment by kittykat** [comment]
I wonder if this is one of the places where it makes sense to differentiate between Android and iOS because the system default is quite different.

ooi, based on the screenshot you shared above, does it make sense to use "Auto" instead of "System"?

**Comment by stefanceriu** [comment]
> does it make sense to use "Auto" instead of "System"

Auto makes sense for the system as it will compute it based on the time of the day. It doesn't for us as we just follow the system.
