### ISSUE TITLE
[Story] Magnify avatar in detail view

### ISSUE THREAD

**Issue by VolkerJunginger** [vector-im/element-meta#2194]
### Story

As a user that wants to enjoy the beauty of a room or user avatar I want the avatar to be magnified when tapping on it in the details.

- The feature exists already on iOS

### Dependencies

- TBD

#### Android
- [ ] Design sign-off on completion
- [ ] QA sign-off on completion
- [ ] Product sign-off on completion

### Scope

```[tasklist]
### Android
- [ ] Verified with build in screen reader
```

## Out of scope

- TBD

**Comment by manuroe** [comment]
Dup of #2207
