### ISSUE TITLE
[Story] Setting: Disable (enable) read receipts

### ISSUE THREAD

**Issue by VolkerJunginger** [vector-im/element-meta#2202]
### Description

As a user that does value being transparent about the own read status I want to disable sending read receipts so that I can read my messages anonymously.

### Acceptance criteria

- Create a setting in advanced setting to disable sending read receipts

### Leads

* Tech: @Velin92 
* Design: <GitHub id>

### Size estimate

S

### Dependencies

- None

### Out of scope

- 

### Open questions

```[tasklist]
### Questions
```

### Subtasks

```[tasklist]
### Android
- [ ] https://github.com/element-hq/element-x-android/issues/2204
```

```[tasklist]
### iOS
- [ ] https://github.com/element-hq/element-x-ios/issues/2319#
```

```[tasklist]
### Rust
```

```[tasklist]
### Other
```

### Android
- [ ] Design sign-off on completion
- [ ] QA sign-off on completion
- [ ] Product sign-off on completion

### iOS
- [ ] Design sign-off on completion
- [ ] QA sign-off on completion
- [ ] Product sign-off on completion

**Comment by jplatte** [comment]
Completely disabling the sending of read markers / receipts would break the unread state of rooms (even more than it already is). We will have to switch to sending *private* read markers if the user doesn't want others to know which messages they have read.

I believe we already have support for private read receipts in the SDK, so there should not be much Rust work to do here.

**Comment by Velin92** [comment]
created a PR on the SDK to expose a function to send private RR:
https://github.com/matrix-org/matrix-rust-sdk/pull/2906/files

**Comment by Velin92** [comment]
this has been blocked until we decide how to approach new features from BWI

**Comment by Velin92** [comment]
There was a bug in the SDK for sending private RR, but has now been fixed: https://github.com/matrix-org/matrix-rust-sdk/pull/2999

**Comment by rwjack** [comment]
Apart from having a global switch to toggle read receipts, what do you think about having a per-room override? 

Eg. I don't want to share read receipts with any of the rooms I join, so I toggle it off under advanced settings, but I want to share read receipts with friends in DMs, where I can turn read receipts on individually, same as Apple's iMessage.

![IMG_6378](https://github.com/element-hq/element-meta/assets/59068073/ffd8011e-1d40-404a-83b8-c7f6d394e493)

![IMG_6377](https://github.com/element-hq/element-meta/assets/59068073/76c4c6ea-9a83-4a33-a6d1-8646510b5319)
