### ISSUE TITLE
[Story] Setting: Disable sending typing notifications and read receipts

### ISSUE THREAD

**Issue by VolkerJunginger** [vector-im/element-meta#2203]
### Story
As a user of the EX client I do not want to expose to other user that I am active in the app and therefor be able to not send read receipts or typing notifications.

Add a setting to disable user-presence:
- The setting disables sending of typing notifications
- The setting disables sending of read-receipts and make the client send private-read-receipts

If the user enabled the setting do the following in the timeline:
- Don't show typing. notifications of other users
- Don't show read receipts of other users.

### Dependencies

- TBD

#### Android
- [ ] Design sign-off on completion
- [ ] QA sign-off on completion
- [ ] Product sign-off on completion

#### iOS
- [ ] Design sign-off on completion
- [ ] QA sign-off on completion
- [ ] Product sign-off on completion

#### Web
- [ ] Design sign-off on completion
- [ ] QA sign-off on completion
- [ ] Product sign-off on completion

### Scope

```[tasklist]
### Android
- [ ] https://github.com/element-hq/element-x-android/issues/2241
```

```[tasklist]
### iOS
- [ ] https://github.com/element-hq/element-x-ios/issues/2348
```

## Out of scope

- TBD

**Comment by manuroe** [comment]
@VolkerJunginger: the app does not support typing notification at all. It is weird to add a settings about them.

**Comment by jmartinesp** [comment]
@manuroe @VolkerJunginger : there is some code for sending typing notification in the Rust SDK, it's not exposed to the apps though. Should we create the bindings, send the typing notifications and add this option to disable them?

**Comment by VolkerJunginger** [comment]
yes, please.

**Comment by jmartinesp** [comment]
We'll also need some designs for displaying the typing notifications on the timeline. I guess we'll use more or less the same designs and animations that we had in the legacy apps, but it would still be good to confirm this.

**Comment by bmarty** [comment]
FTR this is the current design for this setting in Element Android, in `Settings`/`Preferences` section `Message editor`:

<img width="276" alt="image" src="https://github.com/element-hq/element-meta/assets/3940906/25b20df0-2320-4fc5-8859-a6a656ba0b0b">

**Comment by amshakal** [comment]
Here is a suggestion for what copy can be 

<img width="499" alt="Screenshot 2024-02-01 at 12 37 37 pm" src="https://github.com/element-hq/element-meta/assets/85162587/956aec9d-97f1-4a7b-9b27-974b30e0972e">

**Comment by jmartinesp** [comment]
> Here is a suggestion for what copy can be
> 
> <img alt="Screenshot 2024-02-01 at 12 37 37 pm" width="499" src="https://private-user-images.githubusercontent.com/85162587/301505939-956aec9d-97f1-4a7b-9b27-974b30e0972e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY3OTE0MjUsIm5iZiI6MTcwNjc5MTEyNSwicGF0aCI6Ii84NTE2MjU4Ny8zMDE1MDU5MzktOTU2YWVjOWQtOTdmMS00YTdiLTliMjctOTc0YjMwZTA5NzJlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjAxVDEyMzg0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM2ODE4YWQ5YmNjZmMzY2VjZmZmZDM3YzZmNDMzNWYxY2FlYWVmMDFjZjI0MWQ3NWFmYzY5OWVkYjgwYWRkYzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.SE88_1U8ra5X3w-PjMd3OwKf1hUrlpkXZ36mKB6KKps">

But we do receive read receipts and send and receive typing notifications even with it disabled, I think?

**Comment by bmarty** [comment]
@amshakal the wording looks good, but I would replace all the `or` by `and`. Note that I am not a native English speaker, so you may just ignore me :)

Also, just to confirm, the toggle will be enabled by default.

**Comment by bmarty** [comment]
Regarding the implementation, we will keep separate booleans internally, like:
- `renderTypingNotifications`
- `sendTypingNotifications`
- `renderReadReceipts`
- `sendPublicReadReceipts` (this one already exists on EXA)
rather that just a global `isPresenceEnabled` or anything similar, just to be able to be flexible. There will still be one setting `Share presence` visible to the user that will set all the booleans at once.

To complete this, these settings will be lost when the user logs out, so they are stored in a store scoped to the session. This store is named `SessionPreferencesStore` on Android.
