### ISSUE TITLE
No avatars when forwarding a message

### ISSUE THREAD

**Issue by VolkerJunginger** [vector-im/element-meta#2206]
### Your use case

Avatars are missing when forwarding a message. 
This makes it hard ti distinguish the recipients. 

```[tasklist]
### Tasks
- [x] iOS: No avatars when forwarding a message
```

**Comment by ganfra** [comment]
The issue is not precise enough, which avatar, which screen?  Can you share screenshots so we better understand the issue?

**Comment by stefanceriu** [comment]
@ganfra This was a bug on the message forwarding screen on iOS, the one that shows the rooms you can forward to. On iOS those rooms didn't use to show their avatar because of a bug. Is is the same on android?

**Comment by ganfra** [comment]
> @ganfra This was a bug on the message forwarding screen on iOS, the one that shows the rooms you can forward to. On iOS those rooms didn't use to show their avatar because of a bug. Is is the same on android?

Nope, it's working on android, not sure why there is a ticket

**Comment by stefanceriu** [comment]
Probably just a mistake then, I'll remove the android flag
