### ISSUE TITLE
Pin code: German translations missing

### ISSUE THREAD

**Issue by VolkerJunginger** [vector-im/element-meta#2211]
### Story

Pin code: German translations missing for the whole section

### Scope

```[tasklist]
### Language
- [ ] French
- [ ] German
```

**Comment by manuroe** [comment]
@nadonomy what is the process to get professional translations for new coming features?

**Comment by nadonomy** [comment]
@manuroe sadly the professional translation service just didn't couldn't deliver (internal notes here: https://github.com/vector-im/element-internal/issues/491) and we had to edit everything ourselves internally in the end.

So the best bet is to translate French & German internally, as that's what we care about the most.

**Comment by manuroe** [comment]
Assigning it to @VolkerJunginger and @bmarty. They are our best internal translators for DE and FR.

**Comment by pixlwave** [comment]
A user had incorrect privileges when I opened up the project and has translated a load of strings by mistake.

@VolkerJunginger: Rather than having to translate yourself, you can now see the work they did here (~170) https://localazy.com/p/element/contributors/linuskmr

**Comment by bmarty** [comment]
Un-assigning me, since the missing translations are (were?) the German ones. FTR I'm keeping translating new wordings in French on a regular basis (at least once a week).
