### ISSUE TITLE
@name expansion not working

### ISSUE THREAD

**Issue by radeknoone** [vector-im/element-meta#2215]
### Steps to reproduce

I have to write person name starting with @ and wait and click on the 'graphical representation' of that name to let chat understand, that it is person not the plaintext:
![image](https://github.com/vector-im/element-web/assets/23701185/99180f2c-0e8e-4295-9c4b-432d600c148c)

This is 'graphical representation' of user:
![image](https://github.com/vector-im/element-web/assets/23701185/b710ea8c-b44d-49a9-b93d-26bd8942dfcb)

This is what happen, when I use text form: 
![image](https://github.com/vector-im/element-web/assets/23701185/bffd78c1-a2dc-4ff9-ac6b-9b75d8582d91)

Thats not making sense to me - the name IS @user:server.tld, why I have to bother with the 'graphical representation'?

Element version: 1.11.30
Olm version: 3.2.12

### Outcome

I would expect, that if i write full user name like @user:server.tld, then will be used same way as "graphical representation".

### Operating system

Linux

### Browser information

Firefox

### Will you send logs?

Yes

**Comment by t3chguy** [comment]
Because the mention has to be listed in `m.mentions` property in the event, and as a sender you may wish to send something that looks like an MXID which doesn't mention the owner of that MXID.
