### ISSUE TITLE
Posthog | E2EE possible error inconsistency on name cross platform, would need also to add error code in event

### ISSUE THREAD

**Issue by BillCarsonFr** [vector-im/element-meta#224]
It looks like web/android/mobile are not using Unspecified vs Unknown the same way. It's suspicious as the graph are inverted for these category on android vs ios; Unspecified looks absent in web?

Also, we need more details regarding unknown/unspecified as they represent a decent chunk of errors. E.g on web nearly all of UTDs are `UnknownError`

**Comment by BillCarsonFr** [comment]
As per discussion we could add more enum values to the error `name` field, and ensure we have cross platform consistency

```
UnknownError covers a lot though,

    OLM_MISSING_CIPHERTEXT
    OLM_NOT_INCLUDED_IN_RECIPIENTS
    OLM_BAD_ENCRYPTED_MESSAGE
    OLM_BAD_RECIPIENT
    OLM_BAD_RECIPIENT_KEY
    OLM_FORWARDED_MESSAGE
    OLM_BAD_ROOM
    MEGOLM_MISSING_FIELDS
    OLM_DECRYPT_GROUP_MESSAGE_ERROR
    OLM_UNKNOWN_MESSAGE_INDEX
    MEGOLM_BAD_ROOM

**Comment by novocaine** [comment]
@BillCarsonFr can you post links to the suspicious graphs please? I think the crypto team can action this..

**Comment by BillCarsonFr** [comment]
I wonder if mobile won't be other reporting the same UISI compared to web.
A mobile app is often killed/start, we don't persist the sessions that were already reported, so everytime you re-open the app we will re-report for that session.
Web is not persisting either but web is often opened for longer.

Is there a way to send the sessionId (or hash) in the error event and deduplicate on posthog?

**Comment by duxovni** [comment]
Would we want to deduplicate on session ID, or on event ID? If we get 12 undecryptable messages from the same user as part of the same megolm session, should that be 1 tracked error or 12?

**Comment by duxovni** [comment]
Web also theoretically has some code to save/load already-reported event IDs from local storage, but it's commented out right now, I forget what the issue was.

**Comment by BillCarsonFr** [comment]
Consistency now resolved https://github.com/matrix-org/matrix-react-sdk/pull/8916
