### ISSUE TITLE
Clean up Settings page

### ISSUE THREAD

**Issue by VolkerJunginger** [vector-im/element-meta#2247]
Clean up the settings page an cluster items:

My name & Avatar

**"Manage my app"-section** 
- Notifications
- Screen lock
- Chat Backup

**"Account"-section**
- Manage Account
- Manage Devices
- Manage Blocked Users

**"General"-section**
- About
- Report a problem
- Analytics
- Advanced Settings
- (optional) Dev options
- Sign out

```[tasklist]
### Android
- [ ] https://github.com/element-hq/element-x-android/issues/2801
```

```[tasklist]
### iOS
- [ ] https://github.com/element-hq/element-x-ios/issues/2789
```

**Comment by jmartinesp** [comment]
@VolkerJunginger maybe it's a dumb question, but since I can't find a Figma design for this, should the titles of each section be added to the layout as headers, or are they just so we can think of them as different groups of features?

**Comment by VolkerJunginger** [comment]
No headline needed. It's just for grouping.

**Comment by jmartinesp** [comment]
Ok, just to confirm it, it should look like this:

<details>
<summary>Screenshot</summary>

<img width="511" alt="image" src="https://github.com/element-hq/element-meta/assets/480955/53585dce-7196-4247-8345-cf29a3b2c3b3">

</details>

**Comment by VolkerJunginger** [comment]
nice
