### ISSUE TITLE
Remove extra logout screen

### ISSUE THREAD

**Issue by VolkerJunginger** [vector-im/element-meta#2249]
### Your use case

Go to setting and tap "log-out".
The app is opening an extra screen.
The user has to tap "Log-Out" again.
A pop-up is shown: "are you sure you want to logout?"

Expectation:
- Do not show the extra screen
- Show the pop-up right away (same as iOS)

**Comment by VolkerJunginger** [comment]
@amshakal Do you agree or was there any meaningfull reason to show the extra screen?

**Comment by amshakal** [comment]
I think it's fairly normal to have an 'are you sure' alert for signing out, specially in our case where signing in can mean going through the whole OIDC flow again, or worse, doing verification again. We should avoid having people sign out.

**Comment by amshakal** [comment]
I do however think that having sign out inside settings is fine but we dont need to make it prominent in the context menu on iOS

**Comment by VolkerJunginger** [comment]
Ok, lets keep the alert but remove the extra page on Android.

**Comment by VolkerJunginger** [comment]
Will be done w. https://github.com/element-hq/element-x-android/issues/2072
