### ISSUE TITLE
Discourage enabling threads if the user's homeserver doesn't have threads support

### ISSUE THREAD

**Issue by novocaine** [vector-im/element-meta#228]
#### What would you like to do?

Discourage users from enabling threads if their homeserver does not have threads support as per [MSC 3440](https://github.com/matrix-org/matrix-spec-proposals/pull/3440).

#### Why would you like to do it?

The threads experience is significantly degraded without server-side support, and not fit for general use. We should try to avoid promoting the degraded threads experience as part of our beta.

#### How would you like to achieve it?

1. Do not show the beta prompt in the message toolbar if the homeserver does not have support for MSC 3440.
2. Do continue to show the option to enable threads in settings. If when this setting is enabled, the homeserver doesn't support MSC 3440, warn the user with a modal dialog with the following copy

>  Your homeserver does not currently support threads, so this feature may be unreliable. Some threaded messages may not be reliably available. [Learn more.](https://element.io/help#threads) Do you want to enable threads anyway?

- [x] https://github.com/vector-im/element-web/issues/21790
- [x] https://github.com/vector-im/element-android/issues/5761
- [x] https://github.com/vector-im/element-ios/issues/6038

**Comment by novocaine** [comment]
There will be a bunch of existing users who have already enabled it at this point against a homeserver without threads support - I wonder if we should consider doing anything about that?

**Comment by janogarcia** [comment]
What if they have already enabled it? They should still be able to "Leave the beta". 

And if they want to enable it back after having disabled it?

**Comment by novocaine** [comment]
> What if they have already enabled it? They should still be able to "Leave the beta".
> 
> And if they want to enable it back after having disabled it?

I have amended the ticket to continue to show the threads setting for all users so that users that have already enabled it still have control.

**Comment by janogarcia** [comment]
>  we will need to continue to show the beta card for users that have enabled the feature using a home server that doesn't have MSC 3440, **so they can disable it**.

What would happen after disabling it, and on subsequent client releases? The feature may disappear from some users if they 

1. enabled threads when in a non-MSC 3440 homesever 
2. then disable thread
3. at a later date (either in the same client version, or a new one), with threads disabled and still in a non-MSC 3440 homesever, want to get their threads back

It could also happen that some users managed to enable threads in some platform (for example, Web) during the time window between the first threads RC and the hotfix, but now can't get threads enabled on other platforms (iOS, Android) if they didn't do it during said timeframe.

I guess we can't detect either the case where a user during the timeframe enabled threads, created some content, and then disabled threads before releasing the hotfix. They wouldn't be able to get their threads back. But that's probably less likely to happen.

**Comment by novocaine** [comment]
@janogarcia I changed my mind and updated the ticket description, are you happy with that?

**Comment by janogarcia** [comment]
That's why I suggested (internally, yesterday) not hiding it but showing a contextual warning instead.

**Comment by janogarcia** [comment]
@novocaine Yeah, definitely better. 👍

**Comment by novocaine** [comment]
Suggested copy for the "Learn more" at https://element.io/help#threads

## Why does my homeserver need to support threads?

In order to reliably update the list of threads in a room and their contents, your homeserver needs to support threads via MSC3440. If your home server runs Synapse, this is available in version 1.55 and above. You can ask your homeserver administrator to upgrade your server to ensure that threads are supported.

If your homeserver doesn't support threads, you will still be able to read and contribute to threads, but the feature might be unreliable - you might not see all threads in a room, and some messages might be missing, especially older messages. For that reason, we strongly recommend to upgrade your homeserver.

**Comment by t3chguy** [comment]
The EW release which links to https://element.io/help#threads has just gone live, would be good to get the site update up asap
