### ISSUE TITLE
Remove edits from roomlist preview

### ISSUE THREAD

**Issue by VolkerJunginger** [vector-im/element-meta#2301]
### Your use case

Please remove edits from roomlist preview.
- it is ok for now that the preview might still show the unedited message.

**Comment by frebib** [comment]
I'm a little confused by this. As a user I would expect the room list preview for a room to show the last "readable" message. Seeing one thing in the preview and something else entirely when opening the room would seem like buggy behaviour to me as a user

**Comment by stefanceriu** [comment]
It's already behaving weirdly as it's rendering the last edit irrelevant of whether it's for the last message in the timeline or not. If you go edit a message from 5 years ago it will show as the preview in the room list.

**Comment by kongo09** [comment]
@VolkerJunginger , can I just clarify: is this intended behaviour or just a prio question and the preview will be fixed at a later point?

**Comment by VolkerJunginger** [comment]
See my comment https://github.com/element-hq/element-x-ios/issues/2683#issuecomment-2059291987

**Comment by ara4n** [comment]
might be worth opening a new meta issue to track the actual desired behaviour? i.e. to show the most recent event in the room preview, even if it's been edited?
