### ISSUE TITLE
Clean up User Profile

### ISSUE THREAD

**Issue by VolkerJunginger** [vector-im/element-meta#2304]
### Your use case

Add to the top:
-  DM Call to action
- "Call" Call to action 

```[tasklist]
### Android
- [ ] https://github.com/element-hq/element-x-android/issues/2818
```

```[tasklist]
### iOS
- [ ] https://github.com/element-hq/element-x-ios/issues/2816
```

**Comment by jmartinesp** [comment]
I think we'll need some icons for those call to actions. We have [these designs](https://www.figma.com/file/0MMNu7cTOzLOlWb7ctTkv3/Element-X?type=design&node-id=1302%3A80673&mode=design&t=cn21D2oQI92tVhWI-1) but they lack the DM one and I think they're a bit outdated?

**Comment by Velin92** [comment]
> I think we'll need some icons for those call to actions. We have [these designs](https://www.figma.com/file/0MMNu7cTOzLOlWb7ctTkv3/Element-X?type=design&node-id=1302%3A80673&mode=design&t=cn21D2oQI92tVhWI-1) but they lack the DM one and I think they're a bit outdated?

do we have any news about this? @amshakal @VolkerJunginger

**Comment by amshakal** [comment]
Profile - [iOS](https://www.figma.com/file/A2pAEvTEpJZBiOPUlcMnKi/Settings-%2B-Room-Details-(new)?type=design&node-id=1787%3A39519&mode=design&t=cdfShLkE2yWw0WDU-1), [Android](https://www.figma.com/file/A2pAEvTEpJZBiOPUlcMnKi/Settings-%2B-Room-Details-(new)?type=design&node-id=1787%3A57232&mode=design&t=cdfShLkE2yWw0WDU-1)
