### ISSUE TITLE
Clean up Room Details

### ISSUE THREAD

**Issue by VolkerJunginger** [vector-im/element-meta#2305]
### Your use case

Please clean up the room details page:

Remove from the list:
- Call to action for the "invite to group flow" if the user has the rights to do so.

Add to the top:
- Call to action for the "invite to group flow" if the user has the rights to do so.
- "Call!" Call to action ? @amshakal what do you think?

```[tasklist]
### Android
- [ ] https://github.com/element-hq/element-x-android/issues/2814
```

```[tasklist]
### iOS
- [ ] https://github.com/element-hq/element-x-ios/issues/2812
```

**Comment by jmartinesp** [comment]
Is the 'invite to group' option this one?  

<img width="528" alt="image" src="https://github.com/element-hq/element-meta/assets/480955/31572d24-c42a-4afc-8104-def6d51b31fb">

If it is, I guess we should reuse the icon and shorten the title to 'Invite'?

Also, should we add the 'Call' CTA @VolkerJunginger , @amshakal ? And with which icon, the phone one or video one? Keep in mind the call will be by default a video call although you can disable your camera.

**Comment by amshakal** [comment]
i have created states for when invite is available or not and when the room is encrypted or not
iOS - https://www.figma.com/file/A2pAEvTEpJZBiOPUlcMnKi/Settings-%2B-Room-Details-(new)?type=design&node-id=1787%3A39764&mode=design&t=cdfShLkE2yWw0WDU-1
Android - https://www.figma.com/file/A2pAEvTEpJZBiOPUlcMnKi/Settings-%2B-Room-Details-(new)?type=design&node-id=1787%3A59660&mode=design&t=cdfShLkE2yWw0WDU-1

**Comment by jmartinesp** [comment]
I've added the `action.call` string to localazy since we didn't have one before.
