### ISSUE TITLE
Clean Up DM details

### ISSUE THREAD

**Issue by VolkerJunginger** [vector-im/element-meta#2306]
### Your use case

Please clean up the DMM details view

Remove from the top:
- Share DM call to action

Add to the top:
- "Call" call to action

```[tasklist]
### Android
- [ ] https://github.com/element-hq/element-x-android/issues/2815
```

```[tasklist]
### iOS
- [ ] https://github.com/element-hq/element-x-ios/issues/2813
```

**Comment by amshakal** [comment]
iOS - https://www.figma.com/file/A2pAEvTEpJZBiOPUlcMnKi/Settings-%2B-Room-Details-(new)?type=design&node-id=1787%3A31291&mode=design&t=cdfShLkE2yWw0WDU-1
Android - https://www.figma.com/file/A2pAEvTEpJZBiOPUlcMnKi/Settings-%2B-Room-Details-(new)?type=design&node-id=1787%3A56333&mode=design&t=cdfShLkE2yWw0WDU-1

**Comment by jmartinesp** [comment]
@VolkerJunginger , @amshakal just to confirm, the CTAs that should be visible for DMs are Mute/Unmute and Call if available, right?

In the designs I also see the CTAs for creating a DM, which doesn't make sense, and Share, which we want to remove, so I guess the combination above is the right one?

**Comment by VolkerJunginger** [comment]
@VolkerJunginger , @amshakal just to confirm, the CTAs that should be visible for DMs are Mute/Unmute and Call if available, right?

yes.
