### ISSUE TITLE
can we disable the non-sence  of verify sessions 

### ISSUE THREAD

**Issue by sergiomb2** [vector-im/element-meta#2316]
### Have you considered any alternatives?

can we disable the every time user use a new device have to verify the session? , encrypt all messages in the room is a mess , I 'm a expert in Linux I did rpm packages for Fedora [1], I  already have 947 keys (Successfully restored 947 keys) 

I don't see  any great improvement on validate the session and have n sessions in the room , once I login with my auth and element-keys , I 'd like all sessions are valid , I see users with 20 sessions to verify 

[1] https://copr.fedorainfracloud.org/coprs/sergiomb/electrons/

### Additional context

I have an user that doesn't verify the session , because mobile app , doesn't pop-up correctly the emojis I guess , I had that problem once , verification doesn't work in many androids and if he enter in the room , another user in the next day says that have all what was write encrypted and can't read 

we don't want so much security, we want communicate with some security but isn't nothing that must be hyper secure 

_No response_

**Comment by richvdh** [comment]
There are no plans to make it possible to disable this. You can skip it if you prefer.
