### ISSUE TITLE
Multiple choices for Polls

### ISSUE THREAD

**Issue by antonengelhardt** [vector-im/element-meta#2319]
#### What would you like to do?

Select multiple options for Polls.

#### Why would you like to do it?

Example: For meeting time polls, i would like to be able to select multiple timewindows and not just one.

#### How would you like to achieve it?

By clicking any option and clicking it again to unselect it.

### Have you considered any alternatives?

Doodle

**Comment by antonengelhardt** [comment]
@t3chguy Thanks for transferring. Now I see that this is a duplicate of #2295. should we close this issue?

**Comment by t3chguy** [comment]
Good spot

**Comment by t3chguy** [comment]
Duplicate of #2295
