### ISSUE TITLE
Consistent handling of end-of-candidates `m.call.candidates` events

### ISSUE THREAD

**Issue by stefanceriu** [vector-im/element-meta#2323]
### Steps to reproduce

1. Where are you starting? What can you see?
- starting from a DM
2. What do you click?
- the call button
3. More steps…

#### What did you expect?
- valid event payloads
#### What happened instead?
As part of the legacy VoIP calling feature the clients are supposed to exchange `m.call.candidates` events as per https://spec.matrix.org/v1.9/client-server-api/#mcallcandidates

Web does so but includes an invalid `Candidate` dictionary at the end of the list e.g.

```
{
  "type": "m.call.candidates",
  "content": {
    "candidates": [
      {
        "candidate": "[candidate:123 1 udp 123 123.123.123.123 123 typ relay raddr 123.123.123.123 rport 123 generation 0 ufrag D5L1 network-id 2]",
        "sdpMid": "0",
        "sdpMLineIndex": 0,
        "usernameFragment": "D5L1"
      },

      ...

      {
        "candidate": ""
      }

    ],
    "version": "1",
    "call_id": "123",
    "party_id": "123"
  },
  "room_id": "!123:matrix.org"
}
```

All `Candidate` dictionaries are supposed to have 3 required fields: `candidate`, `sdpMLineIndex` and `sdpMid` which doesn't happen in this case, so the RustSDK refuses to accept them.

### Operating system

macOS

### Browser information

Chrome

### URL for webapp

staging.element.io

### Will you send logs?

No

**Comment by ara4n** [comment]
@stefanceriu this looks to be a bug in the spec, not in EW. A blank candidate entry is how you signify the end of trickle ICE (i.e. that there are no more candidates to be discovered), and so is semantically important to signal the end of the ICE setup. Looks like the spec forgot that this was a thing.

**Comment by ara4n** [comment]
Actually the spec got it right in words: https://spec.matrix.org/v1.9/client-server-api/#end-of-candidates; it's "just" the formal definition which got it wrong

**Comment by stefanceriu** [comment]
Oh, I'm sorry, I totally missed that. I'm going to close this ticket and move the discussion to the Rust side here https://github.com/matrix-org/matrix-rust-sdk/issues/3187
