### ISSUE TITLE
My Threads: Thread replies to root messages going unnoticed

### ISSUE THREAD

**Issue by novocaine** [vector-im/element-meta#235]
We're updating this issue to be more specific as the original content is now split into 2 solutions. 

1. Updating Notifications so that messages are not missed will be tracked by https://github.com/vector-im/element-meta/issues/196
2. **this issue** The "My Threads" filter in the Thread Panel should include threads that my message is the root message.

## Solution
This is fixed by the thread list API

---
## The original issue content

Current implementation prevents you from being notified when someone starts a thread on one of your messages without mentioning or quoting you.

“My threads” should include threads where I’m the author of the root message even if I didn’t reply to it or no one mentioned me directly.

Failing to implement it means users will be missing replies to their messages.

User A post a message in the main timeline.
User B starts a thread for User A message, without directly mentioning him (e.g., User B message is That looks promising. Any chance I can test the service before I commit to your contract?)
User A never gets a notification for User B request.
Missed business opportunity.

**Comment by novocaine** [comment]
@clokep said:

> Yeah, that seems like it might be a design flaw in what we put together.
> I think we could just consider it an implementation bug in terms of the current_user_participated bit, but I don't think the filters allows you to find it easily.

**Comment by clokep** [comment]
[MSC3856](https://github.com/matrix-org/matrix-spec-proposals/pull/3856) should help with this case.

**Comment by daniellekirkwood** [comment]
This should be fixed with the notifications work that we're doing for the Exit Beta Milestone @gsouquet / @clokep ?

**Comment by clokep** [comment]
> This should be fixed with the notifications work that we're doing for the Exit Beta Milestone @gsouquet / @clokep ?

This issue is a bit confusing -- it isn't really related to notifications, but to the way we display threads under "My Threads". It should be fixed as part of the threads list API added in MSC3856 as part of the exit beta work.

**Comment by clokep** [comment]
This is done -- from a technical POV this ended up being the same solution from #195.
