### ISSUE TITLE
Moderation feature bugs

### ISSUE THREAD

**Issue by VolkerJunginger** [vector-im/element-meta#2369]
### Your use case

The user-screen in the moderation

- Always show all users in the edit admin list
  - iOS does not show yourself

- Pending members in edit admin & moderation list
  - Android shows pending members; iOS does not
  - It must be possible to change the role of a pending member

- Show role of user & show "not selectable" checkbox
  - Show sections for the users role: Admin, Moderator, Member
  - Decorate the pending members: USERNAME (Pending)
  - Show a checkbox that is not selectable
  @amshakal

- iOS Use the same string for search in all memberlists.
  - In the memberlist seem to be another string that in the moderation or invite flow: Search for someone
  
- iOS Memberlist:
  - As an admin I should not be able to ban other admins
  - I should not be able to ban myself

Android:Roles & Permissions
- lines for headlines are missing
  

```[tasklist]
### Android
- [ ] https://github.com/element-hq/element-x-android/issues/2593
```

```[tasklist]
### iOS
- [ ] https://github.com/element-hq/element-x-ios/pull/2608
```

**Comment by jmartinesp** [comment]
@VolkerJunginger just to confirm, on Android should we do anything else to the separators in the 'change permissions for actions' screens? There are separators between the different sections, and the headlines are bolder (medium vs regular) than the other options.

We could change the headlines in the Compound components to be slightly larger or make then bold if they don't look different enough from the options.

<details>
<summary>Screenshot</summary>
<img src='https://github.com/element-hq/element-meta/assets/480955/5234fdab-658f-4620-ad38-e2ac7a1dc8f5' />
</details>

**Comment by amshakal** [comment]
I dont think we should change our list component, we are using material standard components and styles and to a regular android user, thse should feel fine. I had a chat with Aaron and we can monitor if people complain about this list item in the future and iterate on the component accordingly.

**Comment by jmartinesp** [comment]
Should we close this now?

**Comment by amshakal** [comment]
Yes
