### ISSUE TITLE
Blocking users is not working anymore as expected

### ISSUE THREAD

**Issue by VolkerJunginger** [vector-im/element-meta#2382]
### Your use case

Blocking users does not work anymore as expected.
- Blocking a user should hide the users messages: This is not always the case anymore.
- The timeline seems to "drop" recent messages so the last messages on the screen are from weeks / month ago.
- Unblocking the user does not bring the timeline back in it's original state. The messages are still from the past & some messages of the blocked user seem still to be hidden.
- Sending a new message in this room seems to restore the timeline.
- When a user is blocked the "blocking" call to action is not updated the first time. The button still gives the option to block the user even though I just did that.

The behaviour is quite irrational but seem to be similar on iOS and Android so I suspect this is an SDK issue.

**Comment by manuroe** [comment]
Volker is seing this issue on element.io. BWI can see them on their HS. 
The behavior is as expected when I test it with my matrix.org account.

**Comment by manuroe** [comment]
@kegsay can you share any thoughts on this when you are back?

**Comment by manuroe** [comment]
I tested it again on m.org and it did not work. See the linked rageshake and its sister rageshake.
@bnjbvr raised a suspicious piece of code at https://github.com/matrix-org/matrix-rust-sdk/blob/96a4b06ca69d44cd03f1646b0b78295887c7bb70/crates/matrix-sdk-ui/src/timeline/builder.rs#L212-L225 where the timeline is cleared but not reloaded.

**Comment by bnjbvr** [comment]
https://github.com/matrix-org/matrix-rust-sdk/pull/3378 should help with this.

**Comment by manuroe** [comment]
I just tested it again. It works as expected now. Thanks @bnjbvr !
