### ISSUE TITLE
MSC3783: Fixed base64 for SAS verification cross platform

### ISSUE THREAD

**Issue by BillCarsonFr** [vector-im/element-meta#241]
Update all sdk according to new [SAS encdoding](https://github.com/matrix-org/matrix-spec-proposals/pull/3783)

- \[x\] https://github.com/matrix-org/matrix-rust-sdk/issues/603
- \[ \] https://github.com/matrix-org/matrix-js-sdk/pull/2320
- \[ \] https://github.com/vector-im/element-android/issues/5845
- \[ \] https://github.com/vector-im/element-ios/issues/6078

**Comment by richvdh** [comment]
Given that the legacy mobile apps are essntially unmaintained, I guess we consider this done.
