### ISSUE TITLE
Message encrypted with different session from what is sent to recipients

### ISSUE THREAD

**Issue by uhoreg** [vector-im/element-meta#2425]
From a rageshake:

The recipient receives a Megolm session, say with session ID `aaaaaa`, and then receives room events encrypted with a different session ID, say `bbbbbb`.   Room messages encrypted with `bbbbbb` only start appearing after `aaaaaa` is sent.  Both `aaaaaa` and `bbbbbb` are for the same room ID.  Room messages encrypted with `aaaaaa` are never encountered.

So it seems like room messages are being encrypted using a different session from what is sent out to the recipients.

Unsure what client the sender is using (could even be a non-Element client).  Recipient in this case is using Element X iOS.

**Comment by richvdh** [comment]
Given we've only seen this once, and don't know which client was doing it, I don't think this is actionable as it stands. Let's reopen if we ever see it again (particularly if we get more details of the sender side client).
