### ISSUE TITLE
[Story] Render permalink as pills in the timeline

### ISSUE THREAD

**Issue by bmarty** [vector-im/element-meta#2431]
### Description

* As a user
* When a permalink is detected in a message
* I want to see nice permalink pills instead of long a techie link

Need to detect the link and resolve data: room name, room avatar for room permalink and user name, user avatar for user permalink

### Acceptance criteria

- TBD

### Leads

* Tech: <GitHub id>
* Design: <GitHub id>

### Size estimate

None

### Dependencies

- None

### Out of scope

- Nothing

### Open questions

```[tasklist]
### Questions
```

### Subtasks

```[tasklist]
### Android
```

```[tasklist]
### iOS
```

```[tasklist]
### Rust
```

```[tasklist]
### Other
```

### Android
- [ ] Design sign-off on completion
- [ ] QA sign-off on completion
- [ ] Product sign-off on completion

### iOS
- [ ] Design sign-off on completion
- [ ] QA sign-off on completion
- [ ] Product sign-off on completion

**Comment by mxandreas** [comment]
@bmarty There was already an issue for this: https://github.com/element-hq/element-meta/issues/2342. Could we close this as a duplicate?

**Comment by bmarty** [comment]
Yes, thanks.
