### ISSUE TITLE
Web App Team Tech Strategy 2022

### ISSUE THREAD

**Issue by novocaine** [vector-im/element-meta#246]
Strategic work to improve Element Web that we aim to complete in 2022.

- \[x\] Write tests as part of work as per https://github.com/matrix-org/matrix-js-sdk/blob/develop/CONTRIBUTING.md#tests
  - [New code coverage for matrix-react-sdk](https://sonarcloud.io/component_measures?id=matrix-react-sdk&metric=new_coverage&view=list)
  -  [New code coverage for matrix-js-sdk](https://sonarcloud.io/component_measures?metric=line_coverage&view=list&id=matrix-js-sdk)
- \[x\] https://github.com/vector-im/element-web/issues/21083
- \[x\] https://github.com/vector-im/element-web/issues/21965 \[KA\]
- \[x\] https://github.com/matrix-org/matrix-js-sdk/issues/2353 \[KA\]
- \[x\] https://github.com/vector-im/element-web/issues/21969
- \[x\] https://github.com/matrix-org/matrix-js-sdk/issues/801
- \[x\] https://github.com/vector-im/element-meta/pull/216
- \[x\] https://github.com/matrix-org/matrix-js-sdk/issues/2112
- \[ \] https://github.com/vector-im/element-web/issues/21967 \(needs owner\)
- \[ \] https://github.com/vector-im/element-web/issues/21968 \(needs owner\)
- \[ \] https://github.com/vector-im/element-web/issues/21738
- \[ \] https://github.com/vector-im/element-web/issues/21970 \(needs owner\)
- \[ \] https://github.com/vector-im/element-web/issues/21971
- \[ \] https://github.com/vector-im/element-web/issues/21972
- \[ \] https://github.com/vector-im/element-web/issues/22264
- \[ \] https://github.com/vector-im/element-web/issues/23543

**Comment by Johennes** [comment]
Closing this off since we're in '23 now. This year's agenda is tracked in https://github.com/vector-im/element-web/issues/24660.
