### ISSUE TITLE
Unable to query secret storage status

### ISSUE THREAD

**Issue by Nyanraltotlapun** [vector-im/element-meta#2471]
### Steps to reproduce

1. I probably used Nheko to create account initially. Signing other client works.
2. Try to login with Element-desktop, or Web, or Element X
3. Choose to enter recovery key or to reset keys

#### What did you expect?
Element accepts recovery key or resets it

#### What happened instead?
Element did not accepts recovery key (Invalid key)
And cannot reset it (Unable to query secret storage status)

But Nheko accepts recovery key and works as expected.

### Operating system

Arch Linux, Android, Web

### Application version

Element version: 1.11.69 Crypto version: Rust SDK 0.7.0 (068a0af), Vodozemac 0.6.0

### How did you install the app?

Arch repos, F-Droid

### Homeserver

matrix.org

### Will you send logs?

Yes

**Comment by Nyanraltotlapun** [comment]
In  logs I see such messages:

```
Error fetching backup data from server Error: Failed decoding Curve25519 key from base64: Invalid number of bytes for Curve25519, expected 32, got 45.
Error: Error: Failed decoding Curve25519 key from base64: Invalid number of bytes for Curve25519, expected 32, got 45.
```

Maybe make change to reset secret storage without checking how correct is what inside?

**Comment by Nyanraltotlapun** [comment]
Ok. I deleted keys buck-up by using API directly from python. But bloody hell! This needs to be fixed!

**Comment by dal00** [comment]
I have the same issue, could you please elaborate on what you did to solve this?

**Comment by Nyanraltotlapun** [comment]
> I have the same issue, could you please elaborate on what you did to solve this?

I am embarrassed to admit I deleted the code.... I thought that I never need it again because issue would be solved...
Maybe this can be helpful - https://playground.matrix.org/#delete-/_matrix/client/v3/room_keys/version/-version-

**Comment by bonswouar** [comment]
Same issue here `Invalid number of bytes for Curve25519, expected 32, got 45.`
I hope this can be fixed without using the api, I don't think users should need to use the API directly at any point

**Comment by wj25czxj47bu6q** [comment]
Two users on the homeserver I administer have also experienced this error.

One of them definitely used Nheko in some capacity (I didn't ask for details) and successfully reconfigured key backup from Element after the [`DELETE /_matrix/client/v3/room_keys/version/{version}` API](https://spec.matrix.org/v1.12/client-server-api/#delete_matrixclientv3room_keysversionversion) was used.

Regarding the second user, I am not sure what clients besides Element they have used and have not attempted to erase their key backup at this time. (I will edit this comment with any updates.)

**Comment by richvdh** [comment]
I was able to reproduce this by configuring a backup with a malformed `public_key` in the `auth_data`. More to the point, I was *not* able to reproduce it on develop (the backup doesn't work, obviously, but I was able to successfully reset secret storage).

I think this has been fixed by https://github.com/element-hq/element-web/pull/28290.
