### ISSUE TITLE
Make Web consistent with EX crypto UX

### ISSUE THREAD

**Issue by pmaier1** [vector-im/element-meta#2487]
# Input gathering
## Web side
- Remove ability to choose your own Recovery passphrase
- Key reset during sign-in
- Settings (related: https://github.com/element-hq/element-web/issues/26468)
  - Key storage (previously 'secure backup' or 'chat backup' in EX)
  - Move footguns to developer mode
- Update terminology to match MSC4161
- Invisible crypto
  - Force device verification during sign-in
  - TOFU
  - Exclude non-cross-signed devices
- Design consistency between EX and Web

**Comment by BillCarsonFr** [comment]
Next Steps:

- [ ] Proper gap analysis between EX / WebR

**Comment by mxandreas** [comment]
For the sake of clarity, I am closing this ticket as we're tracking these problems as part of the internal roadmap ticket [ER-69](https://element-io.atlassian.net/browse/ER-69).

[ER-69]: https://element-io.atlassian.net/browse/ER-69?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
