### ISSUE TITLE
[Prep] EX: Remove the SS proxy waiting list

### ISSUE THREAD

**Issue by manuroe** [vector-im/element-meta#2498]
### Description

It will be nore more required with SSS and was never used anyway.

[Internal discussion](https://matrix.to/#/!cnVVNLKqgUzNTOFQkz:matrix.org/$T5D-kjYe9T7Cwvx94Hrlw3rzLGs7h3RTv0QsuQ1447s?via=element.io&via=matrix.org&via=jki.re)

<details>
<summary>The screen to kill</summary>
<img src="https://github.com/user-attachments/assets/9b403723-acd2-4db2-b0e4-452a8f13b4ce"/>
</details>

# Acceptance criteria
- This flow does not exist anymore in the code

# Size estimate
S/M/L

# Dependencies    
- None

# Out of scope
- 

# Subtasks
```[tasklist]
### Android
- [ ] https://github.com/element-hq/element-x-android/issues/3293
```

```[tasklist]
### iOS
- [ ] https://github.com/element-hq/element-x-ios/issues/3147
```

**Comment by bmarty** [comment]
Done on Android and iOS, lets close this issue.
