### ISSUE TITLE
Invisible Crypto: EX iOS: display a warning when an *unverified* user changes identity

### ISSUE THREAD

**Issue by andybalaam** [vector-im/element-meta#2525]
Followup to https://github.com/element-hq/element-meta/issues/2492.  Part of https://github.com/element-hq/element-meta/issues/2491, itself part of [Invisible crypto](https://github.com/element-hq/crypto-internal/issues/282).

When an unverified user changes their identity, we need to make our user aware of this. In the long term, the intention is just to show a notice in the timeline (#2493); however, that is difficult to implement and we need a stop-gap.

This task is for Element X iOS.

The proposal is to show a warning above the composer, in much the same way as we would for *verified* users (#2491), but without locking the composer.

Figma designs:

* [EXI](https://www.figma.com/design/0oUTCbYhROEDprSp7bdWhx/Identity-Changes?node-id=340-11002&t=S7GYP1iJFJMzIRid-0)

![Image](https://github.com/user-attachments/assets/2343f21f-6527-4b52-91b3-3d6876fac16c)

**Comment by mxandreas** [comment]
@stefanceriu I am guessing you're taking care of this for iOS, if not please tag who is.

@bmarty Asked a question what should the Learn more link do. We did a quick iteration with @americanrefugee and landed on the following.

1. The Learn more link will open this [help screen](https://www.figma.com/design/0oUTCbYhROEDprSp7bdWhx/Identity-Changes?node-id=787-21682&t=t0jcMRgIDEfiBleY-4) - there is an equivalent for [Android](https://www.figma.com/design/0oUTCbYhROEDprSp7bdWhx/Identity-Changes?node-id=787-36289&t=zEqiVBEF1csFfM58-4) and [Web](https://www.figma.com/design/0oUTCbYhROEDprSp7bdWhx/Identity-Changes?node-id=801-20095&t=zEqiVBEF1csFfM58-4) in Figma.

Samples:

![image](https://github.com/user-attachments/assets/f7e42c10-a5f1-49ea-b44b-88236890ec85)
![image](https://github.com/user-attachments/assets/b1839836-db16-4138-bb69-572abc67f974)
![image](https://github.com/user-attachments/assets/5f14a37f-7621-48f8-88b5-bdce9364be4c)

2. The **Go to FAQ** would then open browser that will lead to https://element.io/help#encryption (final URL TBD - we have the content but still need to publish it).

@andybalaam @richvdh @BillCarsonFr for visibility.

**Comment by americanrefugee** [comment]
[This what I have for Web](https://www.figma.com/design/0oUTCbYhROEDprSp7bdWhx/Identity-Changes?node-id=801-20095&t=QjspuOPA3vNH0uGH-4)

**Comment by mxandreas** [comment]
Updated my comment above to have the complete info.

**Comment by stefanceriu** [comment]
@mxandreas This is a bit unexpected to be honest. All our 'learn more' kind of links always point to somewhere on the web i.e. https://github.com/element-hq/element-x-ios/blob/e6f4dd33a0326081a03553f3d8f6a21ca3c2041b/ElementX/Sources/Application/AppSettings.swift#L116-L126 

Why are we building a custom screen for this one when we can easily send people to a new section on the same https://element.io/help#encryption? (Especially as this is a full screen pushed onto the navigation stack which makes it extra hard to implement)

**Comment by mxandreas** [comment]
The idea was that it would be more "accessible", but if it increases complexity of the implementation, then it is not worth it, I think. cc @americanrefugee - I am fine this link to go directly to the web and have all the content there. Let me know if you have any further thoughts.

**Comment by mxandreas** [comment]
The **Learn more** link should lead to: https://element.io/help#encryption18 - let's skip the in-app screen to save effort for now.

Product marketing did some final touches on the content so that it would fit into the FAQ format. There are a couple of details that we could improve IMO or make it more specific but I did not want to do another iteration and block the work. We can update content on the website independently.

cc @bmarty @uhoreg

**Comment by mxandreas** [comment]
The correct link is https://element.io/help#encryption18 - fixed it above as well but just in case. Sorry for confusion.
