### ISSUE TITLE
Ability to ban users after they leave a room

### ISSUE THREAD

**Issue by TheJaredWilcurt** [vector-im/element-meta#2529]
#### Why would you like to do it?

* Spam bot enters room.
* Spam bot sends spam message.
* Spam bot leaves room.
* I delete message
* Spam bot comes back
* Spam bot sends spam message
* Spam bot leaves room
* I delete message

You should be able to ban accounts from being able to come back. Bans with the word "spam" in the reason should be sent to an automated spam filter system and used as part of the criteria to prevent accounts from joining/spamming other rooms.

#### How would you like to achieve it?

Any of these would work:

* User search should show users that left recently, or were ever in the room, at least to those with ban powers. This is the only place I know of where you can get the option to ban a user.
* When you go to "remove" a message, it should have an option to ban the user, this is the most obvious place to put it.
* When you click on the message `...` it has:

```
Forward
Share
Report
View Source
---
Remove
```

It should have `Ban` under `Remove`, even if the user left the chat.

### Have you considered any alternatives?

Couldn't find any other way to ban users that have already left.

**Comment by solbu** [comment]
I am a moderator in several rooms, and I think I have an answer for you.

When a user leaves the room, you can still click on the user profile image in the chat.
The message will have an icon or their profile picture , and a text saying «UserName left the room»
The icon is always clickable and opens their profile, and if you're a moderator you can Ban them from the room, there. You can also remove all their messages in one go in the same view.

It is not _obvious_ that the profile icons in the chat are clickable. :-)
