### ISSUE TITLE
Verification | Run Sanity test for verification against all clients currently in prod

### ISSUE THREAD

**Issue by BillCarsonFr** [vector-im/element-meta#253]
Test Plan:
https://docs.google.com/spreadsheets/d/1Sjjfi2EztTni6Hd1OsciB19IJxUd\_4-9I6zX5S7ftwk/edit#gid=1359908241

Concerning Issues:
https://github.com/vector-im/element-android/issues/5910
https://github.com/matrix-org/element-android-rageshakes/issues/37173
https://github.com/matrix-org/element-android-rageshakes/issues/37172
https://github.com/matrix-org/element-android-rageshakes/issues/37171
also to to close/tirage https://github.com/vector-im/element-web/issues/21021

**Comment by richvdh** [comment]
Closing this in favour of https://github.com/vector-im/element-meta/issues/2165

**Comment by kegsay** [comment]
Added the following as goals for complement-crypto:

Key Verification: (Short Authentication String)
- [ ] Happy case Alice <-> Bob key verification.
- [ ] Happy case Alice <-> Bob key verification over federation.
- [ ] Happy case Alice <-> Alice key verification (different devices).
- [ ] A MITMed key fails key verification.
- [ ] Repeat all of the above, but for QR code. (render QR code to png then rescan).
- [ ] Repeat all of the above, but for Emoji representations of SAS.
- [ ] Verification can be cancelled.
- [ ] Verification can be cancelled over federation.
