### ISSUE TITLE
Invisible Crypto: A clearer message to the user when sending fails due to their own unverified devices

### ISSUE THREAD

**Issue by mxandreas** [vector-im/element-meta#2534]
### Description

On our way to invisible crypto (in which all users devices are either fully verified or fully ignored) we have implemented a stop-gap solution for security purposes:

**Given** Alice has explicitly verified Bob's identity
**And** Bob has unverified devices
**When** Alice is trying to send a message to Bob
**Then** The message fails to send
**And** Bob needs to take an action to decide what will happen next.

The visuals look as follows:

![image](https://github.com/user-attachments/assets/70167e27-a1c5-4e11-92aa-f601a69fb3b7)
![image](https://github.com/user-attachments/assets/93416fc9-bc2d-4b0f-8312-b2bfa631bbc7)

It was not realized that the same will happen when Alice == Bob, meaning that user's own devices aren't verified. For security reasons this needs to remain, as otherwise one could inject a device on behalf of the user and start listening to their messages without the user noticing that. However, to make this more user friendly, the text of the message to the user should be changed so that it is clearer for them what is happening.

Proposed copy of the message when its the user's own device that is unverified.

**Title**: Your message was not sent because you have not verified one or more of your devices
**Description**: One or more of your devices are unverified. You can send the message anyway, or you can cancel for now and try again later after you have verified all of your devices.

Links to the [design](https://www.figma.com/design/0oUTCbYhROEDprSp7bdWhx/Identity-Changes?node-id=13-4450&t=tRtKLbQQzdJjOg2S-4) in Figma for convenience.

### Acceptance criteria

- User can see the tailored error message when one or more of their own devices are unverified.

### Leads

* Tech: <GitHub id>
* Design: <GitHub id>

### Size estimate

None

### Dependencies

- None

### Out of scope

- Nothing

### Open questions

```[tasklist]
### Questions
```

### Subtasks

```[tasklist]
### Android
- [ ] https://github.com/element-hq/element-x-android/issues/3484
```

```[tasklist]
### iOS
- [ ] https://github.com/element-hq/element-x-ios/issues/3350
```

```[tasklist]
### Rust
```

```[tasklist]
### Other
```

### Android
- [ ] Design sign-off on completion
- [ ] QA sign-off on completion
- [ ] Product sign-off on completion

### iOS
- [ ] Design sign-off on completion
- [ ] QA sign-off on completion
- [ ] Product sign-off on completion

**Comment by mxandreas** [comment]
@americanrefugee Could you please review the copy I suggested and then add the corresponding variant also into Figma. If you need further clarifications, let me know.

**Comment by americanrefugee** [comment]
Here is the design for [iOS](https://www.figma.com/design/0oUTCbYhROEDprSp7bdWhx/Identity-Changes?node-id=516-7991&t=nRSCtecC2WQuRz5f-4) and [Android](https://www.figma.com/design/0oUTCbYhROEDprSp7bdWhx/Identity-Changes?node-id=517-20144&t=nRSCtecC2WQuRz5f-4)

**Comment by manuroe** [comment]
The update has been done both on Android and iOS. It was part for the releases we made for the Matrix Conf. Can we close this issue?

**Comment by mxandreas** [comment]
Done
