### ISSUE TITLE
Rename "invisible crypto" config setting to something else we agree on

### ISSUE THREAD

**Issue by andybalaam** [vector-im/element-meta#2536]
```[tasklist]
### Tasks
- [ ] https://github.com/element-hq/element-x-ios/issues/3322
- [ ] https://github.com/element-hq/element-x-android/issues/3528
```

**Comment by pmaier1** [comment]
**Proposal**

> Ignore unverified devices when sending/receiving messages

**Comment by richvdh** [comment]
The js-sdk exposes a separate mode called "transition mode". Apparently this means:

* Encryption will throw an error if a verified user has an unsigned device, or if a verified user replaces their identity.
* Events are decrypted only if they come from cross-signed devices, or devices that existed before the Rust crypto SDK started tracking device trust: other events will result in a decryption failure.

(See https://github.com/matrix-org/matrix-js-sdk/pull/4407)

Now that I look at that list, I can't see why it would ever be useful. @BillCarsonFr: any ideas?

**Comment by richvdh** [comment]
We're doing some brainstorming to figure out what we actually want here

**Comment by richvdh** [comment]
> Now that I look at that list, I can't see why it would ever be useful. @BillCarsonFr: any ideas?

After discussion: we believe that we do *not* need a separate "transition mode" at the application level, but we do need some flexibility at the js-sdk level. We'll need some changes to the current js-sdk impl though: https://github.com/matrix-org/matrix-js-sdk/issues/4428.

**Comment by richvdh** [comment]
Following a [suggestion](https://github.com/element-hq/element-x-ios/issues/3322#issuecomment-2373209887) by @mxandreas, I think we're instead converging on:

> Exclude insecure devices when sending/receiving messages

**Comment by BillCarsonFr** [comment]
> Following a [suggestion](https://github.com/element-hq/element-x-ios/issues/3322#issuecomment-2373209887) by @mxandreas, I think we're instead converging on:
> 
> > Exclude insecure devices when sending/receiving messages

Right, will update EIX/EAX side when doing https://github.com/element-hq/crypto-internal/issues/353 and https://github.com/element-hq/crypto-internal/issues/354

**Comment by BillCarsonFr** [comment]
> > Following a [suggestion](https://github.com/element-hq/element-x-ios/issues/3322#issuecomment-2373209887) by @mxandreas, I think we're instead converging on:
> > > Exclude insecure devices when sending/receiving messages
> 
> Right, will update EIX/EAX side when doing [element-hq/crypto-internal#353](https://github.com/element-hq/crypto-internal/issues/353) and [element-hq/crypto-internal#354](https://github.com/element-hq/crypto-internal/issues/354)

In review in https://github.com/element-hq/element-x-ios/pull/3358 and https://github.com/element-hq/element-x-android/pull/3569
