### ISSUE TITLE
Show Polls participant

### ISSUE THREAD

**Issue by Thatoo** [vector-im/element-meta#2537]
#### What would you like to do?
We would like to know who participate to a poll to be able to ping those who didn't participate yet.

#### Why would you like to do it?
If we need that everybody participate to a poll, we need to know who did already and who we should ping to remind them to participate.

#### How would you like to achieve it?
Have an option to be able to display who participate to a poll.

### Have you considered any alternatives?

Nextcloud polls.

**Comment by nitn3lav** [comment]
duplicate of #1349

**Comment by Thatoo** [comment]
indeed but that's because when I look in element-hq/element-web/issue, I could not find any issue talking about it. Element users don't search in element-hq/element-meta/issues.
Sorry
