### ISSUE TITLE
New posthog codes for new decryption failure reasons

### ISSUE THREAD

**Issue by richvdh** [vector-im/element-meta#2541]
We've recently added new decryption failure reasons; in particular:

  *  messages sent from devices which their owners have not cross-signed
  * messages sent from users who we had previously verified, but who have now rotated their identity.

We should add new PostHog reason codes for these failure reasons, and wire up the applications to send them correctly.

* [x] New Error "names" in `analytics-events` project https://github.com/matrix-org/matrix-analytics-events/pull/114
* [x] Update React SDK to send new codes
* [x] Update Rust SDK to send new codes https://github.com/matrix-org/matrix-rust-sdk/pull/4126
* [x] #2597
* [x] https://github.com/element-hq/element-x-android/issues/3626
* [x] https://github.com/element-hq/element-x-ios/issues/3380
* [x] EXA support for Posthog code for messages from users with verification violation https://github.com/element-hq/element-x-android/pull/3729
* [x] EXI support for Posthog code for messages from users with verification violation. Done as part of this PR https://github.com/element-hq/element-x-ios/pull/3442

Not strictly the same cause but may be trivial to fix at the same time:

* https://github.com/element-hq/element-meta/issues/2581
* https://github.com/element-hq/element-meta/issues/2589

**Comment by BillCarsonFr** [comment]
I created an issue on rust https://github.com/matrix-org/matrix-rust-sdk/issues/4048 that is covering the work on rust I think.
Linking here so we can discuss it

**Comment by richvdh** [comment]
> I created an issue on rust [matrix-org/matrix-rust-sdk#4048](https://github.com/matrix-org/matrix-rust-sdk/issues/4048) that is covering the work on rust I think.

That issue lays some groundwork, but does not update the posthog integration in the rust sdk

**Comment by uhoreg** [comment]
matrix-analytics-events PR: https://github.com/matrix-org/matrix-analytics-events/pull/114

**Comment by uhoreg** [comment]
@BillCarsonFr is doing the EX bits, and I'm doing the EW bits

**Comment by uhoreg** [comment]
React SDK PR: https://github.com/element-hq/element-web/pull/28292 (in draft until tests written)

**Comment by BillCarsonFr** [comment]
> Not strictly the same cause but trivial to fix at the same time:

No trivial, need to be handled separatly

**Comment by richvdh** [comment]
I've moved this to the "Trust & Decoration" workstream, since the codes affected here will only affect devices with the "Exclude insecure devices when sending/receiving messages" labs option enabled, for now.
