### ISSUE TITLE
[Story] EX: Show in user's profile when they have been verified

### ISSUE THREAD

**Issue by mxandreas** [vector-im/element-meta#2569]
### Description

There are 2 related-parts here:
* Show if a user has been verified (and their verified identity has not changed)
* Show a hint-button that verification needs to be done on web (unless the user is already verified)

#### Show if a user has been verified
* As a user
* I want to see if a user is verified (and their verified identity has not changed)
* So that I would not be confused if the verification did not work or they have changed their identity

For now, only show this on the person's profile by showing the green badge and not showing the (always-disabled) button to verify.

Designs:
* [iOS](https://www.figma.com/design/0oUTCbYhROEDprSp7bdWhx/Identity-Changes?node-id=895-8648&t=wA9gdldm7gs1xXoo-4)
* [Android](https://www.figma.com/design/0oUTCbYhROEDprSp7bdWhx/Identity-Changes?node-id=896-11306&t=wA9gdldm7gs1xXoo-4)

![image](https://github.com/user-attachments/assets/6ac807b2-8b7f-41ec-b18b-50c259fde516)

#### Show a hint that verification needs to be done on EW

* As a user 
* I want to know that user verification is not yet supported by EX
* So that I would not waste time for looking for this functionality in the app

Designs:
* [iOS](https://www.figma.com/design/0oUTCbYhROEDprSp7bdWhx/Identity-Changes?node-id=895-8347&t=wA9gdldm7gs1xXoo-4)
* [Android](https://www.figma.com/design/0oUTCbYhROEDprSp7bdWhx/Identity-Changes?node-id=896-11141&node-type=instance&t=wA9gdldm7gs1xXoo-11)

![image](https://github.com/user-attachments/assets/403a25b7-dd5c-4cf8-b1dd-e433e9845c6a)

### Acceptance criteria

- TBD

### Size estimate

None

### Dependencies

- None

### Out of scope

- Nothing

### Open questions

```[tasklist]
### Questions
```

### Subtasks

```[tasklist]
### Android
- [ ] https://github.com/element-hq/element-x-android/issues/3684
```

```[tasklist]
### iOS
- [ ] https://github.com/element-hq/element-x-ios/issues/3413
```

```[tasklist]
### Rust
- [ ] https://github.com/matrix-org/matrix-rust-sdk/pull/4142
```

```[tasklist]
### Other
```

**Comment by manuroe** [comment]
Tested on the today nightlies of EXA and EXI. Everything works as expected. The UX is pretty clear. So nice!

We raised the fact the user verification is not available from a DM but it needs more thinking on the UX and maybe cross work with EW: we want to improve and revisit the DM info screen.
