### ISSUE TITLE
Tracking enabling/disabling the Threads beta

### ISSUE THREAD

**Issue by novocaine** [vector-im/element-meta#258]
Create an event to track when users enable or disable the threads beta.

This can be used to track:

- A funnel starting point for how threads are engaged with after enabling the beta
- Opt-in/out rates for the beta

It seems more useful to have an event than a user property, for the purposes of creating funnels etc

**Comment by novocaine** [comment]
Would this be part of a new Setting event?

**Comment by daniellekirkwood** [comment]
Hey @t3chguy did we decide for or against this?

**Comment by t3chguy** [comment]
@daniellekirkwood I wasn't aware a decision was ever reached, but I'm not involved in many Producty decision calls so likely would've missed it.

**Comment by daniellekirkwood** [comment]
ok - well I didn't know it was an open question to be answered so I assumed this was a engineering request. 
If it hadn't come to you (through discussion or assignment) then let's close it. It's likely to late to implement it anyway.
