### ISSUE TITLE
EX: support new posthog UTD properties

### ISSUE THREAD

**Issue by richvdh** [vector-im/element-meta#2582]
We [previously](https://github.com/element-hq/element-meta/issues/2332) added some extra Posthog properties to UTD reports sent by Element Web and the classic mobile apps. We need to do the same work on EX.

It looks like the new properties we need to support are:

 * `eventLocalAgeMillis`: Not actually implemented on Web: do we need it? It's probably pretty easy so maybe we will just do it anyway.
 * `userTrustsOwnIdentity`: presumably always `true` on EX
 * `isFederated`
 * `isMatrixDotOrg`
 * ~~`wasVisibleToUser`: not sure if we have this information, or if it needs to wait for a larger refactor of the UTD reporting code.~~ Factored out to https://github.com/element-hq/element-meta/issues/2659

Already implemented:
 * `timeToDecryptMillis`
 
Tasks:
 * [x] rust sdk: https://github.com/matrix-org/matrix-rust-sdk/pull/4360
 * [x] ffi bindings: https://github.com/matrix-org/matrix-rust-sdk/pull/4404
 * [x] update kotlin wrapper: https://github.com/matrix-org/matrix-rust-components-kotlin/actions/runs/12282985162
 * [x] element-x-android: https://github.com/element-hq/element-x-android/pull/4020
 * [x] element-x-ios: https://github.com/element-hq/element-x-ios/pull/3612

**Comment by andybalaam** [comment]
@mxandreas will follow up with @richvdh on priority of this.

**Comment by andybalaam** [comment]
@richvdh will split out `wasVisibleToUser` into a separate task because it is more complex than the others.

**Comment by richvdh** [comment]
> @richvdh will split out `wasVisibleToUser` into a separate task because it is more complex than the others.

Now done: https://github.com/element-hq/element-meta/issues/2659
