### ISSUE TITLE
Report withheld messages to posthog using `RoomKeysWithheldForUnverifiedDevice` code

### ISSUE THREAD

**Issue by richvdh** [vector-im/element-meta#2589]
There is a specific Posthog error code for reporting UTDs that are due to withheld messages: we should (make sure we) use it.

* [x] https://github.com/matrix-org/matrix-rust-sdk/issues/4270

**Comment by uhoreg** [comment]
Looks like we use the right code in EW: https://github.com/element-hq/element-web/blob/83777a6c5788c204782c28bc0f225c4d53b4936b/src/DecryptionFailureTracker.ts#L76

**Comment by andybalaam** [comment]
Presumably this is just Element X then

**Comment by andybalaam** [comment]
This should only affect people receiving messages from someone who has turned on "only encrypt to verified devices" in Element Web.

**Comment by BillCarsonFr** [comment]
Done:

Rust: https://github.com/matrix-org/matrix-rust-sdk/pull/4305
EXI: https://github.com/element-hq/element-x-ios/pull/3586
EXA: https://github.com/element-hq/element-x-android/pull/3999

![image](https://github.com/user-attachments/assets/25f7dc37-95b0-469a-8e15-2c3a494c22a6)
