### ISSUE TITLE
Update Posthog graph to exclude new Expected UTDs codes

### ISSUE THREAD

**Issue by BillCarsonFr** [vector-im/element-meta#2597]
Update the posthog `Visible UTD` [action](https://posthog.element.io/data-management/actions/21) to filter out the new expected UTD codes:
https://github.com/matrix-org/matrix-analytics-events/pull/114/files

**Comment by andybalaam** [comment]
Excluded `name=ExpectedSentByInsecureDevice` and `name=ExpectedVerificationViolation` from [Visible UTD](https://posthog.element.io/data-management/actions/21)

**Comment by richvdh** [comment]
I've moved this to the "Trust & Decoration" workstream, since the codes affected here will only affect devices with the "Exclude insecure devices when sending/receiving messages" labs option enabled, for now.
