### ISSUE TITLE
MSC3814: Document new dehydrated device format (probably just a concatenation of the various bits of information needed, similar to existing pickle format)

### ISSUE THREAD

**Issue by BillCarsonFr** [vector-im/element-meta#2602]
Currently, the dehydrated device is just a libolm-style pickle, and contains several unnecessary fields (some of which wouldn't make sense for other implementations). The MSC already has comments on these fields.

**Comment by uhoreg** [comment]
Done in https://github.com/matrix-org/matrix-spec-proposals/pull/3814/commits/11149e4bc0c321854f04fff85356e256bc4fab3a
