### ISSUE TITLE
[Story] Element X: Hide the "Join" button after the call has started (Android only)

### ISSUE THREAD

**Issue by fkwp** [vector-im/element-meta#2608]
### Description

Currently the Call Symbol on the top right of a room will start a new call or becomes a green "Join button" if a call is currently present. In both cases pressing the button starts the Element Call widget.

Now with the Picture-in-Picture feature you can still see the green "Join button" while participating that call which is misleading. This is the case only for Android version, iOS is already hiding the "Join button". It is desired to make Android consistent with it.

Note that this is room specific, meaning that the Join button would be hidden only in the room where the user has joined. Other rooms that have ongoing calls (that the user has not joined) are still showing the Join button.

### Acceptance criteria

- TBD

### Size estimate

None

### Dependencies

- None

### Out of scope

- Nothing

### Open questions

```[tasklist]
### Questions
```

### Subtasks

```[tasklist]
### Android
```

```[tasklist]
### iOS
```

```[tasklist]
### Rust
```

```[tasklist]
### Other
```

**Comment by mxandreas** [comment]
@fkwp Actually, in iOS we're already hiding the Join button. Therefore we would do the same on Android. As it is not critical to have the hang up button there, I would keep it simple. Do you agree?

**Comment by fkwp** [comment]
> @fkwp Actually, in iOS we're already hiding the Join button. Therefore we would do the same on Android. As it is not critical to have the hang up button there, I would keep it simple. Do you agree?

The thing I like about the hangup button is that you can also notice in the timeline view of that room that a call is in progress. @amshakal wdyt?
