### ISSUE TITLE
Database migration UX

### ISSUE THREAD

**Issue by BillCarsonFr** [vector-im/element-meta#263]
When we will publish Element R to the store, we will have to migrate the way internal data are stored from the existing crypto SDK to the Rust crypto SDK.
This can take some time, and we will need to provide some feedbacks to the user.

This would appear the first time you launch the app after updating.
We can technically display a progress bar.
We would need some copy better than `App is performing a database migration, please be patient` ;\)

**Comment by amshakal** [comment]
[Proposed solution](https://www.figma.com/file/0LOheXPc2lZVOQUFHk8tS0/Database-Migration?node-id=2%3A2411):

<img width="568" alt="Screenshot 2022-06-01 at 1 12 50 pm" src="https://user-images.githubusercontent.com/85162587/171401695-ffde4a98-d59f-42ef-84e5-7aff520008fb.png">

 
Add a progress screen after the splash screen to show progress. This is the happy path. We need to discuss what happens incase the device is unable to successfully complete migration.

**Comment by richvdh** [comment]
Closing this in favour of https://github.com/element-hq/element-web/issues/26773.
