### ISSUE TITLE
EX Expected UTDs: use a different message for expected UTDs (parity with web)

### ISSUE THREAD

**Issue by BillCarsonFr** [vector-im/element-meta#2638]
Parity with web

EX only says `Waiting for this message`

**Historical expected UTDs:**

See https://github.com/matrix-org/matrix-react-sdk/pull/12391

Web displays different messages for historical expected UTDs, with some call to action if applicable:
- `Historical Messages are not availble on this device` => When Key storage is not configured
- `You need to verify this device to access historical messages` => When there is backup but the decryption key is missing?

**Pre join UTD:**

Web says `You don't have access to this message`

**Comment by andybalaam** [comment]
This needs to build on top of the types introduced in https://github.com/element-hq/element-meta/issues/2581

**Comment by BillCarsonFr** [comment]
- [x] https://github.com/element-hq/element-x-android/pull/4044
- [x] https://github.com/element-hq/element-x-ios/pull/3625
