### ISSUE TITLE
Enable square profile pictures?

### ISSUE THREAD

**Issue by Merulox** [vector-im/element-meta#273]
### Your use case

In the appearance settings, it would be nice if we could enable square profile pictures instead of circle ones. Thank you for your time!

**Comment by daniellekirkwood** [comment]
Thanks so much for the suggestion, @Merulox 

At this time we use squares for Spaces and so wouldn't be able to also use squares for a profile icon.
I'm going to close this issue as "will not do" for now. 

Thank you for sharing your idea with us - keep the suggestions coming.
