### ISSUE TITLE
Add option to show avatar/displayName changes only for direct chats

### ISSUE THREAD

**Issue by MurzNN** [vector-im/element-meta#337]
Please add option to show avatar/displayName changes only for direct chats. At now we can only globally enable it, but info that some person in room with 2000+ members is change avatar is not useful for most users, instead in his direct chats - very useful.

**Comment by MadLittleMods** [comment]
Related to https://github.com/vector-im/element-meta/issues/1633

**Comment by MadLittleMods** [comment]
Duplicate of https://github.com/vector-im/element-meta/issues/256
