### ISSUE TITLE
2FA for logins

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-meta#345]
When I log in (using a username/password or 3PID/password combo), we should give users the option to also require a two factor authentication (or multi-factor authentication) via other channels.  Options are:

 * 2FA by email
 * 2FA by SMS (MSISDN)
 * 2FA by matrix, using another device.

**Comment by brainbug89** [comment]
Still no 2FA? 🙄

**Comment by stevenaldinger** [comment]
bump just to see if vector im took up @jaekwon on offering to sponsor if nothing else.

2 factor isn't optional at this point imo but I really like the potential of this project so hate to bail on the thing. will contribute myself eventually but reinventing-the-wheel with my personal time is too much for a project I'm just now considering adopting.

my software engineering company would take the contract work to implement it for sure though 😄

**Comment by stevenaldinger** [comment]
let me scope it out a little bit and see what it really takes to make it a reality and I'll update. client is js which I'm really comfortable with and have worked with this sort of thing before, synapse/matrix server is python and I might make a mess lol (but with test coverage! 🤣), haven't looked into if they're both needing updates at this point or what the deal is. I'll try to lead the hunt this week though, I'm interested.

**Comment by dngray** [comment]
> While planning this feature, you should also take into account webauthn (https://www.w3.org/TR/webauthn/)

One of the things I like about [WebAuthn](https://webauthn.guide/) is:

> The public key is not secret, because it is effectively useless without the corresponding private key. The fact that the server receives no secret has far-reaching implications for the security of users and organizations. Databases are no longer as attractive to hackers, because the public keys aren’t useful to them.

It seems WebAuthn is a even more secure option than even TOTP so I hope it doesn't overlooked just because everyone is already used to TOTP.

WebAuthn will have clear support in all browsers and that much is apparent being a part of the W3.

**Comment by rugk** [comment]
Wtf, Matrix, what happened to you? People would have paid you for this feature?

> We'll pay for this to be implemented by the end of January, just send us a service contract.

https://github.com/vector-im/riot-web/issues/2772#issuecomment-352947462

Also the [French goverment is a client of yours](https://matrix.org/blog/2018/04/26/matrix-and-riot-confirmed-as-the-basis-for-frances-secure-instant-messenger-app) that may very much appreciate such a feature…

**Comment by ptman** [comment]
> Also the [French goverment is a client of yours](https://matrix.org/blog/2018/04/26/matrix-and-riot-confirmed-as-the-basis-for-frances-secure-instant-messenger-app) that may very much appreciate such a feature…

They most likely use some kind of SSO (SAML? CAS? OpenID Connect?) that handles 2FA on another layer. Like keycloak. But I would not recommend SAML as you can now use OpenIDC.

**Comment by ara4n** [comment]
In case anyone is wondering why this hasn’t happened yet: we’ve found that most people who want 2FA are also using SSO, and so can use the SSO provider (keycloak etc) for this.

However, we still want to get it natively into Matrix, but it’s in the middle of the feature backlog.

**Comment by JonathanWilbur** [comment]
I'd like to point out that I have an [outstanding feature request](https://github.com/vector-im/element-meta/issues/1840) that I reported for TLS / X.509 client certificate authentication. If implemented, it would require no change at all to Synapse, Dendrite, or the Matrix protocol, and would still provide an additional factor of very robust, well-understood authentication.

**Comment by CoolGaM3r215** [comment]
TOTP would be nice if added

**Comment by thalesfsp** [comment]
Since 2016.. and counting

**Comment by SergeyDjam** [comment]
> 2FA by matrix, using another device.

TOTP? FreeOTP, Aegis, Google Authenticator, hardware OTP?

**Comment by RyanSquared** [comment]
> > 2FA by matrix, using another device.
> 
> TOTP? FreeOTP, Aegis, Google Authenticator, hardware OTP?

I believe the intent was to use the second device, already signed into Matrix, as a 2FA method.

**Comment by jbastruz** [comment]
Hi guys! I just read this topic, and I'm quite interested! Do we have any updates on the 2FA? Is it still under discussion or is it in production?

**Comment by Mikaela** [comment]
I think Element has given up on this and moved the issue to https://areweoidcyet.com/

2FA/MFA currently depends on login system of your homeserver

**Comment by erebion** [comment]
> "2FA by matrix, using another device." - This is definitely needed, especially by a "Verified" alternate device (text, emoji, etc).

Steal a device or get access for half a minute, add a device... This does not seem to be a good idea. I'd go with WebAuthn instead.

Or alternatively a way to disable this and require entering the password to enable this again.

**Comment by erebion** [comment]
Also, WebAuthn. The standard many sites now adopt. Much better than TOTP, but for the users that don't have a WebAuthn device, TOTP is still better than no 2FA at all.

**Comment by ptman** [comment]
OIDC seems to be the way forward (for synapse, dendrite just dropped PR for OIDC). So make sure you pick an auth provider that supports 2FA. https://areweoidcyet.com/ . WebAuthn is supported by a very wide range of devices since google/apple/microsoft passkeys are built on top of webauthn.
