### ISSUE TITLE
Displaying UISIs

### ISSUE THREAD

**Issue by amshakal** [vector-im/element-meta#35]
Explore UI changes for how UISI messages are displayed based on technical requirements mentioned here: https://docs.google.com/document/d/1gsYukZUbWbIVDzd02eDluj1fzXEBke4lp5yYFY3dB0s/edit

**Comment by BillCarsonFr** [comment]
Element android displays "Waiting for this message..."  and additional info when clicked.
Confuse users because they wait..

<img width="394" alt="image" src="https://user-images.githubusercontent.com/9841565/138074686-51b53071-1585-465d-ab9c-f76aca0f4d36.png">

**Comment by amshakal** [comment]
Figma file with explorations: https://www.figma.com/file/a1NWmg6mOi2VZuSgaJx6nD/Displaying-UISI?node-id=1%3A12315
