### ISSUE TITLE
Text after a quote gets dragged into the quote

### ISSUE THREAD

**Issue by andybalaam** [vector-im/element-meta#357]
### Steps to reproduce

1. In the message composer
2. Type this message:

```
Before
> Quoted text
After
```
![image](https://user-images.githubusercontent.com/76812/170271581-5e7148c5-5c90-4f18-a34f-ccc1225a46ce.png)

4. Send the message

#### What did you expect?

I expected to see only the words "Quoted text" as the quote, and the word "After" to appear as non-quoted text.

Something like this: 
![image](https://user-images.githubusercontent.com/76812/170271748-1840d273-deb8-46c4-811c-ad44b0ee30b5.png)

#### What happened instead?

The word "After" was included in the quote: ![image](https://user-images.githubusercontent.com/76812/170271651-0ecf031a-0a6c-453a-9f60-693f9a611e69.png)

When I edit the message, Element Web pretends I typed it like that:

```
Before
> Quoted text
> After
```

(Related: vector-im/element-web#10725 )

### Operating system

Ubuntu 21.10

### Browser information

Firefox 100.0

### URL for webapp

https://develop.element.io

### Application version

Element version: 863e5f6c7897-react-90dfb8d61f88-js-ad030bfc1f91 Olm version: 3.2.8

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by t3chguy** [comment]
This is just how markdown works

<img width="1188" alt="image" src="https://user-images.githubusercontent.com/2403652/170272486-18383080-b8da-4e0e-b600-301dc498d493.png">


before
> quote
after

Even here

**Comment by andybalaam** [comment]
Hmm. Pretending I typed that is a little mean, but I guess we have to accept it unless we store the original markdown somewhere.

**Comment by t3chguy** [comment]
@andybalaam that's https://github.com/vector-im/element-meta/issues/1493
