### ISSUE TITLE
Forgot password asks for the new password before validation via email, not after

### ISSUE THREAD

**Issue by novocaine** [vector-im/element-meta#359]
### Steps to reproduce

The forgot password screen, reached from the login screen

<img width="708" alt="Screenshot 2021-08-25 at 14 39 40" src="https://user-images.githubusercontent.com/57377/130801947-a1f6d4b3-4428-4c69-a487-337560b44cb2.png">

### What happened?

It is unconventional to ask for he new password before validation via email.

### What did you expect?

To prompt for the new password after I've clicked on the email validation link.

### Operating system

OS X

### Browser information

Chrome

### URL for webapp

app.element.io

### Have you submitted a rageshake?

No

**Comment by HarHarLinks** [comment]
Just to state it explicitly: this is not just unconventional and _feels_ unexpected, but there is a **need** to reorder steps in this flow so 1. you don't enter a pw in vain when you thereafter fail to validate via email, and especially 2. password gets validated against requirements before taking another step which currently leads to problem 1.

**Comment by daniellekirkwood** [comment]
This was resolved as part of the Mobile FTUE work and the remaining Web piece is being tracked here: https://github.com/vector-im/element-web/issues/23131

**Comment by HarHarLinks** [comment]
Is this done now?

**Comment by daniellekirkwood** [comment]
Yes, the web work has been completed.
