### ISSUE TITLE
Where, when, and how do we ask for PostHog info: Mobile

### ISSUE THREAD

**Issue by daniellekirkwood** [vector-im/element-meta#41]
We need to discuss and decide how and when to display and ask users for their permission to track on PostHog

- [x] Basic ask: We need a fast solution for this question to get it into product with the PostHog launch
- [x] Further ask: This should be added into the FTUE prototype after some thought and discovery on the best placement and content

**Comment by daniellekirkwood** [comment]
> 1. Something to display to new users - this could just be an update to the existing prompt for now seeing as it'll all change with FTUE.
> 2. Something to display to existing users - this probably should be a screen as it'll show up for anyone who has previously accepted the old prompt.
> 
> Just a "pretty" screen with a 👍 or 👎 button and a nice explainer would be enough.

Conversation on Element

**Comment by daniellekirkwood** [comment]
The Web implementation is here: https://www.figma.com/file/nt8rhrQ9arytjKUl5omfYj/%23157-Analytics-prompt?node-id=50%3A12568

**Comment by daniellekirkwood** [comment]
Notes: https://docs.google.com/document/d/1OGJX54wrsMZ4GB_-LT7bdpmwaDpIqxJI1aAzE3NJJc4/edit?usp=sharing

**Comment by amshakal** [comment]
^ I have added mobile designs to the same figma document

**Comment by daniellekirkwood** [comment]
The PostHog designs on Mobile has been merged and the longer term planned looped into FTU
