### ISSUE TITLE
Upgrading room with Scalar RSS bot did not transfer the bot

### ISSUE THREAD

**Issue by jaywink** [vector-im/element-meta#438]
This is more of a Scalar issue than room upgrade or Riot, but logging here since people will likely come here to look, due to the fact that Scalar RSS bot has been available built in to Riot for so long.

Upgraded a public v1 room to v5. The Scalar RSS bot did not join the new room. Had to manually add it from the IM UI and copy paste over all the feeds.

ping @turt2live

**Comment by turt2live** [comment]
This should be re-opened against go-neb.

**Comment by Mikaela** [comment]
FWIW https://github.com/matrix-org/go-neb/issues/319
