### ISSUE TITLE
Bridges and Bots should be configurable by admins and mods only

### ISSUE THREAD

**Issue by rootkea** [vector-im/element-meta#442]
Hello!

Like widgets, bridges and bots should be configurable by admins and mods only.

As a normal user (power 0) I could add giphy bot, wikipedia bot, rss bot, github bot successfully. Also could bridge matrix to slack room of my choice (something went wrong with the integration as I didn't have much time to probe further but I made slack integration bot to join matrix room)

A normal user besides admin and mod should not be able to configure/add/delete bridges and bots like widgets.

#### Version information

- **Platform**: web (in-browser)

For the web app:

- **Browser**: Firefox 90.0 (64-bit)
- **OS**: Ubuntu 20.04.2 LTS
- **URL**: app.element.io

**Comment by Half-Shot** [comment]
This is no longer the case.
