### ISSUE TITLE
Implement message bubbles for iOS and Android

### ISSUE THREAD

**Issue by nadonomy** [vector-im/element-meta#46]

**Comment by daniellekirkwood** [comment]
@nadonomy I think we can close this issue as Bubbles is now [tracked elsewhere](https://github.com/vector-im/element-meta/issues/72) and available on iOS and Android

**Comment by daniellekirkwood** [comment]
Closing this issue as Android is delivered to prod and iOS is in labs with further issues elsewhere tracking it's delivery to users.
