### ISSUE TITLE
Make the shields the same in Element Web and Element Android

### ISSUE THREAD

**Issue by Linerly** [vector-im/element-meta#52]
> Is your other session showing the same shield?

The first time I verify a login against another session was confusing: Element Web and Element Android have a different shield with the checkmark (in other means, I took it literally), but I knew it has the checkmark in both Element Web and Element Android, so I click "Yes"

**Comment by aaronraimist** [comment]
The web issue for this is https://github.com/vector-im/element-meta/issues/1887 and the suggestion from M was to change the copy (in addition to just changing the icon)

> We should probably change the prompt to be "Is the other user showing a tick?" in order to be more cross-client compatible, or something rather than "the same shield".
