### ISSUE TITLE
Update the captcha screen during create account flow 

### ISSUE THREAD

**Issue by daniellekirkwood** [vector-im/element-meta#524]
The captcha screen needs 2 updates following the release of the MVP auth flow:

- [ ] Update the icon
- [ ] Update captcha as per design suggestions to make it clear that it's an iframe (to avoid https://github.com/vector-im/element-android/issues/6638)

**Comment by daniellekirkwood** [comment]
fyi @ouchadam @pixlwave @amshakal

**Comment by karlabbott** [comment]
Marked as occasional as this should only be seen during the new user registration/auth flow.

**Comment by karlabbott** [comment]
@daniellekirkwood Does the lack of these updates prevent this functionality from working? Or does the lack of these updates just make the experience annoying?

**Comment by daniellekirkwood** [comment]
@karlabbott I think it's a design defect, not a technical one. Will update labels. Thanks!

**Comment by daniellekirkwood** [comment]
this was completed, closing
