### ISSUE TITLE
App Layout: Invites

### ISSUE THREAD

**Issue by daniellekirkwood** [vector-im/element-meta#538]
As part of the app layout work we need to make an improvement to invites.

Requirements:
- Ensure that new invites are not missed
- Improve today's experience
- Ensure that pending invites do not 'get in the way'
- We should be able to revert quickly to the current invites implementation
- Have new invites on a seperate page \(T&S requirement\)

Use cases:
- When a user has an invite, they should know right away, regardless of whether they want to take action or not
- If users want to ignore it, it should not keep floating in front of your face
- If a new invite comes after you have some pending ones, you should be able to identify that right away \(this is the Ghosting use case and it's nice to have for the MVP of App Layout\)

## MVP deliverable

* Add a text label in product at the top of the home page, this opens a new page that lists invites

<img width="739" alt="invites" src="https://user-images.githubusercontent.com/89144281/183649599-5ddea3da-49bd-4524-b0cb-1211b06f6c42.png">

<hr />

## V2

* Have "Seen" and "Unseen" functionality that allows users to know when they're missing a new invite. \(This covers the Ghosting edge case

**Comment by daniellekirkwood** [comment]
Needs a feature flag for itself so that it's independant from the other app layout changes and can be reverted quickly if needed

**Comment by amshakal** [comment]
Updated designs based on all the feedback: 
[iOS Link](https://www.figma.com/file/Hw4gjP3pknMZUir8jQqmWH/%5BMobile%5D-IA-early-proposals?node-id=3223%3A152615)
[Android Link](https://www.figma.com/file/Hw4gjP3pknMZUir8jQqmWH/%5BMobile%5D-IA-early-proposals?node-id=3272%3A162876)
