### ISSUE TITLE
App Layout: Usage Measures

### ISSUE THREAD

**Issue by daniellekirkwood** [vector-im/element-meta#547]
As part of the https://github.com/vector-im/element-meta/issues/544 we may wan to add some tracking to the app layout changes so that we can identify the most used parts of the new flow. 

We will need to add something related to Space Switching modal (similar to the experiment tracking) 
Then, let's add an "on/off" event to the Recents and Filters in Edit Layout.

PostHog Dashboard: https://posthog.hss.element.io/dashboard/710

**Comment by germain-gg** [comment]
@daniellekirkwood could we work on refining this a bit more? I'm not sure the description is enough to implement this ticket, I'm slightly unsure about what needs to be tracked and in what form?

**Comment by daniellekirkwood** [comment]
@gsouquet Yes!

Analytics should be driven by Engineering (y'all know best) but here's my 2 cents... 

- Space switching icon/fab clicked
- Space switched (already exists? Could be ViewRoom where room = Space or subspace -- we had this discussion for the app study and whatever we did was great.)
  - Is it a space or a subspace?
- Space created via bottom sheet
- Recents toggled on
- Recents toggled off
- Favourites toggled on
- Favourites toggled off

Nice-to-have: 
- Filter taps... All selected, Favourites selected, Unreads selected, People selected.

**Comment by daniellekirkwood** [comment]
@gileluard 
We would like to know: 
* How often users turn on and off Filters or Recents from Home
* How often users switch space using the icon and if that space is a space or a subspace

It would be interesting to know (but is not a blocker)...
* If Filters are on, which ones are being used

Does this help?

**Comment by fedrunov** [comment]
We have:

Space switching:

- Interaction.SpacePanelSelectedSpace (User tapped the already selected space from the space list.)
- Interaction.SpacePanelSwitchSpace (SpacePanelSelectedSpace)
- ViewRoom (isSpace = true) (but I can't see it being used on Android) 

Invites:

- No event for Invites screen

AppLayout settings:

- No event for settings dialog

AppBar:

- No event for new avatar icon click (we might be interested if users need it)

Others:
- ViewRoom.RoomList trigger is currently used for any case room is accessed from list of group rooms, dms or unreads (Android). We might what to split it to `all`, `unreads`, `favourites` and `dms` to analyse how users use filters (which they user more often, which less)

- JoinedRoom.Invite -> needs to be tested, if works properly after changes

**Comment by daniellekirkwood** [comment]
Ok, if I'm reading it correctly that looks like what we need for space switching? 
Invites and app bar would be interesting but not necessary, same for access to the app settings dialog. 

Can we implement tracking on the recents and filters toggles?

**Comment by fedrunov** [comment]
Yes, and changing filters also. It's easy to track screen enter and button click, so no problem to do so if you are intersted, my main concern here is how many events our PostHog is able to proceed

**Comment by gileluard** [comment]
On iOS ViewRoom (isSpace = true) is used for space explore rooms already

AllChats screen is tracked as `home` as of now.

Space switching already implemented:

- Interaction.SpacePanelSelectedSpace (User tapped the already selected space from the space list.)
- Interaction.SpacePanelSwitchSpace (SpacePanelSelectedSpace)

**Comment by gileluard** [comment]
Here is what I managed to do for the time being:

### Space switching icon/fab clicked ###
Screen `SpaceBottomSheet` + `ViewRoom(isSpace = true, trigger = RoomList)`
### User navigate inside the space bottom sheet ###
`ViewRoom(isSpace = true, trigger = MobileSpaceBottomSheet)`
### Space switched ###
Interaction `SpacePanelSwitchSpace` or `SpacePanelSwitchSubSpace` in case of a sub space
### Is it a space or a subspace? ###
Interaction `SpacePanelSwitchSubSpace`
### Space created via bottom sheet ###
Screen `SpaceBottomSheet` -> Screen `
### All Chats filter tapped ###
Possible interactions: `MobileAllChatsFilterAll`, `MobileAllChatsFilterFavourites`, `MobileAllChatsFilterUnreads`, `MobileAllChatsFilterPeople`
### All Chats layout settings interactions ###
`MobileAllChatsRecentsEnabled`, `MobileAllChatsRecentsDisabled`, `MobileAllChatsFiltersEnabled`, `MobileAllChatsFiltersDisabled`
### Space created via bottom sheet ###
Screen `SpaceBottomSheet` -> Screen `CreateSpace` -> Interaction `MobileSpaceCreationValidated`
### Space created via All Chats context menu ###
Screen `Home` -> Screen `CreateSpace` -> Interaction `MobileSpaceCreationValidated`
### Space creation aborted ###
Screen `CreateSpace` -> Screen `Home`
### User opens invite screen ###
screen `Invites`
### New user property `allChatsActiveFilter` that represents the active filter in the All Chats screen ###
possible values `none`, `All`, `Unreads`, `Favourites`, `People`

**Comment by germain-gg** [comment]
@gileluard @fedrunov Have we completed this on both platforms?
Trying to figure out whether this is stale and need to be closed or whether we need to schedule some time to look into it

**Comment by gileluard** [comment]
@gsouquet All metrics described [here](https://github.com/vector-im/element-meta/issues/547#issuecomment-1225318915) are implemented on iOS. If it's enough, you can consider it as done.

**Comment by daniellekirkwood** [comment]
@gileluard I'll assign it to myself and link the posthog dashboard and then close this out :)

**Comment by fedrunov** [comment]
For Android it's also done - https://github.com/vector-im/element-android/issues/6508
