### ISSUE TITLE
Info architecture

### ISSUE THREAD

**Issue by nadonomy** [vector-im/element-meta#56]
### Quick links

* [Figma](https://www.figma.com/file/u6xYQamXT4BqUJ5cKnkbWr/iA-Prop?node-id=587%3A106765)
* [Project board](https://github.com/orgs/vector-im/projects/20/)
* [Web issues](https://github.com/vector-im/element-web/issues?q=is%3Aissue+is%3Aopen+label%3Az-ia+label%3Az-delight)
* [iOS issues](https://github.com/vector-im/element-ios/labels/Z-IA)
* [Android issues](https://github.com/vector-im/element-android/labels/Z-IA)

---

### Overview

Through continued development, testing, and research we've encountered usability snags we've been unable to improve within the scope of past projects. To solve these issues, we need to make broader, holistic changes to our *information architecture* \(or, in laypersons terms: app layouts\).

<details>

<summary> Problems we're solving </summary>

### Problem

1. **Navigating the app isn't intuitive** as we've built debt over time, with feature development generally empathizing with complex use cases at the expense of simpler ones.
2. **Cross-platform implementations vary** muddying any mental models or muscle memory for users.
3. **Our app layouts don't scale** with our future needs.

</details>

<details>

<summary> Goals of the project </summary>

### Goals

1. **Learn for the future** by building a clearer understanding of our varied userbase, and workflows.
2. **Increase ease of use and usability** ensuring content is easy to first discover continually re-discover.
3. **Meet simple user needs and expectations out of the box** letting users grow into committed actions over time.

</details>

<details>

<summary> Out of scope </summary>

### Out of Scope

1. **Lengthy 'blue sky' reimagining.** We're biasing for action, learning from small changes and experiments. We'd like our highest-impact changes to confidently live on production before year-end.
2. **Shocking users with large change.** Surprises are fun, but we think we risk eroding trust if we change too much too suddenly or often.
3. **Designing from the gut, or for the loudest voices.** We know our userbase is complex, so we need to listen to a wide range of feedback and validate our findings with testing and research.

</details>

<details>

<summary> People and roles involved </summary>

### People and roles

* **Kat \(Product\):** Driving the project & product thinking.
* **Nique \(Design\):** Advocating for & responsible for all things design. Producing design assets, pairing closely with eng. User research & testing.
* **James \(Eng Manager\):** Ensuring delivery is feasible, and efficient. Having opinions.
* **Michael \(Web\):** Pairing on discovery for Web, and implementing changes.

Once we've progressed through Phase I on web \(timelines below\) we'll also closer loop in Danielle \(who spiked the initial [IA brief](https://docs.google.com/spreadsheets/d/18qa5yzNQVYRr_Zyt3FdZ7rOXO6vwJ82tbvtQmurYfhY/edit#gid=1794807528) too!\) and the mobile app teams, as they may have bandwidth to action high impact changes too.

</details>

---

### Feature lifecycle

To optimise for the velocity of learning, we'll consider the following feature lifecycles for this project: Concept, discovery, and build.

<details>

<summary>More details</summary>

### Concept

- Initial concepts from product & design to spike discussion with engineering
- Issues, napkins, low fidelity comps

### Discovery

- Fleshing out concepts with engineering
- Issues, mid-fidelity comps
- While in discovery, issues will be:
   - Merged to develop to avoid bitrot
   - Labs flagged
      - Enabled by default for low-risk changes
      - Disabled by default for destructive or high-risk changes
- Rapidly user-tested & iterated on

### Build

- Once we have high confidence in issues in discovery, we'll then build the findings for production
- Issues capturing conclusions from testing & iteration
- Hi-fidelity comps in Figma, mature enough to use as acceptance criteria

</details>

---

### Tasks & timeline

<details>

<summary> Timeline 2021-2022 </summary>

* October 2021
* Kicked off discovery & development on Web.
* November:
* Web: Testing & iterating on Phase I. Shipping findings from Phase I to production. Discovery for Phase II & III.
* Mobile: Kicking off designs. Validating with dev if resources available.
* December
* Web: Shipping highest impact changes to production from all learnings.
* Mobile: TBD, pending resources.
* January 2022
* Web: iterate on IA1, kick off IA2 design and development
* iOS: Kicking off designs and metrics instrumentation. Validating with dev if resources available
* Android: Kick off metrics instrumentation, learn from iOS progress

We'll use bullets in this section below as placeholders of intent, maturing into issues when we commit to doing a piece of work. When wrapping this project, we should comb through notes in this epic to break out any useful notes or thinking into issues in our tracker.

</details>

- \[x\] [Metrics](https://github.com/vector-im/element-meta/issues/159)

## Web

Phases I, II, III & IV.

- \[x\] [Phase I: Foundations: Highest impact changes, solving fundamentals for everyone](https://github.com/vector-im/element-meta/issues/153)
- \[ \] [Phase II: Secondary: Lower impact changes, for more committed actions](https://github.com/vector-im/element-meta/issues/154)
- \[ \] [Phase III: Value adds: Stretch goals for deferred value adds and new opportunities from the project](https://github.com/vector-im/element-meta/issues/155)
- \[ \] [Phase IV: Future](https://github.com/vector-im/element-meta/issues/158)

## iOS

- \[x\] [Phase I: Foundations & quick fixes](https://github.com/vector-im/element-meta/issues/156)

## Android

- \[x\] [Phase I: Foundations & quick fixes](https://github.com/vector-im/element-meta/issues/157)

## Mobile holistically

- \[x\] https://github.com/vector-im/element-meta/issues/184
- \[x\] https://github.com/vector-im/element-meta/issues/166
- \[ \] https://github.com/vector-im/element-meta/issues/165
- \[x\] https://github.com/vector-im/internal-planning/issues/237

**Comment by nadonomy** [comment]
Quick notes from a sync with @niquewoodhouse & @t3chguy:

- We won't remove the notification bells from the room lists for now, high risk, we can easily action later once we have more confidence
- We need variants of the room context menus for rooms vs DMs
- We should consider Threads & pinned messages

**Comment by adrm** [comment]
Just out of curiosity, could it be possible to see some screenshots of those Figma designs? It seems the link is not public.

**Comment by nadonomy** [comment]
> Just out of curiosity, could it be possible to see some screenshots of those Figma designs? It seems the link is not public.

Would love to open up Figma docs directly, but unfortunately project permissions are too leaky. It's possible to browse unrelated, confidential docs and comments.

[Issues linked to from this epic](https://github.com/vector-im/element-web/issues?q=is%3Aissue+is%3Aopen+label%3Az-IA+IA1) do include screenshots and more in depth descriptions though.

**Comment by HarHarLinks** [comment]
Somewhere between spotlight and the point "Settings" under future, I hope enabling search for all settings can fit in somewhere https://github.com/vector-im/element-web/issues/9592 https://github.com/vector-im/element-web/issues/20625

**Comment by daniellekirkwood** [comment]
@nadonomy  As this is not actively being worked on anymore, do you think we've completed this epic, and we can close it? Or should we move it back to the Product Pipeline Concept column to pick up later?

**Comment by kittykat** [comment]
I'm going to close this issue for now, please re-open if it's still useful :+1:
