### ISSUE TITLE
Threads Beta: Launch plan

### ISSUE THREAD

**Issue by daniellekirkwood** [vector-im/element-meta#566]
**There will be 3 stages to removing the beta label and launching the MVP of Threads:**

1. Continuous deployment and delivery of improvements to product 
2. Evaluation and testing of product when all items in Exit Beta issue have been resolved
3. Go-To-Market: Remove the beta label and launch GTM marketing materials

---

The Threads Exit Beta Epic is here:
* https://github.com/vector-im/element-meta/issues/187

We need to complete the items in that issue in order to consider Threads as "ready". Once Threads is ready, we will remove the Beta label and "launch it". There are steps involved. **This issue is in draft state while we learn and discuss the plan.**

- As Threads is in Beta already, any improvements committed should be rolled out immediately. We do not need to do a "big bang" launch while working on the [Exit Beta issue](https://github.com/vector-im/element-meta/issues/187). This applies to all platforms
- When we're near completion of the [Exit Beta items](https://github.com/vector-im/element-meta/issues/187) we should discuss the GTM plan and the removal of the Beta label. 
   - The removal of the Beta label should be done **on all platforms at the same time**

**Before removing the Beta label**
We should have:
- Internal & Community testing sessions for bug finding and feedback
- All platforms hitting exit beta criteria
- Review with key stakeholders (like Acceptance testing)
- a detailed GTM plan

**The GTM plan**
The Go-To-Market plan in this instance will likely include: 
- A blog post
  - Marketing have said they don't think another blog is necessary. Due to the time of year this would likely be included in a Year End Round Up post. 
- A tweet
  - Danielle working with Caitlyn for this. A GIF may be user also
- An in-app announcement (maybe across platforms, maybe web only, tbd)

**Comment by daniellekirkwood** [comment]
[Germain] When do we switch from stable prefixes to unstable prefixes?

* Synapse might not recognise the new prefixes and fallback to the old (current) problems.

**Comment by clokep** [comment]
> When do we switch from stable prefixes to unstable prefixes?

For API changes like the above, I don't think this necessarily needs to be tied to marketing of the features. It is more dependent on the spec process. (But we also want to be confident that our solution will pass spec before exiting beta).

**Comment by daniellekirkwood** [comment]
#### Release issues

- [ ] [https://github.com/vector-im/element-ios/issues/5799](https://github.com/vector-im/element-ios/issues/5799)
- [ ] [https://github.com/vector-im/element-android/issues/5503](https://github.com/vector-im/element-android/issues/5503)
- [ ] [https://github.com/vector-im/element-web/issues/21910](https://github.com/vector-im/element-web/issues/21910)

**Comment by clokep** [comment]
>> When do we switch from stable prefixes to unstable prefixes?
>
> For API changes like the above, I don't think this necessarily needs to be tied to marketing of the features. It is more dependent on the spec process. (But we also want to be confident that our solution will pass spec before exiting beta).

The spec stabilized most of our needs so we should probably switch to using the stable identifiers before release, see matrix-org/synapse#14104.

**Comment by daniellekirkwood** [comment]
We expect this to be ready early December. We plan on hitting the 20th December release train to ensure plenty of time for testing. 

👀  @amywalkerdev

**Comment by daniellekirkwood** [comment]
The 20 December 'launch' will be moving the Labs flags to "on" but leaving them in the product for at least one cycle.

**Comment by daniellekirkwood** [comment]
Marking as complete as Threads is now available to all users by default.
