### ISSUE TITLE
Ability to disable "black dot" notifications for rooms

### ISSUE THREAD

**Issue by ghost** [vector-im/element-meta#572]
**Is your feature request related to a problem? Please describe.**
When notifications are disabled on Element, and a message is sent in that room, the room name turns bold and a black dot is shown to the right on the room name (At least on web/desktop).
**Describe the solution you'd like**
The ability to disable that notification type.
**Describe alternatives you've considered**

**Additional context**

**Comment by SimonBrandner** [comment]
![2022-08-28_09-30](https://user-images.githubusercontent.com/25768714/187063119-eaecca6f-c642-4ff2-8573-2f4209564707.png)

If you set notifications to `None`, you won't see any black/white dot. Do I understand correctly that you want to keep `Mentions & Keywords` enabled but not see the unread messages dot?

**Comment by ghost** [comment]
@SimonBrandner I meant setting notifications to "None" and disabling the unread dot.

**Comment by SimonBrandner** [comment]
Sorry, I am still somewhat confused... Which one of the notification options do you have selected? Would it work for you to have it set to `None`?

**Comment by ghost** [comment]
@SimonBrandner I have the default notifications set to "None", the unread dot it still show.

I have to acknowledge that this bug is a bit weird, maybe we should just close it.

**Comment by SimonBrandner** [comment]
Is it reliably reproducable?

**Comment by ghost** [comment]
@SimonBrandner This is actually not a bug, just a feature request.

**Comment by SimonBrandner** [comment]
If this is one Element Web/Desktop and you have notifications set to `None`, there should be no dot shown and therefore this would be a bug. If that is the case, please open an issue at https://github.com/vector-im/element-web/

**Comment by ghost** [comment]
@SimonBrandner very well, thanks for the help.
