### ISSUE TITLE
Mark all as Read (including Threads)

### ISSUE THREAD

**Issue by daniellekirkwood** [vector-im/element-meta#577]
While this issue is marked as an enhancement we need to define the behaviour for Threads Exit Beta and then update this WIP issue with the appropriate next steps that are not blocking to the Exit Beta release.

Now that we have Thread Timelines as well as the Main Timeline we do not have the ability to mark a room as read on Web. The Main Timeline button that (without threads) marks a room as read, only applies to the main timeline.

<img width="82" alt="Screen Shot 2022-09-02 at 12 43 45" src="https://user-images.githubusercontent.com/89144281/188173668-8de74db4-bc3e-4d0e-be6f-25183f379659.png">

On Mobile we have a room level control that marks a room as read (including threads?)

**Comment by germain-gg** [comment]
We have a solution to mark the room as read technically, but it won't scale very well. 
Follow the MSC conversation about how to do it in a more performant manner https://github.com/matrix-org/matrix-spec-proposals/pull/3773/files#r961753262

**Comment by daniellekirkwood** [comment]
Related: 
https://github.com/vector-im/element-web/issues/24053

**Comment by clokep** [comment]
I think this work is done -- Element Web and mobile clients can mark an entire room as read including all threads in it.

**Comment by marcusmueller** [comment]
@clokep I'm sorry, I'll have to deny that – element web 1.11.27 doesn't mark threads read:


https://user-images.githubusercontent.com/958972/233776550-5c875082-efc6-4fb0-876d-393b6fbc4924.mp4

**Comment by germain-gg** [comment]
I +1 @clokep . This has been done, and therefore will close this ticket. 

@marcusmueller it sounds like you've faced a bug, and it would be good if you could open an issue and share a rageshake so we can investigate this issue.
