### ISSUE TITLE
Can't dismiss persistent notification (on web and Android)

### ISSUE THREAD

**Issue by kittykat** [vector-im/element-meta#58]
### Steps before triggering:
1. Sent a message in a group chat
2. Someone else reacted to the message and replied to a thread
3. I reacted to the reply in the thread
4. I now have a persistent 1 unread message notification both on Android and web for the room

I've looked at the room both on web and Android and cannot see any new messages

The last action in the room is the react from me

On Android:
![Screenshot_20211102-110316.png](https://user-images.githubusercontent.com/51663/139840097-aca2b411-c4bb-4852-b0ff-0ab01b0dc8e5.png)

**Comment by daniellekirkwood** [comment]
This should now be fixed - @kittykat can you confirm and close ?

**Comment by kittykat** [comment]
I think the fix might have caused vector-im/element-web/issues/20036
