### ISSUE TITLE
What does Thread summary look like when root message is not text? Reactions are before Thread Summary also

### ISSUE THREAD

**Issue by daniellekirkwood** [vector-im/element-meta#60]
When the root message is not text, how does the Thread Summary appear?

- Cross platform
- Room list

Discussed in stand up on November 8,2021

**Comment by daniellekirkwood** [comment]
I think it's been so long we might not need this issue any more. 

@janogarcia please confirm you're happy to close this

**Comment by janogarcia** [comment]
@daniellekirkwood It's being addressed here https://github.com/vector-im/element-meta/issues/121

I'm closing this one, but feel free to reopen if necessary.
