### ISSUE TITLE
Delight: Improve notifications & comms for new users

### ISSUE THREAD

**Issue by daniellekirkwood** [vector-im/element-meta#604]
### Your use case

Related to: https://github.com/vector-im/element-web/issues/11937

Also:
* Auto enable email notifications and send new users an intro/summary email. What do the first few emails look like, could we introduce “product learning emails” that encourage usage?

**Comment by t3chguy** [comment]
Default notifications are set by the server (Synapse)

**Comment by MadLittleMods** [comment]
@daniellekirkwood To continue the better default notifications area this issue originally touched upon, see https://github.com/vector-im/element-meta/issues/256. It has a good small iterative improvement which doesn't require any extra backend work (just needs product decision on whether we like the new default proposed there).

**Comment by daniellekirkwood** [comment]
Closing this as it's replaced by other notificaitons issues
