### ISSUE TITLE
Users expect to be told when they have missed notifications

### ISSUE THREAD

**Issue by daniellekirkwood** [vector-im/element-meta#615]
This is a chronic issue

**Problem:** Users expect to be told when they have missed notifications.
**Defect:** Re-add the badge to the NotifPanel so folks can see when they have notifs(!)
**Suggested Plan:** Add the badge. We had it pre-Element, in https://github.com/matrix-org/matrix-react-sdk/pull/2336

**Comment by ara4n** [comment]
i did it: https://github.com/matrix-org/matrix-react-sdk/pull/9242

**Comment by daniellekirkwood** [comment]
I see this in Element Nightly (which is awesome) but I think the Notif. panel could use some love @amshakal
