### ISSUE TITLE
When accepting an invite, expecting to see the room (meta)

### ISSUE THREAD

**Issue by giomfo** [vector-im/element-meta#62]
On Element-Mobile, when I accept an invitation to a room, after the invite is processed I would expect to see the room. Instead it is hidden somewhere in my room list, forcing me to use search to find it, to find out if there are any messages there for me to react to.
I didn't test on Element-Web

The details of this request (and discussions with the mobile Application team (Android/iOS)) are available in the following issues:
- https://github.com/vector-im/element-android/issues/3771
- https://github.com/vector-im/element-ios/issues/4986

The conclusion was
![image](https://user-images.githubusercontent.com/8969772/141989284-c58ce95d-3c89-4919-a233-23b7d07c7082.png)

The request here is to consider this conclusion with a cross-platform point of view

**Comment by giomfo** [comment]
As part of the UX work on start a DM, the design team confirms that the intended behaviour should be to open the chat timeline as soon as the user presses on “Accept”. This should be effective cross-platform

We will apply the change on Element-Android first, then it will be applied on Element-iOs and Web

**Comment by daniellekirkwood** [comment]
Thanks, @giomfo Can you confirm there's no action needed from us on the app-teams?

**Comment by giomfo** [comment]
> Thanks, @giomfo Can you confirm there's no action needed from us on the app-teams?

@daniellekirkwood : FYI I'm able to take in charge the change on Element-Android and iOS. I may just have difficulties to plan the change on Web at the same time. We may sync together to define the best plan for this platform (web)

**Comment by giomfo** [comment]
@daniellekirkwood FYI the change has been done in Element-Android (see https://github.com/vector-im/element-android/pull/5247). After thinking, no change is expected for Element-Web

We still have to plan the change in Element-iOS by considering https://github.com/vector-im/element-ios/issues/4986
My team was not able to work on it for the moment. I will remove the assignment on this ios issue to let it takeable
