### ISSUE TITLE
Minor spelling, grammar and link issues in the wiki

### ISSUE THREAD

**Issue by stevepdp** [vector-im/element-meta#63]
There are some minor spelling, grammar and link issues in the wiki which I have fixed.

Due to the wiki repo not supporting PRs, please review the attached `git diff` and markdown pages for copy-pasting.

Thanks

- [diff.txt](https://github.com/vector-im/element-meta/files/7566460/diff.txt)
- [git-log.txt](https://github.com/vector-im/element-meta/files/7566481/git-log.txt)
  
- [Community-testing.md](https://github.com/vector-im/element-meta/files/7566456/Community-testing.md)
- [Home.md](https://github.com/vector-im/element-meta/files/7566457/Home.md)
- [Testing-Element-on-Android.md](https://github.com/vector-im/element-meta/files/7566458/Testing-Element-on-Android.md)
- [Testing-Element-on-Web.md](https://github.com/vector-im/element-meta/files/7566459/Testing-Element-on-Web.md)

**Comment by kittykat** [comment]
All changed applied except the absolute links - I'm not sure there's a benefit to changing those (open to reasons for changing).
