### ISSUE TITLE
Destroy all decryption keys from a room, onec all users leave it.

### ISSUE THREAD

**Issue by Atom-Dragon** [vector-im/element-meta#654]
### Your use case

It would be nice if all decryption keys are deleted from a room when all members leave it.

For example say you're homeserver is matrix.org which is using EMS, if all users were to leave the room the contains in that room would still exist but it would be un-joinable. Since all users are unable to join back it would be good from a privacy and security stand point to delete the keys as all the users can't really access that left room anymore.

I was told on EMS homeservers the function "purge room on all members leave" is not enabled by default as it's impossible to do on EMS, hence deleting all the decryption of a forgotten room would be a great feature to have and give users extra protection in case of a future beach.

### Have you considered any alternatives?

An Alternative to this would be to have an automatic garbage collection of empty rooms, as having the empty rooms would take unnecessary space on the homeserver especially if the rooms contains media and files. so once in a while a function is ran to clear out any rooms where there is no users.

**Comment by t3chguy** [comment]
Users can look back at history of rooms they have left, so they'd need to keep keys to decrypt that history
