### ISSUE TITLE
Voice message playback queue should not include own voice message

### ISSUE THREAD

**Issue by grimhilt** [vector-im/element-meta#707]
#### What would you like to do?
When I start a queue of voice message, I would expect it to skip my own voice message and continue with the interlocutors voice messages.

#### Why would you like to do it?
Doing a voice message as listening to it is long and there are frequent use case where my voice message between other voice message I didn't listen to, and I do not need to listen to my own voice message, I just want to listen to the other one.

#### How would you like to achieve it?
Either adding an other settings (as this feature is useful when going through old conversation where listening to our own messages is needed for context).
Or just removing this feature.

**Comment by bwindels** [comment]
Hi, could you elaborate what you mean with `When I start a queue of voice message`. I am not aware of any kind of queue when playing back voice messages.

**Comment by bwindels** [comment]
Ah, I think I know what you mean now, if you play a voice message, it will try to play the next voice message.

**Comment by grimhilt** [comment]
Precisely, let's consider a conversation like this : 
* Voice Message 1 (Not me)
* Voice Message 2 (Not me)
* Voice Message 3 (Me)
* Voice Message 4 (Not me)

Currently, if I play 1, when it will reach the end, 2 will start, followed by 3 and 4.

I would expect my voice message to be ignore, so 1, 2, 4 will be played with the queue.
Or my voice message could have the same behavior of a text message and stop the queue, so when 1 is played, it will trigger 2 and that is it.

**Comment by kittykat** [comment]
Moving to discussions as this is cross-platform :+1:
