### ISSUE TITLE
The way spaces and rooms are organized makes no sense;

### ISSUE THREAD

**Issue by expikr** [vector-im/element-meta#709]
#### What would you like to do?

clicking on a community should automatically list all of the rooms. The "Home" rooms list should simply serve as a shortcut folder for frequently accessed rooms, rather than being a strict container for loose rooms (and joining a space should not force-move the loose rooms to the space)

#### Why would you like to do it?

preserves object permanence

#### How would you like to achieve it?

clicking on a community should automatically list all of the rooms. The "Home" rooms list should simply serve as a shortcut folder for frequently accessed rooms, rather than being a strict container for loose rooms (and joining a space should not force-move the loose rooms to the space)

### Have you considered any alternatives?

Basically Discord, but with an extra "Frequent Channels" button.

![image](https://user-images.githubusercontent.com/77922942/194067009-7a6e01dc-6bf9-4b88-b709-f1cc417a7a77.png)

### Additional context

vector-im/element-web#23425

**Comment by t3chguy** [comment]
> clicking on a community should automatically list all of the rooms.

This is already possible if the Space marks its rooms as `Suggested`

**Comment by expikr** [comment]
> > clicking on a community should automatically list all of the rooms.
> 
> This is already possible if the Space marks its rooms as `Suggested`

Then the pattern should be reversed. Default-show and optional "mark unsuggested". This is a problem with the Matrix protocol itself, then?

**Comment by expikr** [comment]
_Originally posted by @DanMan in https://github.com/vector-im/element-web/issues/15930#issuecomment-863086706_:
> What's the reasoning behind not listing all the rooms inside a Space for everyone in that (private) Space? It seems like even a public room with guest access is not listed for all the Space members. Aren't they supposed to be able to discover all the (public) rooms? What's the point of "suggested" rooms then after all?

seems that it had been mentioned before but completely missed the point, the problem is with the reversed default being terrible UX, not a problem with private/public functionality.

**Comment by t3chguy** [comment]
Moving to meta as this is a cross-platform concern
