### ISSUE TITLE
Improve history UISI Display

### ISSUE THREAD

**Issue by BillCarsonFr** [vector-im/element-meta#74]
## Problem description

Currently if you login a new session, all the history messages retrieved via initial sync will be in Error with \*\*unable to decrypt\*\* errors for all messages in timeline.

If the user did verify his session and have a keybackup, a backup import should be happening in background. But during this process the messages would still be displayed with hugly errors. Even key gossiping with the other session could take time.

Actual rendering:
<img width="450" alt="image" src="https://user-images.githubusercontent.com/9841565/146420621-ef59260e-b882-452a-81f4-72656b9b210e.png">

## Proposal

We should hide undecryptable history if we know that there is no chance for the current device to get the key without a user action \(verify, manual import..\)
We should hide history while a key backup is in progress, and give feedback on the import process
The user should have an option to show history anyway

<img width="903" alt="image" src="https://user-images.githubusercontent.com/9841565/146421047-d9ad7a32-1675-4ef9-b35d-910b4e11cf74.png">

If the session is verified and the user already did a key import, or if he decided to show message anyway, or if this room is setup to [share room key history](https://github.com/matrix-org/matrix-doc/pull/3061), we should then show them, but the error level should lowered and a dismissable banner should be shown with details and CTA

<img width="947" alt="image" src="https://user-images.githubusercontent.com/9841565/146421277-edd0e3c3-b71f-4209-94c8-d0c855d661c2.png">

We should also give feedbacks to the user about the key gossiping process, currently for the user it's like a shot in the dark \(`re-request encryption keys`\)

<img width="589" alt="image" src="https://user-images.githubusercontent.com/9841565/146421465-09d31973-237d-496e-88f7-04b4fd19f46f.png">

## Dev Tasks

- Android https://github.com/vector-im/element-android/issues/4940
- Web https://github.com/vector-im/element-web/issues/20532

**Comment by amshakal** [comment]
Proposed solution for different usecases:
![UISI - User Action Needed](https://user-images.githubusercontent.com/85162587/147820614-4854912b-0b1c-4461-a6e8-5ed9ded7d7b0.png)

![UISI - User Action Needed2](https://user-images.githubusercontent.com/85162587/147820617-c87762bd-cb07-40fd-a527-3396875e41e6.png)

![UISI - User Action Needed3](https://user-images.githubusercontent.com/85162587/147820623-5d5280f0-407a-4e92-a0c5-37bf91368a9a.png)

![Room template (Web)4](https://user-images.githubusercontent.com/85162587/147820629-eec1d4e3-2f21-42de-ac7b-60f37fc5753f.png)

![Room template (Web)5](https://user-images.githubusercontent.com/85162587/147820634-5730e517-d549-4048-8039-7c1ded24e2b7.png)

Link to figma: https://www.figma.com/file/a1NWmg6mOi2VZuSgaJx6nD/Displaying-UISI?node-id=112%3A6692

**Comment by ShadowJonathan** [comment]
> ![](https://user-images.githubusercontent.com/85162587/147820629-eec1d4e3-2f21-42de-ac7b-60f37fc5753f.png)

Some feedback; i personally love this variant the most, as it does not hide *which* messages can be decrypted, which i personally think is a downside of other designs.

**Comment by pmaier1** [comment]
https://github.com/vector-im/element-meta/issues/249#issuecomment-1673338527
