### ISSUE TITLE
Implement MSC3879: Trusted key forwards

### ISSUE THREAD

**Issue by BillCarsonFr** [vector-im/element-meta#756]
MSC: https://github.com/matrix-org/matrix-spec-proposals/pull/3879

- \[ \] Js-sdk
- \[ \] iOS sdk
- \[ \] android sdk
- \[ \] https://github.com/matrix-org/matrix-rust-sdk/issues/1108

**Comment by pmaier1** [comment]
In the future we plan to not rely on key gossiping anymore as the key backup will become more stable and key forwarding creates unnecessary traffic. For that reason no work is planned on this anymore.
