### ISSUE TITLE
Rust crypto SDK parity for integration in element R

### ISSUE THREAD

**Issue by BillCarsonFr** [vector-im/element-meta#759]
https://github.com/matrix-org/matrix-rust-sdk/issues?q=is%3Aopen+is%3Aissue+milestone%3A%22Stabilize+the+crypto+crate%22

Notable points:

- https://github.com/matrix-org/matrix-rust-sdk/issues/580
- https://github.com/matrix-org/matrix-rust-sdk/issues/401
- https://github.com/matrix-org/matrix-rust-sdk/issues/40
- https://github.com/matrix-org/matrix-rust-sdk/issues/281

**Comment by almereyda** [comment]
- https://github.com/matrix-org/matrix-rust-sdk/issues/1016#issue-1365783675

mentions

- key backup & cross-signing (and/or SSSS) 
- Custom to-device message bindings (for MSC3401 VoIP)

for this, too.

https://github.com/vector-im/element-web/issues/21972#issuecomment-1141345625 also mirrors the cross-signing/SSSS and backup requirement.

**Comment by richvdh** [comment]
Looks like this issue has served its purpose.
