### ISSUE TITLE
[UISI] Allow users to view e2e information regarding a message, and option to review incoming key requests

### ISSUE THREAD

**Issue by BillCarsonFr** [vector-im/element-meta#76]
## Problem

Currently when a recipient could not decrypt a message sent by a user, the sender is left clueless on what happened / what to do.
The idea would be to offer some troubleshoot options to the sender.
This should not be detrimental to the generic UX, not too prominent in the UI. Because it might be due to a bug and we want to fix the root cause ultimatly. Yet having option to troubleshot in UI will greatly help reporting issue as well as allow user to self troubleshot.

## Proposal

We might add a new option on e2e message menu that would display a modal with some e2e details.
<img width="379" alt="image" src="https://user-images.githubusercontent.com/9841565/146563609-678c6357-c853-4efc-b6ad-ac356635fb9b.png">

The \(i\) Cryptography menu item would open a modal showing some generic info \(accessible via the view source\). As well as information regarding the key sharing:
- List of member / devices the key was shared with
- Eventually the list of user|device it failed to deliver to \(no otk/ blocked / ..\)
- And more importantly the list of current pending key request that could be manually handled **check technical feasibility here, might modify SDK to bubble up to app some declined requests**\)

Wireframe
<img width="801" alt="image" src="https://user-images.githubusercontent.com/9841565/146564525-4e12a02f-d057-4434-a091-a5c23d8e3872.png">

The `review request` shoud give the user all needed informations in order to decide to accept or not the incoming \(is this user trusted, as well as the device .. TBD\)

## Potential issues

This is not designed as to be some UX to allow the sharing of key history. \(though could it? it's technically possible today to manually export keys and send them\)

### DEV tasks

- EA https://github.com/vector-im/element-android/issues/4891
- EW https://github.com/vector-im/element-web/issues/20454

**Comment by amshakal** [comment]
Proposed designs: A new icon for cryptography has been introduced
![Frame 3830](https://user-images.githubusercontent.com/85162587/147820293-ff7d211c-839a-43a0-9e82-715e7066c350.png)

A new icon for user + device/session has been introduced
![Room template (Web)](https://user-images.githubusercontent.com/85162587/147820315-82cc8c4d-adea-45e5-b0d6-4282a0f50a74.png)

Link to Figma:
https://www.figma.com/file/a1NWmg6mOi2VZuSgaJx6nD/Displaying-UISI?node-id=141%3A11503

**Comment by BillCarsonFr** [comment]
Would be nice to have the origin of the key. Was it via m.room_key or forwarded or via backup

**Comment by pmaier1** [comment]
https://github.com/vector-im/element-meta/issues/249#issuecomment-1673338527
