### ISSUE TITLE
incoming encrypted to-device messages can be lost when the application is restarted

### ISSUE THREAD

**Issue by BillCarsonFr** [vector-im/element-meta#762]
If you restart /upgrade (web) or the app is killed in background while processing to_devices coming down the sync, the non decrypted to_devices will be dropped and lost producing UISIs.

This is problem with atomicity of `/sync`. The sync token is persisted before all `to_device`s have been processed, so the next time the app launches it will use the saved token, thus ack'ing the previous `to_device` chunk that was received. In such case the app should start syncing with the previous token to force a redelivery of the initial `to_device` chunk (or make sure that it permanently persists the to-device messages before storing the `/sync` token). Olm session internal state should also be reverted if the sync does not complete.

- https://github.com/vector-im/element-web/issues/23113
- Similar issue on android
- Similar on iOS?

**Comment by richvdh** [comment]
@BillCarsonFr:

> Olm session internal state should also be reverted if the sync does not complete.

Why is this required?

**Comment by pmaier1** [comment]
Will be fixed with the introduction of ER.

**Comment by BillCarsonFr** [comment]
> Will be fixed with the introduction of ER.

Looks like not. The sync token is save way to early (on purpose?), before the to_devices have been processed by the rust sdk.
So in case of restart, the next token will be used and thus the to_devices not processed are lost.

https://github.com/matrix-org/matrix-js-sdk/blob/748d03ba1129dd0ab6ce6e44f6202b81e604a4b3/src/sync.ts#L895
```
            // set the sync token NOW *before* processing the events. We do this so
            // if something barfs on an event we can skip it rather than constantly
            // polling with the same token.
            this.client.store.setSyncToken(data.next_batch);
```

**Comment by richvdh** [comment]
> Similar issue on android
> Similar on iOS?

Do we actually have any evidence that EAR and EIR are similarly affected? The Rust SDK makes this much harder to mess up than before, so I don't see it as a given that the other platforms have the same problem

**Comment by richvdh** [comment]
Given that https://github.com/element-hq/element-web/issues/23113 is now closed, and we have no reports of it happening on EAR and EIR, can we close this?

**Comment by BillCarsonFr** [comment]
> Given that [element-hq/element-web#23113](https://github.com/element-hq/element-web/issues/23113) is now closed, and we have no reports of it happening on EAR and EIR, can we close this?

Confirm that android only [saves the token after](https://github.com/element-hq/element-android/blob/b4b11a5767ab6f6b3c62beb7f4bb217e3124266b/matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/sync/SyncResponseHandler.kt#L126C13-L126C37) all the to_devices have been [processed](https://github.com/element-hq/element-android/blob/b4b11a5767ab6f6b3c62beb7f4bb217e3124266b/matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/sync/SyncResponseHandler.kt#L86).

For iOS I am not sure for the background sync (NSE). Looks like the [crypto sync is handled after ](https://github.com/matrix-org/matrix-ios-sdk/blob/8639971d9fdd80884c219fe5916112f2b7439e45/MatrixSDK/Background/MXBackgroundSyncService.swift#L435)the call to `syncResponseStoreManager.updateStore` 

So possible that the background sync of IOS is affected?

**Comment by BillCarsonFr** [comment]
Ok so it's also fine for IOS. 
The NSE background sync will save the sync response anyhow, and the next time the app starts it will then start from the token persisted by the app side, and will process the cached syncs (to avoid another server call). So IOS is actually in some condition replaying the to_device (can be seen in various RS ` An Olm message got replayed`) and not dropping them.

So closing.
