### ISSUE TITLE
Hide Ignored users on right side of pane

### ISSUE THREAD

**Issue by autoteelar** [vector-im/element-meta#796]
#### What would you like to do?
when you ignore a user, it hides all their messages and stuff, but you can still see their name on the side, some users may want this or be ok with it, some might not, personally i would have specific use cases

#### Why would you like to do it?
for example if someone has an inappropriate name in a chat and you dont want to look at it on the right side panel, you could hide them from showing up on the users list
#### How would you like to achieve it?
when you press ignore, also hide them from the list, or if that may inconvenience some users, maybe make it a toggle in the settings to also hide ignored users on the side

### Have you considered any alternatives?

i tried using inspect element and other addons, but they dont work that well and you cant really in the desktop client

### Additional context

i just think that when someone ignores/blocks/whichever term you want to call it, most people would probably prefer not to see anything about them at all, or even be able to know they exist at all while they are ignored.

**Comment by t3chguy** [comment]
Ignore is actually implemented by the server
