### ISSUE TITLE
New Direct Messages screen is inconsistent between the different platforms

### ISSUE THREAD

**Issue by jakewb-b** [vector-im/element-meta#83]
My request concerns the screen opened when the user wants to create a new DM from the different Element application (Web/Android and iOS)

Here is a screenshot with the current implementation:

![f142c856-4e29-4999-a0fa-8f45c4b8c04f](https://user-images.githubusercontent.com/87766619/148039591-f676361a-c99f-42db-9a6f-686822a2644c.png)

Element-web has a "Recent Conversations" section which doesn't exist on the other apps (I don't know if this is really useful)

I consider "Suggestions" and "Known Users" are the same, but they don't list the contacts in the same order (for the same connected account). FYI: known users are people with who the end user shares at least one room

Element-iOS don't have any suggestions, this is a pity...

The contact book access on mobile is handled totally differently on Android and iOS...

These inconsistencies may disturb the end users.They disturb our work at PS level to promote the use of the Element design for this screen. For example, I'm supposed to replace the existing Tchap (DINUM) contacts picker with the Element one. We did for Tchap-Android, but I don't want to do the same on iOS until Element-iOS has a suggestions/known users list. It will be a regression for Tchap end users.

Last remark, I consider this improvement about the contacts picker for the DM creation screen should be taken into account by the Application team (or a Feature team). I don't think we should ask sponsoring for that

(see https://element-io.atlassian.net/browse/PROD-48)

**Comment by daniellekirkwood** [comment]
Thanks for raising - all great points and we hope to address this in Q1 :)

**Comment by gaelledel** [comment]
@daniellekirkwood @giomfo 
I am integrated this issue as part of the start DM UX rework https://element-io.atlassian.net/browse/PROD-1?atlOrigin=eyJpIjoiNDk3YjMxOWYwNzlkNGNhMDhhYzc2ODQ1M2ZjMzY0ZDAiLCJwIjoiaiJ9

Danielle, please feel free to get in touch for more info. We'll need to touch base on this at some point.

**Comment by daniellekirkwood** [comment]
Discussion of requirements: 
- [ ] We need to decide how the user adds their contact book
- [ ] We need to make this screen consistent across platforms
- [ ] We need to ensure the iOS designs scale to include the QR code one day
- [ ] We need to keep the ability to invite friends
- [ ] On Mobile we do not need to keep known users

This screen will change dependant on the life stage of the user; 
- FTUE for new users and 
- Ongoing where there have been interactions with others already.

**Comment by giomfo** [comment]
In case of search the result is inconsistent on the different platforms (Web/iOS/Android):
![image](https://user-images.githubusercontent.com/8969772/150846367-a41f76b0-d046-492c-8d37-48cee8c9a294.png)

- The list displayed on the web client is totally different than the one displayed on mobile. (Note : the 2 first suggested contacts displayed on android are displayed at the end on ios. The other contacts are listed in the same order)
- a know contact named Christy is displayed at the first position on web and android (👍 ), this contact is totally missing on iOS 👎
