### ISSUE TITLE
Automatic rainbow writing

### ISSUE THREAD

**Issue by trixint** [vector-im/element-meta#859]
#### What would you like to do?
I want to write with /rainbow in every message without having to remember typing the command every time.

#### Why would you like to do it?
I love rainbows. (I automated pacman on Linux to pipe through lolcat every single time for more rainbow on my screen, too.)

#### How would you like to achieve it?
I would love to have the possibility to set permanent message commands. have a new sub-setting in Preferences to add /rainbow before every message. (except: writing own commands, message already starts with '/')

### Have you considered any alternatives?

an alternative would be to set a shortcut on my keyboard to only paste '/rainbow' to get it down faster, this still wouldn't make me remember it always, but probably more often.

### Are you willing to provide a PR?

No

**Comment by daniellekirkwood** [comment]
Hey @trixint 

We love that you love rainbows! (So do we). Unfortunately at this time we're not looking to add anything else to Settings so I'm going to close out your request. Our settings pages are pretty cumbersome and full - we need to take a step back and simplify choices for our users. 

While rainbows are enjoyable and likely to bring joy to lots of people, it's already a command we have at the point of writing a message and therefore will not be adding it to settings in the foreseeable future.

Thanks so much for your feedback and suggestion. Please keep raising new ones with us!
