### ISSUE TITLE
Update the default notifications settings for new users and add new options to reset and clear notifs.

### ISSUE THREAD

**Issue by daniellekirkwood** [vector-im/element-meta#887]
### Your use case

This is the meta issue discussing the work needed to complete the outcome desired.

We want to: 
* Update the default settings for new users so that notifications make more sense and are comparable to other messaging apps so that mental models are preserved
  * Ideally we'd draw this out so it can be understood by internal Element employees too
  * We need to understand the current state of all 5 platforms and the desired state so that we can take a decision on what we build now or build in the future

We also should: 
* Create a "reset to default" option for all users 
* Update the behaviour of the "Clear notifications" button in Settings - it should always be visible, it's content should be updated.

**Comment by daniellekirkwood** [comment]
@clokep, @amshakal  assigning to you both as i think we need to confirm the default changes we want to create and then check that this is doable with the current environment (and if there's any spec changes needed).

Also, @amshakal / @gsouquet  should we make the "reset" apply to all platforms?

**Comment by daniellekirkwood** [comment]
Afterwards, I will create the platform specific issues for the work that will need to be done

**Comment by daniellekirkwood** [comment]
Related documentation:
 - https://docs.google.com/document/d/1J6-XyVQsthkylffD20UrCFbWF_g9mao8JS2bhn5z1SU/edit#bookmark=id.ayc00ag4dkdj
 - https://github.com/vector-im/element-meta/blob/develop/docs/notifications_defaultsettings.md
 - https://docs.google.com/document/d/1ryZjVuYBSfsu4e6fqYHIC9hJhY-aEWukcWMig1ewRA4/edit#

**Comment by daniellekirkwood** [comment]
The items from the body are being handled by other GH issues in the Web space under the Get Your Updates cycle epic: https://github.com/vector-im/element-web/issues/24291

Defaults for new users have been decided and documented (linked above).

Closing this issue

**Comment by t3chguy** [comment]
@daniellekirkwood the default push rules are set out in the spec so unless we want all new users to land in "Custom" too we'd need an MSC and server updates - the client can't really be relied upon to override defaults as during SSO auth it has no way of knowing whether the user is new or not, it all looks like logins

**Comment by daniellekirkwood** [comment]
@t3chguy  ok, i will reopen this issue. 

We should probably discuss your comment in much more detail as it's new. 

Moving to internal room: https://matrix.to/#/!aREzkHGCDRZFBtnnxx:one.ems.host?via=matrix.org&via=element.io&via=one.ems.host

**Comment by clokep** [comment]
I'm still pretty certain there's *no* proposed changes here, which means this can be closed. As @t3chguy says, if we want to make changes we'll need to write an MSC and go through that process.

**Comment by daniellekirkwood** [comment]
Yep - the other parts of this issue are handled elsewhere.

Thanks
