### ISSUE TITLE
Consider adding support for "whispering" in group rooms

### ISSUE THREAD

**Issue by richvdh** [vector-im/element-meta#941]
Apparently XMPP has the ability to send messages to a specific subset of users in a larger room; we may wish to consider supporting this too.

Advantages of the feature are that it can be useful to send a quick/offtopic message to a subset of users in a channel about something small or only affecting them, especially in high-traffic rooms, without necessarily starting a new discussion.

Concerns about such a feature are that it would provide a ready spam/harassment vector: people in large rooms may use it to send inappropriate messages out-of-sight of moderators. We would need to make sure that such a feature came alongside tools for managing such misuse (eg blocking, reporting).

**Comment by vertigo220** [comment]
In addition to examples already given, I can think of at least several more where whispering would be useful, to allow some individuals in a room with many people to quickly say something between them where either it would just add unnecessary clutter to the room conversation or they may simply not want it to be in the public conversation, but easier than having to create a separate room or DM. And there's no need to make them non-private, and they can and probably should be encrypted if possible, even if the room isn't (though this should probably be a setting). If there's abuse/harassment, all it would take is a copy/paste or screenshot shown to an admin to make it known so it can be dealt with.
