### ISSUE TITLE
[Story] Create a new 1:1 chat

### ISSUE THREAD

**Issue by kittykat** [vector-im/element-meta#989]
As a user I want to have a 1:1 chat with an other user.
- That chat is either already existing or I want to create a new chat.
- That chat should be our "personal room"  - so no other user should be allowed to join.

I want start my user journey at the home screen.
- From there I want an easy access to users that are relevant to me: For example users I have recently chatted with or that are from my organisation.
- If I do not know the matrix-id of the user I want to write a message to I want to be able to search for that user.

Once I found the user I'll end up in a room.
- If me and the user already have a 1:1 chat room I'll end up in this room and see the history

If a room does not yet exist I end up in an empty room.
- I can write a first message to that user right away.
- When I send that message the room gets created and the other user is invited to that room.

## Scope

```[tasklist]
### Engineering
- [ ] https://github.com/vector-im/element-meta/issues/1012
- [ ] https://github.com/vector-im/element-meta/issues/1014
```

## Out of scope

- Persisting the room when writing a draft message

## Sign-off

```[tasklist]
### Android
- [x] Design sign-off on completion
- [x] QA sign-off on completion
- [x] Product sign-off on completion
```

```[tasklist]
### iOS
- [x] Design sign-off on completion
- [x] QA sign-off on completion
- [x] Product sign-off on completion
```

**Comment by Johennes** [comment]
@kittykat the iOS side of this story is ready for testing.

**Comment by kittykat** [comment]
Must be tested with test accounts for now

**Comment by Johennes** [comment]
Closing this since we've reviewed it in the weekly on Tuesday and shipped it in the iOS TestFlight today. Any further issues can be tracked under the epic which I'm keeping open until QA has processed the whole scope.

**Comment by ghost** [comment]
Retested this on Element X iOS 1.1.8 (270) and Element X Android 0.1.0-nightly (July 1, 2023). It seems to be working in line with the acceptance criteria. Removing this from my backlog, but please tag me if you need something tested.
