### ISSUE TITLE
[Story] Join a room following an invitation

### ISSUE THREAD

**Issue by kittykat** [vector-im/element-meta#991]
As a user that has been invited to a new conversation I want to join a room to read messages & chat w. other users.
- The new room with the invitation is on top of the room list.
- The name and avatar is displayed
- Show a text "[user-name] invited you"

Taping on that room opens the room and the user is joining the room.

## Scope

```[tasklist]
### Engineering
- [ ] https://github.com/vector-im/element-meta/issues/1018
- [ ] https://github.com/vector-im/element-meta/issues/1054
- [ ] https://github.com/vector-im/element-meta/issues/1158
```

## Out of scope

- Message preview for DMs
- Bulk process invites (accept and/or reject multiple invites from the view of all invites)
- Block user (when the invite is spam)
- Ignore invite
- Preview public room that you've been invited into
- A tap on the "User invited you" button for a "room invite" opens the inviter's profile

## Sign-off

```[tasklist]
### Android
- [x] Design sign-off on completion
- [x] QA sign-off on completion
- [x] Product sign-off on completion
```

```[tasklist]
### iOS
- [x] Design sign-off on completion
- [x] QA sign-off on completion
- [x] Product sign-off on completion
```

## Known issues

* https://github.com/matrix-org/matrix-rust-sdk/issues/1770
* https://github.com/matrix-org/sliding-sync/issues/66
* https://github.com/matrix-org/sliding-sync/issues/81
* https://github.com/matrix-org/matrix-rust-sdk/issues/1771

**Comment by alfogrillo** [comment]
@kittykat 
I noticed we have a different story for [inviting](https://github.com/vector-im/element-meta/issues/995).
Inviting isn't really a dependency of joining (you may use other matrix clients to invite).
However it would be better to implement the invite first, so that we can test everything on Element X after this story has been implemented.
I'm not sure how stories are ordered the [epic](https://github.com/vector-im/element-meta/issues/988), but having them sorted in the "expected" implementation order would be better.

**Comment by amshakal** [comment]
Reviwed and added designs

**Comment by kittykat** [comment]
@alfogrillo we're generally putting them roughly into what feels like priority/logical order but totally fine to change if you feel that's needed. I had trouble rearranging the order in some issues at one point!

**Comment by ghost** [comment]
**Update:** _I noticed the room appear in my room list several minutes after posting my initial comment. It seems like that amount of time is less than ideal for Element X. Aside from that I can at least confirm the acceptance criteria are met._ 

----

I can't seem to get this working on iPhone 12 mini with iOS 16.3.1 and Element X 1.1.0 (218). Even trying the work around of joining the room after invite in Element legacy then switching back to Element X doesn't seem to be working. The room shows up properly in the legacy app but it's not even showing up in the room list in Element X for me. 

I have the _Show Invites flow_ flag on in the developer options in case that matters here.

**Comment by alfogrillo** [comment]
@ashughes1 invite list is available under "Show invites flow" flag on Element X nightly.

You should be able to:
- See the invites
- Accept/decline invites

Please try to log off/in and/or delete/reinstall the app.
It may also be worth using another account.
Remember that you need at least a pending invite to see the "invites" button in the home.

https://github.com/vector-im/element-meta/assets/19324622/d139cd56-da49-4702-adc9-b24a1e908b44

**Comment by ghost** [comment]
Thank you @alfogrillo, this is working for me now with Element X 1.1.1 (222). I will resume my testing and report back ASAP.

**Comment by ghost** [comment]
Results from testing Element X Nightly 1.1.1 (222) / iPhone 12 mini with iOS 16.3.1.
**Status**: :heavy_check_mark: QA signed off for iOS

----
#### Things that worked as expected
* _Invites_ shows at the top above the room list when there are pending invites
* A green dot is shown next to _Invites_ if there are unread invites
* An invite shows the room avatar and name, the avatar and name of the person who invited me along with the words "[user] invited you" and a green dot if the invite has not yet been seen 
* Declining an invite
* Cancel declining an invite
* Receiving an invite to a room where I previously declined an invite
* Accepting an invite to a public room
* Accepting an invite to a private room
* When accepting an invite I am taken to the room immediately and can see the chat history

#### Issues encountered
* While viewing the invitation list I sent myself several other room invites but these did not populate the invitation list until I quit and restarted the app. After restarting the app I could not replicate this behaviour.
* After accepting an invite to a room with one other person and tapping on the room details view for that room, it shows a user count of 1 when it should show 2. Opening the _People_ view shows me under _Pending_ with the other user under the _person_ list. 
_**Update:** See #1702_

@alfogrillo please advise if I should file a GH issue for any of the above.

**Comment by ghost** [comment]
Sorry, please ignore me tagging #1701 on this issue, wrong user story.

**Comment by alfogrillo** [comment]
@ashughes1 

> While viewing the invitation list I sent myself several other room invites but these did not populate the invitation list until I quit and restarted the app. After restarting the app I could not replicate this behaviour.

Not sure what happened, but if you don't see it anymore I wouldn't spend more time on that. The sliding sync that powers the invites list is still under development. Sometime strange things may happen. 😄 

> After accepting an invite to a room with one other person and tapping on the room details view for that room, it shows a user count of 1 when it should show 2. Opening the People view shows me under Pending with the other user under the person list.

Answered in the related issue.

**Comment by Johennes** [comment]
Closing this since we've reviewed it in the weekly on Tuesday and shipped it in the iOS TestFlight today. Any further issues can be tracked under the epic which I'm keeping open until QA has processed the whole scope.

**Comment by ghost** [comment]
#### QA Status
:+1: for public testing

#### Notes
Retested this on Element X iOS 1.1.8 (271) and Element X Android Nightly 0.1.0-nightly (1001000) built on July 1, 2023. It meets the acceptance criteria noted above with no further issues found. Will loop back to the Epic for the broader scope but calling this story done from a QA perspective.
