### ISSUE TITLE
[Story] Leave a room from "all chats" screen

### ISSUE THREAD

**Issue by kittykat** [vector-im/element-meta#992]
As a user I want to able to leave room so I can get rid of conversations that don't matter to me anymore.

On the room list
- swipe to the left on a room list item.
- Show a context menu
- Have an option to leave a room
- Show a hint that the user need to confirm that he wants to leave the room

When the user leaves the room show a room event that the user has left the room.

## Scope

```[tasklist]
### Engineering
- [ ] https://github.com/vector-im/element-meta/issues/1175
```

## Out of scope

- Leaving a room from the room details: https://github.com/vector-im/element-meta/issues/1104
    - Already implemented on iOS (by EX platform team)

## Sign-off

```[tasklist]
### Android
- [x] Design sign-off on completion
- [ ] QA sign-off on completion
- [x] Product sign-off on completion
```

```[tasklist]
### iOS
- [x] Design sign-off on completion
- [x] QA sign-off on completion
- [x] Product sign-off on completion
```

**Comment by amshakal** [comment]
Should this story fall here or under https://github.com/vector-im/internal-planning/issues/334

I am noticing some duplication. Please let me know which team is working on it.

**Comment by amshakal** [comment]
Link to figma: 
https://www.figma.com/file/0MMNu7cTOzLOlWb7ctTkv3/Element-X-(new)?node-id=1386%3A81234&t=8VO6vy4FXF4GvEKl-1

**Comment by Johennes** [comment]
@alfogrillo FYI: I've removed the piece about also implementing leaving a room from the room details. We discussed it among the leads today and the platform team is going to work on this part with https://github.com/vector-im/element-meta/issues/1104.

**Comment by alfogrillo** [comment]
> @alfogrillo FYI: I've removed the piece about also implementing leaving a room from the room details. We discussed it among the leads today and the platform team is going to work on this part with #1104.

Yeah, this story is just about leaving the room from "all chats" screen using quick actions.
We can already leave a room from room's detail in EX iOS nightly. ;)

**Comment by ghost** [comment]
### Status
**Tested on:** iPhone 12 mini | iOS 16.3.1 | Element X 1.1.10 (218)
**QA Status:** :question: iOS | :white_circle: Android  
> *Legend: :heavy_check_mark: signed off | :gear: in progress | :white_circle: not started | :question: conditional pass | :x: not passed*
----

### Commentary
This seems to be working as expected on iOS although:

1. The access path to the context menu is a long press, not a swipe left as indicated in the initial acceptance criteria
2. There is no "Left Room" UI as in the Figma mockup, the room is simply removed from the "All Chats" view:
![Screenshot from 2023-05-19 13-39-57](https://github.com/vector-im/element-meta/assets/766595/62f6f18f-6a68-4bea-b69d-79dec097b259)

### Update
_2023-05-19 14:33 PDT_
I am finding that sometimes the room does _not_ disappear from my room list and I can tap it to resume chatting in the room as if I never left, but the message fails to send. Because of this I am changing my QA sign-off to a conditional pass.
![IMG_3823](https://github.com/vector-im/element-meta/assets/766595/c6387942-d8bb-4b18-b8b3-cda7958a14a6)

**Comment by alfogrillo** [comment]
@ashughes1 

> The access path to the context menu is a long press, not a swipe left as indicated in the initial acceptance criteria

Long press is correct. The AC is wrong.

> There is no "Left Room" UI as in the Figma mockup, the room is simply removed from the "All Chats" view:

We forgot to add it. There is a [pending PR](https://github.com/vector-im/element-x-ios/pull/981) for it.

> I am finding that sometimes the room does not disappear from my room list and I can tap it to resume chatting in the room as if I never left, but the message fails to send. Because of this I am changing my QA sign-off to a conditional pass.

We totally rely on the sliding sync to remove left rooms from the chat list. Sometimes I noticed the update is slow like you say.
In this case I think we receive sync updates late, but we need to investigate this better.

**Comment by kittykat** [comment]
@alfogrillo do we have an issue to track investigating further the problem with sliding sync?

**Comment by alfogrillo** [comment]
> @alfogrillo do we have an issue to track investigating further the problem with sliding sync?

Sorry for the late response. 
I'm not aware of any related issue in the feature team.
I guess we need to check if other teams are already aware of this problem (I can ask them soon).

**Comment by Johennes** [comment]
Closing this since we've reviewed it in the weekly on Tuesday and shipped it in the iOS TestFlight today. Any further issues can be tracked under the epic which I'm keeping open until QA has processed the whole scope.

**Comment by ghost** [comment]
I was retesting this on Element X iOS 1.1.8 (271) and Element X Android Nightly 0.1.0-nightly (1001000) built on July 1, 2023 but unfortunately for Android I am hitting a new issue: https://github.com/vector-im/element-x-android/issues/765.

Is this reproducible for anyone else? If so, we should try to get this fixed before shipping for public testing. If not, I wouldn't hold the release for it.

**Comment by alfogrillo** [comment]
> I was retesting this on Element X iOS 1.1.8 (271) and Element X Android Nightly 0.1.0-nightly (1001000) built on July 1, 2023 but unfortunately for Android I am hitting a new issue: [vector-im/element-x-android#765](https://github.com/vector-im/element-x-android/issues/765).
> 
> Is this reproducible for anyone else? If so, we should try to get this fixed before shipping for public testing. If not, I wouldn't hold the release for it.

@csmith @julioromano can you have a look here when you have time?

**Comment by csmith** [comment]
```
2023-07-04T10:48:27*685GMT+00:00Z 101 E/ /Tag: Error while leaving room QA: Test join a room following invite - !WuPyhEEyrlRAKPyTeC:element.io
org.matrix.rustcomponents.sdk.ClientException$Generic: msg=Can't leave a room that isn't in joined state
	at org.matrix.rustcomponents.sdk.FfiConverterTypeClientError.read(SourceFile:26)
	at org.matrix.rustcomponents.sdk.FfiConverterRustBuffer$DefaultImpls.liftFromRustBuffer(SourceFile:13)
	at org.matrix.rustcomponents.sdk.FfiConverterTypeClientError.liftFromRustBuffer(Unknown Source:0)
	at org.matrix.rustcomponents.sdk.FfiConverterRustBuffer$DefaultImpls.lift(Unknown Source:5)
	at org.matrix.rustcomponents.sdk.ClientException$ErrorHandler.lift(SourceFile:8)
	at org.matrix.rustcomponents.sdk.Matrix_sdk_ffiKt.access$checkCallStatus(SourceFile:114)
	at org.matrix.rustcomponents.sdk.Room.leave(SourceFile:54)
	at io.element.android.libraries.matrix.impl.room.RustMatrixRoom$leave$2.invokeSuspend(SourceFile:12)
	at io.element.android.libraries.matrix.impl.room.RustMatrixRoom$leave$2.invoke(SourceFile:13)
...
```

I think this is https://github.com/matrix-org/matrix-rust-sdk/issues/2078 rearing its ugly head again :disappointed:
