### ISSUE TITLE
[Story] Create a new room

### ISSUE THREAD

**Issue by kittykat** [vector-im/element-meta#993]
As a user I want to create a new chat with more than one person so that I can communicate with a group of people.

- Add an option to create group chats to the room list view
- Open a new view similar to the one in https://github.com/vector-im/internal-planning/issues/305
- The user can pick multiple other users to add to the group
- If the user taps "next" the room can be customised:
- Choose a name "What is the group about" & set avatar
- The room is encrypted.

For setting avatar:
> - If the user taps on the (placeholder) avatar they get presented two options: "Take a picture" and "Choose from gallery"
> -  Take a picture opens the camera
>   - The user can take a picture
>   - The user can tap "save" and the picture is used as an avatar for the group
>   - The picture is NOT saved to to the OS picture library <- UX?
> - Choose from gallery open the personal picture gallery.
>   - The user can pick a picture of her gallery
>   - The user can tap "save" and the picture is used as an avatar for the group
> In both cases a permission dialog from the phone OS may appear.

The room is created once the user taps "create".

For UX
Should we at all provide the option to create unencrypted group chats?

I am also tempted to leave the Private Room / Public Room out of the creation process and instead provide the option in the room settings. What is you opinion on that?

## Scope

```[tasklist]
### Engineering
- [ ] https://github.com/vector-im/element-meta/issues/1057
- [ ] https://github.com/vector-im/element-meta/issues/1058
- [ ] https://github.com/vector-im/element-meta/issues/1059
- [ ] https://github.com/vector-im/element-meta/issues/1062
- [ ] https://github.com/vector-im/element-meta/issues/1082
- [ ] https://github.com/vector-im/element-meta/issues/1061
```

## Out of scope

- Changing the avatar

## Sign-off

```[tasklist]
### Android
- [x] Design sign-off on completion
- [x] QA sign-off on completion
- [x] Product sign-off on completion
```

```[tasklist]
### iOS
- [x] Design sign-off on completion
- [x] QA sign-off on completion
- [x] Product sign-off on completion
```

**Comment by alfogrillo** [comment]
> Should we at all provide the option to create unencrypted group chats?

fwiw Element X iOS looks already rendering unencrypted rooms in the timeline.
We could try to ask Element X platform to see if they support fully it or not.
If yes, adding the support for creating a new unencrypted room should be easy enough.

**Comment by amshakal** [comment]
Link to figma 

iOS: https://www.figma.com/file/0MMNu7cTOzLOlWb7ctTkv3/Element-X-(new)?node-id=194%3A32460&t=xokbJVDDwrwgmiTk-1

Android:https://www.figma.com/file/0MMNu7cTOzLOlWb7ctTkv3/Element-X-(new)?node-id=595%3A71791&t=xokbJVDDwrwgmiTk-1

**Comment by Johennes** [comment]
Closing this since we've reviewed it in the weekly on Tuesday and shipped it in the iOS TestFlight today. Any further issues can be tracked under the epic which I'm keeping open until QA has processed the whole scope.

**Comment by ghost** [comment]
#### QA Sign-off Status:
🟢 Element X iOS 1.1.8 (271)
🟢 Element X Android 0.1.0-nightly (July 5, 2023)

#### Details
I ran the following tests and found no major issues, so deem this good enough for public testing.
* Test creating a private room
* Test creating a public room
* Test setting an avatar (from photos and camera) and topic during room creation
* Test inviting users to room before room creation
* Test inviting a blocked user during room creation
* Test inviting myself to a room during room creation

On the last two points I encountered some behaviour I want to confirm is intended before I file an issue:
1. I am able to invite a user I have blocked to a room, but should I be able to do that?
2. I am able to select myself as an invitee to a room at creation but if I am the only invitee selected I get an error "An error occurred when creating the room". I think this can be improved by either A) not populating a user search list with my own account, B) treating room creation with only myself selected the same as skipping invites at room creation, or C) providing a more helpful error message so the user has a hint at what to do to succeed next time.

I do not think either of these issues are blocking.

**Comment by Johennes** [comment]
> I am able to invite a user I have blocked to a room, but should I be able to do that?

This isn't explicitly forbidden by the [spec](https://spec.matrix.org/v1.7/client-server-api/#ignoring-users), only the other direction is (the ignored user inviting you). Unless we have a UI to unignore a user without having to find them in a room, we might want to continue allowing this. CC @VolkerJunginger

> I am able to select myself as an invitee to a room

You shouldn't be able to invite yourself into a room IMO.

**Comment by alfogrillo** [comment]
> I am able to select myself as an invitee to a room at creation but if I am the only invitee selected I get an error "An error occurred when creating the room". I think this can be improved by either A) not populating a user search list with my own account

Currently we don't filter out the account owner from the home server response. I think we should.
Happy to do this now? It should be quick enough. fyi @Johennes @VolkerJunginger

**Comment by Johennes** [comment]
Yes, let's do it. @csmith could you check / fix Android? And does either of you need an issue for this?

**Comment by csmith** [comment]
So we're filtering out the current user from _all_ directory searches? (i.e., these three: Inviting users to a new room, creating a DM, inviting users to an existing room)

No need for an issue, should be small as Alfonso said :)

**Comment by Johennes** [comment]
> So we're filtering out the current user from all directory searches? (i.e., these three: Inviting users to a new room, creating a DM, inviting users to an existing room)

Yes, I'd say so. It doesn't really make sense to add yourself in any of these.

**Comment by ghost** [comment]
Setting this back to _Team QA: In progress_ so the improvements discussed above can be tested when ready.

**Comment by alfogrillo** [comment]
Addressed [here](https://github.com/vector-im/element-x-ios/pull/1266) on iOS

**Comment by csmith** [comment]
Android PR: https://github.com/vector-im/element-x-android/pull/797

**Comment by ghost** [comment]
Tested EX iOS 1.2.1 (280) and EX Android 0.1.0-Nightly July 11, 2023, and confirm this is now fixed. Marking this done for QA, please tag me if there is something else I can help with here.
