### ISSUE TITLE
[Story] Change rooms' state (avatar, invite more people) 

### ISSUE THREAD

**Issue by kittykat** [vector-im/element-meta#994]
As a user having the appropriate permissions (aka. power level) in the room I want to be able to change the room's avatar so that I can personalize it. I also want to be able to invite more people in the room.

In the room detail view show the room avatar.
- If the user taps on the (placeholder) avatar they get presented with two options: "Take a picture" and "choose from gallery"

Add an option to the "Room details > People" view to add (invite) other users.
- Tapping on that button opens an add users view similar to the view #993
- Users can select one or more other users to invite to the room

**Designs**
- [Change avatar](https://www.figma.com/file/0MMNu7cTOzLOlWb7ctTkv3/Element-X-(new)?node-id=1056-77958&t=I58RGk3eFIobEKPz-0)
- [Invite more people](https://www.figma.com/file/0MMNu7cTOzLOlWb7ctTkv3/Element-X-(new)?node-id=1110-80652&t=qZeSBWPTIQUm0zoV-0)

## Scope

```[tasklist]
### Engineering
- [ ] https://github.com/vector-im/element-meta/issues/1165
- [ ] https://github.com/vector-im/element-meta/issues/1166
- [ ] https://github.com/vector-im/element-meta/issues/1168
```

## Out of scope

- Cropping the picture of avatars

## Sign-off

```[tasklist]
### Android
- [x] Design sign-off on completion
- [ ] QA sign-off on completion
- [x] Product sign-off on completion
```

```[tasklist]
### iOS
- [x] Design sign-off on completion
- [ ] QA sign-off on completion
- [x] Product sign-off on completion
```

**Comment by ShadowJonathan** [comment]
I have one objection to the terminology here, I'd recommend using "icon" for a room's title image, not "avatar", as the latter made me think (when reading the title of this issue) that this issue was about changing a room-specific user avatar, similar to how you could set your nicknames in a room.

**Comment by Johennes** [comment]
Closing this since we've reviewed it in the weekly on Tuesday and shipped it in the iOS TestFlight today. Any further issues can be tracked under the epic which I'm keeping open until QA has processed the whole scope.
