### ISSUE TITLE
[Story] Invite additional users to a room

### ISSUE THREAD

**Issue by kittykat** [vector-im/element-meta#995]
As a user that has created a room, I want to invite additional users to share my words of wisdom with others.

Add an option to the "Room details > People" view to add (invite) other users.
- Tapping on that button opens an add users view similar to the view #993
- Users can select one or more other users to invite to the room

Stretch goals for the invite view:
- People that I know (have DMs with) are top of the list for invite suggestions
- People who share rooms with me are second priority

[Figma](https://www.figma.com/file/0MMNu7cTOzLOlWb7ctTkv3/Element-X-(new)?node-id=5-7388&t=Q85v7VhyQ684I7PS-0)

## Scope

```[tasklist]
### Android
- [ ] TBD
- [ ] Design signoff on completion
- [ ] QA signoff on completion
- [ ] Product signoff on completion
```

```[tasklist]
### iOS
- [ ] TBD
- [ ] Design signoff on completion
- [ ] QA signoff on completion
- [ ] Product signoff on completion
```

##  Stretch goals
None at this time

## Out of scope
- TBD

**Comment by alfogrillo** [comment]
Merged into https://github.com/vector-im/element-meta/issues/994
